### ISSUE TITLE
[Bug] Paged operations model response type names don't match the actual model name

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#101]
For reference https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/payload/pageable

Looking at the SdkHttpOperation.responses, the returned model has the name “PagedUser” which doesn’t match the underlying model name “User”. As a result, we don’t know how to map the response type name to the corresponding model name. I suppose we could remove the “Paged” prefix but that seems like a bit of a hack. What’s the reasoning behind the discrepancy and, if it must remain this way, what’s the proper way to map “PagedUser” to “User” (i.e. for Paged<T> how do I get the type name of T)?

**Comment by tadelesh** [comment]
@iscai-msft we may add sth like page item just like lro logical result. what do you think?

**Comment by iscai-msft** [comment]
talked with @jhendrixMSFT, this information already exists. If you go onto `method.response`, there is optional property `responsePath`. If that exists, it tells you the path to take to get from a service response -> the final method response. For paging, the service will return the paged model (which tsp gives to us as `PagedUser`). `PagedUser` has two properties: `nextLink`, and `items`. The method response ultimately returns `items` to the user, so in this case, `method.response.responsePath === "items"`

**Comment by jhendrixMSFT** [comment]
I think this is a non-issue and a bit of user error so closing.
