### ISSUE TITLE
Add `BaseModel` or `BaseType` to `SdkArrayType`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1014]
Because this is a valid syntax:
```typespec
model MyArray extends MyArrayInternal {}

model MyArrayInternal is Array<int32>;
```
maybe it is needed that we add a `BaseModel` or `BaseType` to `SdkArrayType`.

This is not a hard requirement of anything, just thinking about the completeness of TCGC's model.

**Comment by ArcturusZhang** [comment]
Related https://github.com/Azure/typespec-azure/issues/1020

**Comment by iscai-msft** [comment]
closing in favor of https://github.com/Azure/typespec-azure/issues/1020
