### ISSUE TITLE
[Bug]: type graph view crash for azure playground

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1016]
### Describe the bug

![image](https://github.com/Azure/typespec-azure/assets/1726438/ada1ccfe-391e-4078-a750-b7e23239d245)

### Reproduction

1. import `typespec-azure-resource-manager`
2. click type graph view
3. crash

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Seems to be coming from something in azure-core, repro by just importing azure-core

**Comment by timotheeguerin** [comment]
issue seems to be when using a default value
```
model Foo {
 a: int32 = 123;
}
```
