### ISSUE TITLE
[Bug] TCGC models constant params as required params

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#102]
For example, the `Accept` header with value `application/json` is showing up as a required parameter. M4 models these params as constant values (i.e. `param.type.kind` would be `constant`) so we know we don't need to add an explicit parameter, just set the header directly in the generated code.

**Comment by jhendrixMSFT** [comment]
What I've observed, at least in this case, is that the parameter is marked as required with `clientDefaultValue` set which seems a bit odd; i.e. how can you have a client-side default value for a required parameter, doesn't that by definition make the param optional?

**Comment by iscai-msft** [comment]
@jhendrixMSFT can you provide a tsp example? I thought we were running into the same issue, but the issue I'm fixing for Python is actually Python specific. Thanks!

**Comment by jhendrixMSFT** [comment]
Here's an example from `/cadl-ranch-specs/http/encode/datetime/main.tsp` although it's not limited to this spec (i.e. any operation with an `Accept` header param will exhibit this issue).

![image](https://github.com/Azure/typespec-azure/assets/10090263/b089d30d-a44c-4876-b0a1-771000684e89)

This is impossible to distinguish from a "vanilla" required param with a client default value. I would expect `param.type.kind` to be `constant` with the fields appropriately filled out (and ideally with `clientDefaultValue` set to `undefined` as it's constant). [This](https://github.com/Azure/autorest.go/blob/main/packages/typespec-go/src/tcgcadapter/clients.ts#L323-L333) is how I worked around it by applying this pattern.

This is how M4 models such params.

![image](https://github.com/Azure/typespec-azure/assets/10090263/57a2e7fa-a938-4e83-8223-04dc844f8c1b)

As you can see, the param's type is `constant` so we know it's not provided by the caller.

**Comment by jhendrixMSFT** [comment]
To clarify, I'm not saying we have to do it the same way that M4 does if there's a different/better way. But, given that we already have a `constant` construct, it seems like the natural fit without adding any new machinery.
