### ISSUE TITLE
`model Foo extends Array<T>{}` is parsed as a model in TCGC

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1020]
if we have:
```typespec
model Foo extends Array<string>{}
model Bar extends int32[] {}
```
both `Foo` and `Bar` will be returned as `SdkModelType` and appear in the `getAllModels`'s models list.
This is incorrect. They should be `SdkArrayType`.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/typespec-azure/issues/1014
```

**Comment by ArcturusZhang** [comment]
it is claimed as by design in typespec that `extends Array<T>` does not inherit the indexer: https://github.com/microsoft/typespec/issues/3597 which I did not totally buy in.

but if typespec will not change this, we could always work this around in TCGC.

Currently we do not have urgent needs for this. Maybe we could convince the typespec team to remove this syntax completely since it stops making sense if the indexer is not inherited.

**Comment by iscai-msft** [comment]
@ArcturusZhang what is the usecase for this?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang what is the usecase for this?

there is no real use cases, just coming from the thought that since we could write it without compilation error, then we need to support it properly, such as this case:
```typespec
// in azure core
model EmbeddingVector<T> is Array<T>;

// in my own typespec
model MyEmbedding extends EmbeddingVector<int32> {} // now our implementation completely lose the information for embedding vector from azure core, and this is parsed as a model which is incorrect.
```

**Comment by iscai-msft** [comment]
It seems this has been fixed by your pr, going to close this. If there's still an issue, feel free to reopen
