### ISSUE TITLE
Question for `resourceUri` parameter of extension resource

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1022]
The definition is as follows: 
```
@doc("The default resourceUri parameter type.")
model ResourceUriParameter {
  @path
  @doc("The fully qualified Azure Resource manager identifier of the resource.")
  @extension("x-ms-skip-url-encoding", true)
  @resourceParameterBaseFor([ResourceHome.Extension])
  resourceUri: string;
}
```
How can emitter know the `resourceUri` does not need url encoding since it is not typed with `url`? IDK whether `url` type is by design for that?

**Comment by live1206** [comment]
I am reading from extension in emitter for .NET

**Comment by tadelesh** [comment]
blocking scvmm release.

**Comment by MaryGao** [comment]
@timotheeguerin I heard that we have assumption that for type `url` it would implicitly imply `true` for x-ms-skip-url-encoding and with type `string` it would imply `false`. Is this correct?

Personally I don't think url vs string type would imply any encoding info.

**Comment by tadelesh** [comment]
found some previous discussion but not fully understood the final decision. @markcowl could you also help with this question?

**Comment by ArcturusZhang** [comment]
why not we just model the type of `resourceUri` to `armResourceIdentifier`? In practice, this place is always an `armResourceIdentifier`.
And we could add the `skip-url-encoding` extension to the definition of `armResourceIdentifier` because when an arm id was put in path, url encoding should always be skipped.

**Comment by ArcturusZhang** [comment]
Also there is a requirement from dotnet MPG generator that this type is an arm id.

**Comment by tadelesh** [comment]
the difficulty here is to be backward compatible with swagger: https://github.com/Azure/azure-rest-api-specs/blob/87a08b955c257c773a3bd42553c718d4b1092955/specification/common-types/resource-management/v6/types.json#L627

**Comment by timotheeguerin** [comment]
will close in favor of hte core design issue for this https://github.com/microsoft/typespec/issues/3736

**Comment by MaryGao** [comment]
We need to re-open because the relevant definition is not updated yet.

**Comment by timotheeguerin** [comment]
Reopening as `uriTemplate` were added so `resourceUri` path param can be updated. Either using the `allowReserved` or adding the `+` operator in the path
