### ISSUE TITLE
[tcgc] `final-state-via` representation in TCGC

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1023]
With `getLroMetadata`, we could get `final-state-via` for now, but tcgc does not expose it. Need to add it to `SdkLroServiceMethodOptions`.

**Comment by iscai-msft** [comment]
We're not going to add `final-state-via` in tcgc, instead we're going to use the `@useFinalStateVia` from `Azure.Core`, coupled with `.decorators`
