### ISSUE TITLE
[tcgc] support multiple services in one tsp specification

### ISSUE THREAD

**Issue by chunyu3** [Azure/typespec-azure#1024]
When the typespec define multiple services, each service contains different apiVersions, authentication and clients(see following)
TCGC need to provide api to retrieve apiversions, authentications and clients belongs to one service
- `getVersions(service: Service)`: list all the api-versions of the service
-  `listClients(service: Service) `:  lists all the clients which belongs to the services.
- `getAuthentication(service: Service)`:  return the authentications the service supported.
- support service scope for @client decorator

```

@versioned(Versions1)
@service({
  title: "HttpbinServer",
  version: "1.0.0",
})
@server(
  "https://{domain}.{tld}",
  "Httpbin endpoint",
  {
    @doc("second-level domain, use httpbin")
    domain?: string = "httpbin",

    @doc("top-level domain, use org")
    tld?: string = "org",
  }
)
namespace Typespec.Server {
  @route("/status/{code}")
  interface ServerOp {
    status(@path code: int32): OkResponse | NoContentResponse;
  }
}
enum Versions1 {
    @useDependency(Azure.Core.Versions.v1_0_Preview_1)
    "2022-05-15-preview"
  }

enum APIVersions {
    v1: "v1",
  }

@versioned(APIVersions )
@service({
  title: "ContosoServer",
})
@server(
  "{Endpoint}/contoso/{ApiVersion}",
  "Service endpoint",
  {
    @doc("Service endpoint")
    Endpoint: string,

    @doc("Api Version")
    @path
    ApiVersion: APIVersions,
  }
)
namespace ContosoServer {

  @route("/contoso")
  interface ServerOp {
    get(@path code: int32): OkResponse | NoContentResponse;
  }
}
```
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/typespec-azure/issues/441
- [ ] https://github.com/Azure/typespec-azure/issues/441
```

**Comment by iscai-msft** [comment]
@chunyu3 we don't need these individual operations to support it, this is already supported as part of `SdkPackage.clients`, which is where you should be getting the information from. I'm going to close this because this funcationality already exists
