### ISSUE TITLE
Generate Azure.ResourceManager.CommonTypes schemas and include v6

### ISSUE THREAD

**Issue by abatishchev** [Azure/typespec-azure#1028]
### Clear and concise description of the problem

Attempting to reference the latest version of the Common Types:

```
@armCommonTypesVersion(Azure.ResourceManager.CommonTypes.Versions.v6)
```

fails with an error:

```
Error (active)	invalid-ref	Enum doesn't have member v6
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by abatishchev** [comment]
Related to #653 but here I'm asking only to enrich the enum member, if this makes any sense.

**Comment by allenjzhang** [comment]
Hi, Alex, with the complete reorg of ARM common types in TypeSpec, the release of common type will not be piece meal anymore. ie, if adding xxx.json in v6 and later on add another change in types.json in v6 without worrying about breaking change. 
I am going to work with ARM team to transition moving authoring in TypeSpec. Please stay tuned.
