### ISSUE TITLE
bug(tcgc): `getSdkHttpParameter()` doesn't handle default value

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1030]
### Describe the bug

We try to set a endpoint parameter with default value in https://github.com/Azure/cadl-ranch/pull/598
```typescript
@server(
  "{endpoint}",
  "Test server endpoint",
  {
    endpoint: string = "http://localhost:3000",
  }
)
```
The parameter can be fetched in TCGC, but default value is not parsed. Check the source codes of `getSdkHttpParameter()`, and it seems not handle default value: https://github.com/Azure/typespec-azure/blob/5c10b3e3524936610283b4044ddd01c73a22827f/packages/typespec-client-generator-core/src/http.ts#L294

### Reproduction

Just try to parse the definition above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
@iscai-msft i remembered that only when the default value is happened in server endpoint that we will use it as client default value, is that right? if so, it seems we missed this in current code.

**Comment by iscai-msft** [comment]
Yep, it's only for api version and endpoint. This information is in `.templateArguments` though, so I don't think this is an issue. Closing. If it's still an issue can you reopen @archerzz

**Comment by archerzz** [comment]
@iscai-msft for parameters in `.templateArguments`, looks like I could not get the defaut value unless I parse the `__raw.defaultValue`. Maybe we should set the `.clientDefaultValue`?
![image](https://github.com/user-attachments/assets/8fd90622-4747-4913-8fc7-55c219ffc162)

**Comment by iscai-msft** [comment]
This is a good point, we purposefully don't take `defaultValue` into account unless for endpoint or api-version related information. I think we should take into account this information since this is endpoint related. I'm going to make a PR and merge it after I make sure people are ok with it. Thanks @archerzz
