### ISSUE TITLE
resource model changes of generated SDK code based on TSP compared with swagger

### ISSUE THREAD

**Issue by msyyc** [Azure/typespec-azure#104]
By comparing [diff](https://github.com/Azure/autorest.python/issues/2312) about generated SDK between TSP and swagger, I find some model name changes: 
- `Resource-> ArmResource`
- `ProxyResource-> ProxyResourceBase`
- `TrackedResource-> TrackedResourceBase`

I think it is related with [tsp definition of tyepsec-azure-resource-manager](https://github.com/Azure/typespec-azure/blob/9cc71b864dde3fad7f82c333049711ed407aca5f/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L23)

**Comment by allenjzhang** [comment]
Is this the exhaust list? `@@projectedName` should be used to adjust client name.

**Comment by tadelesh** [comment]
Workaround: review all TSP ARM model and rename them with `@projectedName` according to the name in common types.

**Comment by markcowl** [comment]
If we are going to support very old APIs, there are several possible patterns:
- Resource is defined in the spec
- Resource types inherit from 'Resource' or similar common schema
- Resource types inherit from another common schema (e.g. ProxyResource, even if they are tracked resources)

The right things is to generate the proper inheritance in this case and not use the resource templates, the template constraints use structural typing, not nominal typing, so any model with the right properties will work as in [this playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgpAYXJtUHJvdmlkZXJOYW1lc3BhY2UKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zb8guSHViQ2xpZW50IiwKICDnAS06ICIyMDIxLTEwLTAxLXByZXZpZXciLAp9KQpAZG9jKMhFIOgAiiDITyDmAQptZW50IEFQSS4iKQpAdXNlRGVwZW5kZW5jeSj1AMPoAP1zLnYxXzBfUMZyXzEp5QDaQ29tbW9u5AEpc8co10bLKctSNSkKbugBFCBNaWNyb3NvZnQu8gEJ5AFJ5QDfQSDSHSDoAe0iKQptb2RlbCBFbXBsb3llZSDkAV%2FGOeQBfCBvZiBlxxsiKcQbcGF0dGVybigiXlthLXpBLVowLTktXXszLDI0fSTGI2tleSgiyDbERsk6aMQIc2Vn5AFTyiNzxiB2aXNpYmlsaXR5KCJyZWFkxRbkAO06IHN0cuUCSwogIC8qKiBUaGXpAMIgSWQgKi%2FZQGlk3j7kAwXcQMQg0ULIPi3kAz9pZmljIHByb3BlcnRpZXPGTcoQPzrpAVxQyRXFSi4uLvYB%2BkZvdW5kYXTlAfFBcm1UYWdzxzt5Owp96AHYyFbLbPEBzspy6wHYQWfyAddhZ2U%2FOiBpbnQzMuUAnMYqQ2l0edErY2l0eT%2FtARPGLVByb2ZpbNJbQGVuY29kZSgiYmFzZTY0dXJsxRdwxi8%2FOiBieXTnARL2AYPGX%2BQBtnN0YXR1c8RidGhlIGxhc3Qg5ADg5QEr5AOexVbEROUEelN0YXTEYOUC%2BMwU6wFFxFbMNMVj5QDEYekB5sRaQGxyb8Q8dXMKZW51bdJU5QFgLi7pAczRISzqASrtAoFpcyBiZcR66QCHZeYA98xC2z11cOQCK25nxTRVxw3fbWcgZGVsZXTHaUTEDNs1Y3Jl5ADhcmVxdWVzdCBoYcRFZW4gYWNjZXDIRUHHDSzkAVxpbnRlcmbkBKJP6AGfcyBleHRlbmRz9gX3Lsspe30KLy%2FuAsjlANjlAL9PcMQlYWzqAto8xh1hYmzrAu88yDo%2BPjvlBXfIcMpo6wCmyC3mAyZnZXTEakHKNVJlYWTKUjvkAwXlARRPcuoAmcsvQ80dQXN5bmPOPuUBtMg2Q3VzdG9tUGF0Y2hTzCos6QCXxTTmAbLPauUBu2XNN8UtbGlzdEJ5yCZHcm91cM86TMUiUGFyZW501DxTdWJzY3Jp5QFuxzvGM8wZzDl9Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by tadelesh** [comment]
@markcowl thanks for your solution for non-standard resource definition.
Two concerns for the standard resource:
1. When sdk emitter get models info directly from tsp, we will get `ProxyResourceBase` as the base model, which name is different from swagger definition, thus will cause breaking changes for brown field RPs.
2. I don't see different version's common types defined in arm lib. Could sdk emitter get different properties info according to `@armCommonTypesVersion` setting directly from tsp compile?

**Comment by markcowl** [comment]
@tadelesh Those types also have an `@armCommonTypes` definition - the generator should be making these decisions for compliant specs by the ARM common types definition, so this decorator may be useful in the 'compliant' case.

There are differences in the common types version, strictly around type formats (resourceId, uri, uuid), there have not, to date been any substantial differences other than these

**Comment by markcowl** [comment]
The solution we have discussed is:
- Rename the types in the inheritance chain for ProxyResource, TrackedResource and ExtensionResource, so these align with common type schema names
- Add models matching other resource types in common schema for use when defining non-standard (not ProxyResource or Trackedresource) inheritance.

**Comment by allenjzhang** [comment]
#762
