### ISSUE TITLE
[Bug]: [ARM][SDK] armRenameListByOperation decorator prevent client.tsp re-arrange the operation groups

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#1052]
### Describe the bug

SDK emitter (and TCGC) takes interface (interface with `@client`/`@operationGroup` in client.tsp takes precedence) to group the client and operation groups.

`@armRenameListByOperation` decorator on `ArmResourceListByParent` operation template would rename the operation to pattern `listBy<parent-resource-name>`. This present SDK putting 2 or more ArmResourceListByParent operation (different resource, but same parent resource) to a single operation groups.
See https://gist.github.com/weidongxu-microsoft/fa420c35cf0611a62a8d155771dd3425#known-approach-to-group-operations

For brownfield service, SDK would need to keep the operation group structure, to avoid breaking changes.

One solution would be to remove the `@armRenameListByOperation` decorator from `ArmResourceListByParent` operation template.
But this leaves one question: what can we do to guide (particularly greenfield) service dev on operation name. E.g. it would be welcome that the operation name being consistent for new services, e.g. `listByResourceGroup` or `listByTenant`.

If we remove the decorator, breakdown could be
1. rename all existing operation to the expected name of `@armRenameListByOperation` (so that operation name would be same, regardless of the existence of `@armRenameListByOperation`)
2. remove `@armRenameListByOperation` from `ArmResourceListByParent` operation template
3. [optional] find another way to guide service on the List operation name

### Reproduction

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXLfN2MtY2xpZW50LWdlbmVyYXRvcshtCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVW6QDfyBtBxHkuQ29yZc4SUucArU3mAKzPL%2BUAmUfoAJjHPwpAdXNlRGVwZW5kZW5jeShNaWNyb3NvZnQuQ29udG9zb1Byb3ZpZGVySHVi6ACKcy5gMjAyMS0xMC0wMS1wcmV2aWV3YCkKbmFtZXNwYWNlIMZsIHsKICBAb3DEcWlvbkdyb3VwCiAgaW50ZXJmyidPzSHFNSAgQGZyaWVuZGx5TmFtZSgibGlzdENoaWxk6ADjcyIpxSjSGSBpcyD9AMbOLy7EQjsK2HVBbm90aGVy2XzVIP8Ag2Iu1TbnAIogIH0KfQoKLyoqIMc6IMgjIMhEIOYCjm3kAWVBUEkuICovCkBhcm3IIOQAwOUBigpAc2VydmljZSjkAVd0aXRsZTogIvIAkuYBiiIsCn0pCkDnA1BlZCjoAfHsAdz8ANnlAb3sALpBUEkgx09z5AClICBlbnVtIMhYxTDGMvICUsg5xjggIO8CqvUC8%2BoCo3YxXzBfUMZKXzHmAbHkASNDb21tb27kA11zxyzXSsspy1Y1xkr0AwEs5QG75wEBQegBA%2BwBHugETeYA0m1vZGVsIEVtcGxveWVl5AI0VHJhY2tl6QISPMgcUHLkA0V0aWVzPucBMi4u6QCw5AHsUGFyYW1ldGVyyTM%2B5gJJ5wCOyWVwyUr0AITKaOsBmUFnZSBvZiBlyEPFOCAgYWdlPzrkA8wzMucDPsQtVGhlIHN0YXR1c8Q0dGhlIGxhc3Qg6QQE5QKqxC1AdmlzaWJpbGl0eSgicmVhZOcDVHDkAS%2FnBO9TdGF0xGX2AaDIEOUBYcwy6QD6QHBhcmVudMgpKOgA58Rq5gD57QOB5AGCUHJveHnIETx7fegBcEBrZXkoImPEL%2BcAqUBzZWfkA4DOFuQDJzogc3Ry5QWu%2FwCI6gCI9AQQ%2FwCPeSgiYcQ25AZi9QCX1B71AJ%2FqBZDpBYpzIGV4dGVuZHP3AXzLKXvFROQDWsglyh3NXegA9ugCXGdldOQA40HKOVJlYWTuAsEgIGNyZWF0ZU9yVXBkYXTlARTLMUPHHVJlcGxhY2VBc3luY9BBddQ5UGF0Y2hTzC4s8wMFx0JkZWxl0UJExRVXaXRob3V0T2vVe%2BQF0ELpAb%2FmBt7ORkzFIlDlAh%2FWPlN1YnNjcmlw5AFQxz3GNcwZzjv%2FAZHqB37uBrTmAZbEdvwApc0132%2FOb%2FYHKt92x3bUPMd9fQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weidongxu-microsoft** [comment]
@allenjzhang 

Let me know if we follow this breakdown. And if I can help you to do #1 on the renames on existing operation.

**Comment by markcowl** [comment]
This should be fixed in the July release
