### ISSUE TITLE
[tcgc] add `overrideClientMethod` decorator

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#1054]
### Clear and concise description of the problem

We want the ability in `client.tsp` to override a generated client method. When we switch to `...` always meaning spread, we will also need the ability to generate options bags for languages that prefer options bags. Adding a decorator like `overrideClientMethod` will allow authors to clearly state their preferred signature for specific language(s). This will also allow patched customizations without having to craft an entire client to modify one operation

```tsp
// main.tsp
namespace MyService;

model Params = {
  foo: string;
  bar: string;
}

op myOperation(...Params): void;

// client.tsp
namespace MyCustomizations;

op myOperationCustomization(@bodyRoot params: Params): void;

@@overrideClientMethod(MyService.myOperation, MyCustomizations.myOperationCustomization);
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by weidongxu-microsoft** [comment]
link a design discussion for options bag https://github.com/Azure/typespec-azure/issues/831
currently the mapping of model properties could be a challenge.

**Comment by iscai-msft** [comment]
Yeah that's a good idea, this way we more clearly map things from the service to the client
