### ISSUE TITLE
Original name of a type (model or scalar) needs to be tracked in TCGC

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1059]
Now, we only keep the "library name" of a type as the `name` field in the TCGC's result.
But we might need to keep the original name (we could call it `tspName` in parallel of `tspNamespace` which should be intuitive).

Imagine this scenario:
we have a type in azure.core template, such as:
```typespec
namespace Azure.Core;
model ResponseError {}
```

And when it is used in an RP's spec, a decorator could be added to it via client.tsp:
```typespec
@@clientName(Azure.Core.ResponseError, "NewError", "csharp");
```

Now the model returned in TCGC for this ResponseError will be:
```
{
	kind: "model",
	name: "NewError",
	tspNamespace: "Azure.Core"
}
```

The generator now only knows that this model is defined in Azure.Core namespace, but it loses track of which model this is because of the name change.

Therefore we might need another field to track its original name for all types.

**Comment by iscai-msft** [comment]
Fixed in your PR
