### ISSUE TITLE
Service using mix API versions conversion question

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#106]
e.g.: https://github.com/Azure/azure-rest-api-specs/blob/0077b4a8c5071d3ab33fd9f9ba013581c9a66b8f/specification/alertsmanagement/resource-manager/readme.md
For namespace versioning info, I could add multiple versions, but these versions are not work for all APIs. How could I set the mapping as well as different default API version for different resource's APIs?

**Comment by tadelesh** [comment]
Actually lots of ring0 RPs for ARM are using tags containing multiple API version. They always have different API versions for different resource types and different resource types are maintained by different teams. We used to attempt to let them consolidate the version, but the final answer is it is a valid usage for Azure service. My concern is not all API versions defined in `@versioned` are supported for all the operations, do we have the ability to map them?

**Comment by markcowl** [comment]
@tadelesh That is exactly the point, but this behavior in which an api-version is GA and not available in the next stable API version is no longer suggested by ARM.

The TypeSpec for such a spec would proceed something like this:

Version 1: Resource A, B
Version 2: Resource C, D

Resource A and B would be added in version 1 and removed in version 2
Resource C and D would be added in version 2.

The typespec would have lots of changes, but it is possible to model. Clients could add decoration as needed to specify that both Version1 and Version2 are included in the API.

Alternately, we could decide to allow multiple specs that are combined into a single, logical API package.

The workgroup pattern defined here: https://github.com/Azure/typespec-azure-pr/issues/3576  would make it easier to represent the actually recommended version of this.

It's unclear to me how important it is to convert these very complex older specs that are using a versioning mechanism that is no longer considered best practice.

**Comment by markcowl** [comment]
Per the consensus from our discussion and Jeffrey, we should not process these specs until all resources are included in each api-version
