### ISSUE TITLE
feat(tcgc): provide origin of `SdkClientType`

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1060]
### Clear and concise description of the problem

An `SdkClientType` can derive from either a namespce or an operation group. Some languages (like csharp) have different processing logic for those two kinds. We need TCGC to provide that metadata somewhere from `SdkClientType`.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
Can you explain this more clearly @archerzz? Are you tryign to determine whether a client is a top-level client? I'm not sure what you mean if a client is derived from an "operation group"

**Comment by archerzz** [comment]
> Can you explain this more clearly @archerzz? Are you tryign to determine whether a client is a top-level client? I'm not sure what you mean if a client is derived from an "operation group"

@iscai-msft sort of. Here is an example. In `autorest.csharp`, we have a test case which defines a sub namespace: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/UnbrandedProjects/Platform-OpenAI-TypeSpec/audio/operations.tsp#L11
```typescript
namespace OpenAI;
@route("/audio")
namespace Audio {
```

And in typespec, it's parsed as an `SdkOperatoinGroup` (I'm not clear of the magic here, but it happens).
![image](https://github.com/Azure/typespec-azure/assets/4516/7d6b600a-5872-4abd-ab84-9318dd80fdec)

So, I think we should have similar info in TCGC.

**Comment by haolingdong-msft** [comment]
For Java, we will also need the `groupPath` info to build the operation group's name.

**Comment by tadelesh** [comment]
final solution: provide parent info in `SdkClientType` and emitter could use the hierarchal client's name to know the path
