### ISSUE TITLE
Referencing to a type in resource manager library should not generate new type in swagger

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#1061]
In the [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn0KCm1vZGVsIEHoANEKICAgKiBJbmRpY2F0ZXMgaWYgdGhlIOgCWiDkAUsgaXMgYXZhaWxhYmxlLsUy5ADrxBtByBc%2FOiBib29sZWFuOwrMWlTFTWFzb24gd2h5xVxnaXZlbslZbm901F3GND869gJz7QD6Q2hlY2vkAkXnAI1pbGl0eVLFQO4AjERldGFpbGVk%2FgCR8wCNbWVzc2Fn5ADkc3Ry5QMhfQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D), we take `CheckNameAvailabilityReason` as example, which comes from `Azure.ResourceManager.CommonTypes`. 
```
reason?: Azure.ResourceManager.CommonTypes.CheckNameAvailabilityReason;
```
It is generated as type `Azure.ResourceManager.CommonTypes.CheckNameAvailabilityReason` in swagger as showed in that playground. 

For .net, for this generated swagger we will generate model with name `AzureResourceManagerCommonTypesCheckNameAvailabilityReason`, which is expected to be `CheckNameAvailabilityReason`. 

So I'm thinking the expected swagger model might be a reference to common type like:
```
"reason": {
    "$ref": "../../../../../common-types/resource-management/v5/types.json#/definitions/CheckNameAvailabilityReason"
    "description": "The reason why the given name is not available."
  },
```

Same to other types.

**Comment by allenjzhang** [comment]
Dup of #995 , scheduled for next sprint

**Comment by allenjzhang** [comment]
#995
