### ISSUE TITLE
[TCGC] LRO, add polling info to the `SdkLroServiceMethod` and `SdkLroPagingServiceMethod`

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#1062]
`typespec-azure-core`'s `LroMetaData` contains [`pollingInfo`](https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-core/src/lro-helpers.ts#L277). Currently Java emitter will use the `pollingInfo.responseModel` to get polling type and calculate which polling strategy to use. More details can be found in Java emitter's [logic](https://github.com/Azure/autorest.java/blob/main/typespec-extension/src/code-model-builder.ts#L882-L906).

I guess other languages also needs polling info. So it's better to have TCGC to add polling info instead of using raw LroMetaData. For now, Java emitter only needs polling response type.
Not sure what polling info other language needs, language owners, please feel free to use this issue to add your requirements.

**Comment by iscai-msft** [comment]
closing in favor of #1236
