### ISSUE TITLE
[Feature] filter out the emitted decorators by `scope`

### ISSUE THREAD

**Issue by chunyu3** [Azure/typespec-azure#1083]
TCGC will emit the decorators in SDKXXType as `.decorators`.
Can TCGC filter out the decorators by `scope`, such as only emit decorators with scope `csharp` for `typepsec-csharp` emit?

Current we can do this filtering for decorators from `typespec-azure` library because `scope` in `typespec-azure` library has settled meaning.

**Comment by iscai-msft** [comment]
closing in favor of https://github.com/Azure/typespec-azure/issues/1295
