### ISSUE TITLE
[ARM]: Extend linting rule of arm-resource-key-invalid-chars to report invalid words

### ISSUE THREAD

**Issue by raych1** [Azure/typespec-azure#1085]
### Clear and concise description of the problem

**Context**
Currently for any invalid words defined as model/parameter names in the typespec/swagger, we need to add suppressions in two places:
- `custom-words.txt` in the spec repo.
-  `cspell.json` in the `azure-sdk-for-net` repo. 

We propose extending the current lint rule `arm-resource-key-invalid-chars` or adding a new lint rule to validate these words. This would allow the suppression in typespec to be carried over and consumed by the downstream SDK emitters. With this, we can avoid the need for multiple suppressions for the same word.

**Example**
Looking at the following oracle typespec, where the key is defined as `adbscharsetname`, an invalid word:
```typescript
model AutonomousDatabaseCharacterSet
  is ProxyResource<AutonomousDatabaseCharacterSetProperties> {
  @doc("AutonomousDatabaseCharacterSet name")
  @key("adbscharsetname")
  @path
  @segment("autonomousDatabaseCharacterSets")
  @pattern(".*")
  name: string;
}
```
Currently, the suppression must be added to both the spec repo at [custom-words.txt](https://github.com/Azure/azure-rest-api-specs/blob/1c63635d66ae38cff18045ab416a6572d3e15f6e/custom-words.txt#L4025) and the `azure-sdk-for-net` repo at [cspell.json](https://github.com/Azure/azure-sdk-for-net/blob/bf93099012a7e4e8cffce6233822db068a0a4318/.vscode/cspell.json#L870)

With this feature, we can keep the consistency across repositories.

//CC: @ArthurMa1978 

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by raych1** [comment]
@allenjzhang @markcowl  
do you think if the lint rule can be improved to cover this check?

**Comment by allenjzhang** [comment]
This is a bigger question around EngSys to ensure consistency between various SDK team owned repos. I am all for consistency though I suspect that they would be overlapping, or at best cases, rest-api spec repo being the common subset for each language repos. 

@mikeharder, @weshaggard, your thoughts on this?

**Comment by mikeharder** [comment]
@raych1: In azure-rest-api-specs repo, please use file `cSpell.json` instead of `custom-words.txt` going forward.
