### ISSUE TITLE
[ARM] Non-resource based action templates

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#1086]
### Clear and concise description of the problem

I have seen a few non-resource based actions (both GET and POST) that folks trying to fit the resource based operation template thru. While it is even simpler to [model it ](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn0KCm1vZGVsIFF1b3Rh5QDV5AEsOiBzdHLlAfkgIG90aGVyyhF9CuUBrMh6T3BlcmF0xGgKaW50ZXJm5AFlU3Vic2NyaXDEGFVzYWdl5gEvQGFjxBLFCu4B7lZhbHVlxBhnZXQKICB1xTQoCiAgICAuLi7MT0lkUGFyYW1ldGVyLMgg9gEMRm91bmTmAJsuRGVmYXVsdMxz5QIPyUNMb2PFK9NdcGnnAUrNHCk6IEHlAQZwb25zZTxQYWdlPOUBRD4%2BIHwgRXJyb3LIHeQBNA%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D)directly, I think offering op template would make it even cleaner and easier to use.

```
  @action
  @armProviderNameValue
  @get
  op ArmActionSync<
    Request extends TypeSpec.Reflection.Model | void,
    Response extends TypeSpec.Reflection.Model | void,
    BaseParameter = SubscriptionIdParameter,
    Parameters extends {} = {},
    Error extends {} = ErrorResponse
  > (
    ...BaseParameter,
    ...Azure.ResourceManager.Foundations.DefaultProviderNamespace,
    ...ApiVersionParameter,
    ...Parameters,

    @bodyRoot
    body: Request,
  ): Response | ErrorResponse;
```

```
  usages is ArmActionSync<void, Page<Quota>>;

  usages is ArmActionSync<void, Page<Quota>, BaseParameter = SubscriptionIdParameter & LocationParameter >;

```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
losing in favor of existing issue for action template here: https://github.com/Azure/typespec-azure/issues/470
