### ISSUE TITLE
[TCGC]: Unify case of header names

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1098]
### Clear and concise description of the problem

**Minor.**

In some cases, the name of content type header as parameter is `content-type`. In other cases, it's `Content-Type`. See https://github.com/Azure/autorest.csharp/blob/72659d42a5067035f0c2d969ed07dd523cbda4dc/test/TestProjects/FirstTest-TypeSpec/FirstTest-TypeSpec.tsp#L286
```typescript
@header contentType: "text/plain",
```

The header name is `content-type` v.s. `Content-Type`.
![image](https://github.com/Azure/typespec-azure/assets/4516/a8b88eb6-ae96-4719-af34-58a3650a02e3)

This is not a big issue, because according to HTTP spec, the header name is case-insensitive.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
In our sync we determined not to do anythign special here, so closing. Please reopen if there are more questions
