### ISSUE TITLE
[Bug]: SdkFloatKindsEnum contains decimal types

### ISSUE THREAD

**Issue by antkmsft** [Azure/typespec-azure#1106]
### Describe the bug

Decimal types are Fixed Points, not Floating Points, therefore they shouldn't be in `SdkFloatKindsEnum ` - either name the enum "`SdkFractionalKindsEnum`", or split it into "`SdkFloatingPointKindsEnum`" and "`SdkFixedPointKindsEnum`" (or do both - `SdkFractionalKindsEnum = SdkFloatingPointKindsEnum | SdkFixedPointKindsEnum`).

### Reproduction

See https://github.com/Azure/typespec-azure/blob/54567f763257300e64603091659d282072631d2a/packages/typespec-client-generator-core/src/interfaces.ts#L137-L143

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArcturusZhang** [comment]
Resolved by https://github.com/Azure/typespec-azure/pull/1015
