### ISSUE TITLE
[TCGC] - use original model for simple spread instead of creating a new anonymous model

### ISSUE THREAD

**Issue by joheredi** [Azure/typespec-azure#1132]
### Clear and concise description of the problem

There are scenarios where tracking the source model of anonymous models is beneficial. For instance, in TypeScript code generation, this feature would enable us to map serializer/deserializer types between RLC (Rest Level Client) and Modular. This functionality is crucial for bridging gaps between RLC and Modular types.

Example
Consider the following TypeSpec model:

```ts
model Foo {
   bar: {
      baz: string;
   }
} 
```

With the ability to track the source model, we could implement the following TypeScript code:

```ts
declare function deserializeFooBar(input: FooRest["bar"]): BarModel;
```

Here, BarModel is generated from TCGC, but there is no equivalent interface in RLC as it doesn't generate anonymous models.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
could you clarify the source meaning? for example, if anonymous model is in parameter, what should the source model be? other cases are model property, return type, etc.

**Comment by iscai-msft** [comment]
@ArcturusZhang has the following comment:

For this typespec:
```typespec
model Bar {}
model Baz {}
op foo(...Bar): Baz;
```
the TCGC result gives us a `FooRequest` as the model of body parameter. Since it is speading model `Bar`, could we get back the model `Bar` as the body parameter in this case?
This help us reduce the size of the generated assembly.

We agree that there are cases that returning the original model is not possible, such as an operation with spread of two different models, in those cases, we could still do the `FooRequest` as body because it is combining the two models.
But we would like to get the model back if the model is there.

**Comment by tadelesh** [comment]
> @ArcturusZhang has the following comment:
> 
> For this typespec:
> 
> ```
> model Bar {}
> model Baz {}
> op foo(...Bar): Baz;
> ```
> 
> the TCGC result gives us a `FooRequest` as the model of body parameter. Since it is speading model `Bar`, could we get back the model `Bar` as the body parameter in this case? This help us reduce the size of the generated assembly.
> 
> We agree that there are cases that returning the original model is not possible, such as an operation with spread of two different models, in those cases, we could still do the `FooRequest` as body because it is combining the two models. But we would like to get the model back if the model is there.

@joheredi could you confirm if it is enough for js?

**Comment by joheredi** [comment]
Yes I think this would be good enough
