### ISSUE TITLE
body optionality in spread

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1149]
### Clear and concise description of the problem

In the below typespec, we will not be able to get a valid bodyParameter or body.property from http operation. And currently tcgc is set the body.optional as false if it's undefined, which means the body would be required. And in RLC implementation, we set optional default as true.
```
  createStreaming(
    ...StreamingChatCompletionOptions<TState, TContext>,
  ): ChatCompletionChunk<TState, TContext>;
```

I wonder if we can get some common sense here about what should be the expected behavior here? 

Should we set body optionality as true in the spread case if there's any properties inside the spread model that are required? 
```
model Foo {
   prop: string;
   prop1?: string;
}
op test(...Foo): void
```
In this case, RLC will not flatten the Foo, but we will get a body that is optional, but it seems a little strange to have required properties in optional body.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
Body can only be optional when using a body property with `@body` or `@bodyRoot`, implicit body will always be required
See this https://github.com/microsoft/typespec/issues/1907
