### ISSUE TITLE
[Bug][TCGC]: empty name when certain models are used as spread body

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1150]
### Describe the bug

Some models won't get a name when they are used as spread body.

Here is an example.
- `CreateChatCompletionRequest` is the model: https://github.com/Azure/autorest.csharp/blob/a37076386944d9230b94d60e13e6362089801cef/test/UnbrandedProjects/Platform-OpenAI-TypeSpec/completions/models.tsp#L144-L174
  - It has a property `model` which is a union of a string and an alias `CHAT_COMPLETION_MODELS`.
- `CreateChatCompletionRequest` is used as a spread boy in `create` operation: https://github.com/Azure/autorest.csharp/blob/a37076386944d9230b94d60e13e6362089801cef/test/UnbrandedProjects/Platform-OpenAI-TypeSpec/completions/operations.tsp#L20-L22

TCGC fails to give a name to `CreateChatCompletionRequest`:
![image](https://github.com/Azure/typespec-azure/assets/4516/edec2608-d64c-4d9e-86e1-71c3c0ee1786)

### Reproduction

Try to parse the definition in the link above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
the root cause is from `findContextPath` does not handle nested operation group: https://github.com/Azure/typespec-azure/blob/b38b4cae08cbe6fd8b0a2bbe3fdef88232bf573a/packages/typespec-client-generator-core/src/public-utils.ts#L334.
