### ISSUE TITLE
Adding missing common types in TypeSpec

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#1160]
- [ ] managedidentitywithdelegation.json
- [ ] mobo.json
- [ ] networksecurityperimeter.json

**Comment by allenjzhang** [comment]
Should be done asap in the upcoming sprint.

**Comment by timotheeguerin** [comment]
We have issues for the first two already, do you want to combine into this one?

Mobo issue https://github.com/Azure/typespec-azure/issues/249
managedidentitywithdelegation  issue https://github.com/Azure/typespec-azure/issues/944

**Comment by markcowl** [comment]
est: 3
