### ISSUE TITLE
[TCGC][Bug] client's name in `sdkpackage` is not overwritten by decorator `@clientName`

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#1164]
## Issue description
For this cadl-ranch case: https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/client/naming/main.tsp

TSP: 
```ts
@route("/model")
@operationGroup
@clientName("ClientModel")
namespace Model {
  @clientName("CSModel", "csharp")
  @clientName("GoModel", "go")
  @clientName("JavaModel", "java")
  @clientName("TSModel", "javascript")
  @clientName("PythonModel", "python")
  model ModelWithLanguageClientName {
    @doc("Pass in true")
    defaultName: boolean;
  }

}
````

TCGC response:
This `Model` operation group's name should be `ClientModelClient` as it uses `@clientName("ClientModel")`, but TCGC's response of `sdkPackage` returns the client name as `ModelClient`.

![image](https://github.com/user-attachments/assets/f9a624b6-dc55-4e77-a811-d114d69e379d)

## Expected behavior
It should consider `@clientName()` decorator and overwrite the client name using the value provided in the decorator.

**Comment by iscai-msft** [comment]
@haolingdong-msft im confused by this issue. The client name decorator is being applied to a namespace, which I don’t think we have support yet for, but it seems like you want a response to be renamed? Can you elaborate? Thank you!

**Comment by haolingdong-msft** [comment]
Hi @iscai-msft, I'm also confused on the expected behavior for `@clientName` decorator on `namespace`, so I talked with @tadelesh yesterday, and asked for expected client name for this client. And @tadelesh told me the name should be `ClientModelClient`, that's why I create this issue. I'm fine if the `@clientName` decorator on `namespace` will not be applied, but I would like to know the rules on when the decorator will be applied to client name and when it will not be applied.

**Comment by tadelesh** [comment]
i think we should honor `@clientName` for namespace/interface renaming. it's one of the customization way for renaming client. see doc: https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/02client#renaming-the-single-client.

**Comment by iscai-msft** [comment]
yes you're right, that is fair if we think of renaming namespaces and interfaces are really renaming the client. Ok let me go ahead and fix this, thanks for the discussion @haolingdong-msft and @tadelesh
