### ISSUE TITLE
Enable Sample generated for TypeSpec to have real values from TypeSpec/Swagger examples

### ISSUE THREAD

**Issue by lirenhe** [Azure/typespec-azure#118]
When we generate SDK from Swagger for mgmt. SDK, we will leverage test modeler to connect the real values from swagger examples with the model definition in Modeler4 so that we could leverage those real values to generate SDK samples for all languages.

Those samples will be used in API ref docs to show how to use the SDK.
Please check the Example part in https://learn.microsoft.com/en-us/rest/api/avs/addons/delete?view=rest-avs-2023-03-01&tabs=HTTP

With our goal to generate SDK from TypeSpec directly, the existing approach to leverage testModeler will be broken and we need to enable Sample generated for TypeSpec to have real values from TypeSpec/Swagger examples, otherwise, this will be a feature gap when moving services from Swagger to TypeSpec.

This effort would be applied to both MPG and DPG and I hope the test/SDK docs generation could also leverage the real value of the payload.

**Comment by markcowl** [comment]
I think this may be the time to rethink whether we want machine-generated examples for the purpose of documentation. If not, any generator that wants them can use the pattern employed by typespec-autorest, matching the examples by OperationId.

**Comment by markcowl** [comment]
@markcowl: add to dpg discussion

**Comment by lirenhe** [comment]
@markcowl, I think this effort is mainly about DPG and TCGC work and we don't have specific ask for TypeSpec to support this.
As the SDKs are generated from TypeSpec directly, there is no need to create sample through  TypeSpec => Swagger => SDK => SDK samples to avoid any mismatch between SDK signatures.
As you added the label of 'More Info', could you share what information needed for this task?  Thanks

**Comment by markcowl** [comment]
closing as not planned
