### ISSUE TITLE
[Bug]: getLroMetadata returning inconsistent logicalResult information

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/typespec-azure#1180]
### Describe the bug

Health Insights defined the following LRO: https://github.com/Azure/azure-rest-api-specs/blob/2b21f072c61f87958e7866cf532c3f2169454106/specification/ai/HealthInsights/HealthInsights.RadiologyInsights/route.radiologyinsights.tsp#L25

Currently getLroMetadata returns:
![image](https://github.com/user-attachments/assets/14453483-e138-44a9-ae6d-87c1beb12cac)

The current behavior is returning inconsistent logicalPath and logicalResult information since RadiologyInsightsJob is the parent envelope and RadiologyInsightsInferenceResult is the correct type of the logicalResult. Leading to issues downstream when generating client libraries.

I would expect getLroMetadata to return:
```
logicalPath: 'result'.
logicalResult: {
   name: RadiologyInsightsInferenceResult,
   // other fields
}
```

### Reproduction

Use Health Insights spec linked above

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weidongxu-microsoft** [comment]
link https://github.com/Azure/typespec-azure/issues/787

**Comment by markcowl** [comment]
This operation uses the new PUT pattern as specified [in this issue](https://github.com/Azure/typespec-azure/issues/787)

This bug is about ensuring that 'finalResultPath' is consistent, even when the returned model has a field marked with lroResult

**Comment by markcowl** [comment]
[sample of non-resource PUT](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHVzZUF1dGgoCiAgQXBpS2V5xA48xgtMb2NhdGlvbi5oZWFkZXIsICJhcGkta2V5Ij4gfCBPxCoyxS9bCiAgICB7xQYgIOQA3DrHH0Zsb3fkAKUuaW1wbGljaXQsxyVhdXRob3JpesVhVXJsOiAi5AFoczovL2xvZ2luLmNvbnRvc28uY29tL2NvbW1vbi9vxDUyL3YyLjAvyEBlIshSc2NvcGVzOiBbyUl3aWRnZXTNSi5kZWZhdWx0Il3GN30KICBdPgopCkBzZXJ2aWNlKOQAxnRpdGxlOiAiQ8Y6IFfFSSBNYW5hZ2VyIiwKfccxZXLkATkie2VuZHBvaW50fcd05QCV0D9BUElzxRnEYyAgLyoqIApTdXDkAh5lZMglU%2BYAh3MgyFNzIChwcm90b2NvbCBhbmQgaG9zdG5hbWUsIGZvciBleGFtcGxlOgrpAPRlc3R1cy5hcGku8gD%2FKS4KICovxX7IXzogc3RyaW5n5ACYfeQBCOcCvGVkKOcAvy7mAJrnAP3oAmpzKQrkAIZzcGFjZSDVKjsKCuQA41RoySDvAUgg5wFzIMdzLuQAnGVudW0gyGTlASrERccRIDIwMjItMDgtMzHELCAg5AK%2FRGVwZW5kZW5jeSjrAuLIQy52MV8wX1ByZXZpZXdfMikKICBgyUYwYCwKfQoKLy8gTW9kZWxzIC%2FTAeoAx2NvbG9yIG9mIGEg5wFc5ACGdW7kAJrmANtDxSLkALboAVbnAMFCbGFja8clIMYm5QDBxRg6ICLFCCLJL1doaXRl0y%2FFGDogIsUIyi9S6gJAyy1SZWQ6ICJSZWTKKUdyZWXoAKzMK8UYOiAixQjKL0JsdfQAhsQX5QC0deQAhOQBQSoqIEHsARRAcmVzb3VyY2UoIsYWcyIpCm3kAWTIT%2BgB2uQBWMYjIOQCUMU%2BICBAa2V5yDtOYW1lIuQBuEB2aXNpYmlsaXR5KCJyZWFkxRbENugCxTvoALnLVuUBtcdXxQw67AGszTJJROQB3XTJPCdzIG1hbnVmYWN0dXJlyEXME0lkzXsuLi5FdGFnUHJvcGVydHk76AEcxF1yZXBhaXIgc3RhdGXxAkRAbHJvU3RhdHVz7QJPUsU0xBll9AJVxiXHWnMgc3VjY2VlZGVkxVMgIFPIEDogIskM6wJkzj5mYWlsyTtGxQ06ICLGCdk1d2VyZSBjYW5jZco8Q8cP5AVAxwvRQHdhcyBzZW50IHRv5QFw8wFnU2VudFRvTcsZ5ADH0RXsAoFzdWJtaXTkBU3nAW1yZXF1ZXN05QUq7QFw7AKL5gFlUscr7AKY6QGs6gITz1rFTSDIDuUBqegCX%2BsBvO0CZWTEVOQFyXRpbWUgd2hlbsVfx1hpcyBzY2hlZHVsZWTkAR1vY2N16AESyRlEYXRlVGnkAvd1dGPIDd9lx2XmAOXkAX9jcmVhdOkBtccO31rfWsdadXDEJchaxw7fWt9ax1pjb%2BQG7cpcyRDXXusDf3BhcmFtZXRl5ALq6wIO5QHkdXPJZvUCHOYDmlDEQuoGk%2FQEMSBiZeQJaeYBzOkApkBwYXRoCiDHJOwEM%2B8FOydz5ACn8QVCxBTkBUBAcGFyZW50UsgZ5gCj7gVYUGFy7gLE5AUf6AClyV3uBWHENP8FZfkFZUlE5AKmdXNl5QFWcmVvcmRlxCXQcMQL7wUt8gFFxCX%2FBXT%2FBXTvBXRkZXRhaWxzxGBh6ACd7wQV6gE38QQZxBVSxjXwBB5JZGVudGlmaWVzIHdobyBzaWduZWQgb2bmAMjPaugDv8UlT2ZmQnnuAgIvIEFu6AnJ5gCr5AuvbGV0b24g6AIG5QDTUHJvdmlkZXMgYW5hbHl0aWNzIGFib3V0xXXkAYTkAz5tYWludGVu5AV6xk3mAM3wAlXJQ%2F8CWegBDUHJc%2BwCXmnoAQhy5QFP5ACIyVkgb2JqZWN0LiDEKnJl5ATbb25seSBvbuYClmQgJ2N1csR5J%2B0ClclBSeYCfPYCkmnkBmDHQOQNOusC8nVtYmXlCad1c2XlAfzqA6HHaXVzZUNvdeQK%2FWludDY01z%2FkBIhzyz3lBIPvA9zGD85N6QPW7AK2xFHGR3PwAYvMJ%2BoJKOwG5e0BdMwvJ3MgdW5pcXXkA0btAUXMJf8BSPUDlc9l6wmb%2BQQLzzNmdWxsIGFkZHJlc%2BYA8iDIDv8Dv%2BUDEk9wZXLlDhv4C5RhbGlhc%2BgNLuYOzyA9IOcNT3NSZXBlYXRhYmxl5wO6cyAm5QkSxh9Db25kacReYWzWIGxp5QMQxRtJZDvIb%2BsAlj3sD0%2FoAzrKIDztAJo%2BOwoK5AOWcmbkDS7mA1HnA0nrAOsg5woC5wurxCPnBp7rA8gg5AEoxS%2FoAfBzaGFyZWRSb3V0ZQogIGdldMYpyVfGVuQDf8kTcy5H5Abc7wC1xik8xj8%2BO%2F8AiGRl5Ad6%2FwCP6gCPRMUv%2FwCV%2BgCV5Q60xkrmD7luZXZlcgogIOQBW%2BUBR8Ydy0%2FnAMBD5QjacyBvcucIi3PqAMRhc3luY2hyb25vdXNseegHrm9sbGluZ8lJ5wUPcy74AVvkA0fmCUBPclXFY8df7gDeTG9uZ1J1buQRpOgA5uYAnMg26gF66gF76gCs5QCd6QCDz1zIUVJlYWTRR%2BYBe%2FgA9ukIpf8A9%2FcBw%2BQA%2FeYCC%2F8A9ekA9cZH8QCmTGlzdOoMX8Yrc%2BYAnGxpc%2BcAg%2FACMshUxD3yAiTEFlF1ZXJ55Qm75Qn95QOQPFN0YW5kYXJk0yEgJiBTZWxlY88YPvMCa%2BkHE%2FMBr8kc6QG4yhL%2FAbvLK8dy%2FgLGz2vGH99u9gJ60HjpAOrmCwfyA1zkAPLkByDyBB%2FtDVXnAmMjc3VwcOQGAf8VDG9yZS91c2Utc%2BcBpi3pBGRzIiAiVGhp5QDVYSBjdXN0b23qBILoAIfoEtsuIuQC2HLkBIooIucTmXMve8YJSWR9L%2BcOxi97yUNJZH3lBxbvC%2FvEcEZvdW5k6gSp%2BwShzDrmDDXmAo%2FzARrqAlYqKiBT5w3g6gyd5gtUxDDoB0P%2FA6f3BJ7oDjrGfPACFPMDpEFjxBvyA1LzAMPZGSAmIMcKSWRSZXNwb25zZUjlFknmAPZ98gcU5Aty6gph9wZ6xCXxBnfpAP7EHv8GZv8G%2B8VD8gN6zX%2FrDzTLFvwDa1dpdGjnCBTnC8dk5A101XPsBEnKb%2B0A49ds6wRFzlPvBgTKVuwFvNtZ7QW1zlvrBbnFQfkFvcQe%2FQXB1F7nDYEgYWxs5Q4g5g%2B%2F8QvS%2BAMYxXTqAxzzAh7kAyDnDbH0AKH0B7ZvbOQGIWlvbvIDJ8RD7AMS8g5E8Qi%2F7QMI7Av2%2BwMKzCf0AwzMIP8DDvoDDsxF9QaKcmVwbGHkAenvAJHrAx7NGP4Gi1LGTtd35gMU0mfvAO3XZOUDGNZZ6QMazUf%2FCSTHYSjMNOUCZ%2FsBeeoJKvsAsfoJMPYAvuUDfc1Q8wN%2FzCD9A4HPZOcQnSAiZ2xvYmFsIiBSUEPqAm7lDuXmBdlkcyB3aXRo6AKjaW5mb3JtxSXrEKFvdmVy5APG5xn25w8G5geexxTkB%2FN0deQPBG9wyCjqArZScGPpALnkA3R7feobTcY5U%2BUOWOoOYCAgxSPtDYwK5AE96RnS5hT3IGpvYuoR%2FkpvYukDesQZaWTuE8jkD2L9D1B1dWnkDjTKQuUThfMPPucQKugSknRv5wCRIGHuAJJTdGFydEpvYvASh%2BQGQugQ4ccx0GPHKuQA1Gluc3RydeUEs%2BcCHcwSyDNbXeUAmMZ5Sm9i9gkC8AQsSm9i5AFY%2Fwnj%2FwnjxVsiICJOb24t6ALH6gJwIukCLi9qb2JzL3tp5Qmtb3DkBAT5AKn2CavkH0TpAvsuS2V5c09m5QDE5AIvSm9i5QIl5g%2F0Sm9iTHJv6AjBID3lAX1A5h8SKCLJXC3oHy0iKeoAs8gUOiB1cmzkAo8uLi7%2FAUbkA3fnAqHlAfbqAgv%2FAVz%2FAVz%2FAVwK8gTc7AFWKeoBfHPnAowv5RQ5dXTlA6vHFEHkBTbkHxLvAOhBcGnnHZDpDVHpGhJib2ToD3rFC1868ALvLAopOiAo5gYn6QpKICbvAZopIHwgKE9ryiDmAcrPIuwAlkVycm9yyB07Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fdata-plane%22%5D%7D%2C%22options%22%3A%7B%22%40azure-tools%2Ftypespec-autorest%22%3A%7B%22emit-lro-options%22%3A%22all%22%7D%7D%7D)

**Comment by markcowl** [comment]
**Describe the breaking change**
Update the lro data returned from PUT operations to account for non-resource PUT

**Back-compat design to avoid immediate breaking**
Existing specs are updated to prevent changes in data


**Impact**
This change affecting:

- [x] ARM
- [x] Data-plane
- [ ] Existing specs:~11
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
September
