### ISSUE TITLE
Could we get the source model as the body parameter from TCGC when a model is spread as parameters?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1183]
For this typespec:
```typespec
model Bar {}
model Baz {}
op foo(...Bar): Baz;
```
the TCGC result gives us a `FooRequest` as the model of body parameter. Since it is speading model `Bar`, could we get back the model `Bar` as the body parameter in this case?
This help us reduce the size of the generated assembly.

We agree that there are cases that returning the original model is not possible, such as an operation with spread of two different models, in those cases, we could still do the `FooRequest` as body because it is combining the two models.
But we would like to get the model back if the model is there.

**Comment by iscai-msft** [comment]
closing in favor of https://github.com/Azure/typespec-azure/issues/1132

Will copy paste your comment into the issue
