### ISSUE TITLE
Add a linter rule to discourage using @useRef decorator

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#1195]
In typespec service team could use `@useRef` to generate new swagger similar to their old swagger(if in that swagger they have some references). 

Here is an example from Azure Fleet, if we try to generate SDK from typespec directly we will get an empty model for `ApiError` the referenced swagger definition would only work for OpenAPI emitter. In that case we should report this out to ask service team to migrate referenced swagger to typespec also. 

Once the service team finish their migration there is no need to refer any swagger definition. So it's better to have a linter rule to warn the usage for `@useRef` out.

[tsp definition](https://github.com/Azure/azure-rest-api-specs/blob/db2f049580ad55549ce9a34635ab58bc5a27c814/specification/azurefleet/AzureFleet.Management/common.tsp#L18-L19)
```
@doc("ApiError for Fleet")
@useRef("../../../../../compute/resource-manager/Microsoft.Compute/common-types/v1/common.json#/definitions/ApiError")
model ApiError {}
```
[generated swagger](https://github.com/Azure/azure-rest-api-specs/blob/db2f049580ad55549ce9a34635ab58bc5a27c814/specification/azurefleet/resource-manager/Microsoft.AzureFleet/preview/2024-05-01-preview/azurefleet.json#L984-L985)
```
"error": {
    "$ref": "../../../../../compute/resource-manager/Microsoft.Compute/common-types/v1/common.json#/definitions/ApiError",
    "description": "Error Information when `operationStatus` is `Failed`",
    "readOnly": true
  }
```

**Comment by timotheeguerin** [comment]
Agreed, I think though this should just be a rule to say do not use anything from autorest library(and openapi)
