### ISSUE TITLE
triple auto-suggestions

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#1207]
For every auto-fill suggestion, I'm getting the same one three times in the drop-down list. Issue isn't specific to TCGC

![image](https://github.com/user-attachments/assets/53e12052-79c4-4854-b36f-eda34196f591)

[Playground Link](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtY2xpZW50LWdlbmVyYXRvci1jb3JlIjsKCnVzaW5nIEHENC5DxSVHyCQuCgpAc2VydmljZQpuYW1lc3BhY2UgTXlTxhQ7CssWQ3VzdG9taXphdGlvbnMgewogIEBAxnUoyTIpCn0%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by markcowl** [comment]
@iscai-msft would you mint moving this into the microsoft/typespec repo?

**Comment by iscai-msft** [comment]
Sounds good, I originally opened it here because I only saw it in `typespec-azure`, but if the issue is what @timotheeguerin is saying, that makes sense
