### ISSUE TITLE
[tcgc] emit `SdkVersionEnum` in SdkContext

### ISSUE THREAD

**Issue by chunyu3** [Azure/typespec-azure#1211]
Current `SdkVersionEnum` is not emitted in `SdkContext`. There is no way to get the `SdkVersionEnum`.

Expected:
export `SdkVersionEnum` in `SdkContext`

**Comment by iscai-msft** [comment]
The `SdkVersionEnum` is in `.enums` with `UsageFlags.VersionEnum`. Closing because this is already provided
