### ISSUE TITLE
[Bug][TCGC]: @server description is used as endpoint parameter description

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1212]
### Describe the bug

See this spec: https://github.com/Azure/azure-rest-api-specs/blob/2e5be0e72597c6fc8d438f20e38087d900c16427/specification/confidentialledger/Microsoft.CodeTransparency/main.tsp#L19-L25
```typescript
@server(
  "{endpoint}",
  "Code Transparency Service",
  {
    endpoint: url,
  }
)
```
In TCGC, the description of parameter `endpoint` is `Code Transparency Service`, which is wrong. If `@doc` is not defined, the description should be empty.

### Reproduction

Just parse the spec in the link above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iscai-msft** [comment]
The original point for this was to make sure the description for a server still gets generated, since it is a required parameter, I understand the concern though. Do you have any suggestions? I think it is important to still generate the docs somewhere, since we required users to input them.

**Comment by tadelesh** [comment]
it is weird to use service doc as endpoint param doc. is it possible to put the doc in the client if not provided?

**Comment by archerzz** [comment]
> The original point for this was to make sure the description for a server still gets generated, since it is a required parameter, I understand the concern though. Do you have any suggestions? I think it is important to still generate the docs somewhere, since we required users to input them.

I suggest we just leave it empty if `@doc` is not defined. Let each language team to decide what they want to generate by default.

**Comment by iscai-msft** [comment]
Let me ask for suggestions in the TypeSpec channel. I'm not sure adding it to the end of client is the best either: in the example @archerzz gave, they just duplicated the documentation for the client.
