### ISSUE TITLE
[Bug]: tcgc spread params missing optionality

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#1218]
### Describe the bug

tcgc appears to mark all spread params as required. e.g. for https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/parameters/spread/main.tsp#L268 this param should be optional, but tcgc models it as `optional: false`.

### Reproduction

Build spread params in cadl-ranch with latest tcgc `v0.44.1`.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
from my debug, the optional is true for these optional spread parameter:
![image](https://github.com/user-attachments/assets/1f2d69fa-0ca9-469d-994f-475a58581e9f)
![image](https://github.com/user-attachments/assets/8f9409a9-b143-4fcd-afbf-76d13f51d9c3)

**Comment by jhendrixMSFT** [comment]
My mistake, I was looking at the operation param. Will fix on the codegen side.
