### ISSUE TITLE
Feat. req.: multi-namespace client definitions

### ISSUE THREAD

**Issue by trrwilson** [Azure/typespec-azure#1226]
### Clear and concise description of the problem

The OpenAI REST API has a large surface area with many models and operations, making it is useful to organize the client library into separate namespaces. To accomplish this, we need to be able to define which client namespace each capability-grouped subclient and each model go into.
 
To give an example of why this is important: The OpenAI REST API features three different completion APIs: 1) legacy completions, 2) chat completions, and 3) assistants. The models used in one significantly resemble the models used in the other two, but they are NOT actually compatible with each other. If these three APIs coexisted in the same client namespace, it would be very difficult for users to understand which models are to be used where.
 
Without this feature, we have to write custom code to manually pull every single model into a separate client namespace one by one. Additionally, this is not a one-time effort, since we have to do this for any new models that get added as OpenAI introduces new features.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
We do have the ability to reorganize the client structure (see [doc](https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/02client#customizations)). Do you mean the models should also be separated into different namespace? That should be also an SDK design issue.

**Comment by xiangyan99** [comment]
> We do have the ability to reorganize the client structure (see [doc](https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/02client#customizations)). Do you mean the models should also be separated into different namespace?

At least for Search service, yes. I want the models to be separated into different namespaces.

**Comment by joseharriaga** [comment]
> We do have the ability to reorganize the client structure (see [doc](https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/02client#customizations)). Do you mean the models should also be separated into different namespace?

Correct! OpenAI needs the models organized in different namespaces.

**Comment by tadelesh** [comment]
TCGC has supported namespace.
