### ISSUE TITLE
Default names of some headers should be pascal case

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1227]
### Clear and concise description of the problem

When people define header like below:
```typescript
@header
contentType: string
```

The serialized name is `content-type`, instead of `Content-Type`. For the purpose of maximize compatibility, we'd better use `Content-Type` if the name is not specified in `@header`. Although the services should use case insensitive matching when handling header names (per HTTP spec), it's possible their implementation is not 100% correct and normally it takes quite some time to deploy a fix.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
I think this issue has been closed following the discussion in sync. Please reopen if there is still something you'd like to talk about, thanks!
