### ISSUE TITLE
[tcgc] doc representation in tcgc

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1235]
In TypeSpec, we have `@doc` and `@summary` to give a documentation string for a type.
In TCGC, we have some logic to convert them into two type's attribute: `description` and `details`, the logic is:
1. if there is no `@summary`, then `@doc` content will be put into `description`
2. if there is `@summary`, then `@doc` content will be put into `details` and `@summary` content will be put into `description`

Since I received some feedbacks to keep the original TypeSpec doc structure, I want to revisit the design in this issue.

@haolingdong-msft @archerzz could you share your feedback here?

@m-nash Izzy told me the original design is from you, could you share the thinking?

FYI: @jhendrixMSFT @Azure/dpg-devs 

### create new doc and summary from @doc and @summary and deprecate the previous description and details ###

**Comment by haolingdong-msft** [comment]
I would slightly prefer keeping the original output from TCGC, i.e. `description` and `summary`.
As Java codegen will have some handling using `description` or `summary`, and using the current TCGC's `details` and `description, we can't distinghuish `summary` and `codegen`. So we will meet some generated code description change, and we need to update our codegen logics. e.g https://github.com/Azure/autorest.java/pull/2861#discussion_r1683754341

It's fine to update our codegen logics, but just if we can avoid additional efforts, it's better.

**Comment by archerzz** [comment]
C# is using a different logic for operations. See the codes: https://github.com/Azure/autorest.csharp/blob/302040fc2e59e65e316956fc8ad117169cf5247a/src/AutoRest.CSharp/Common/Output/Models/Requests/RestClientMethod.cs#L62-L63
```csharp
public string? SummaryText => Summary.IsNullOrEmpty() ? Description : Summary;
public string? DescriptionText => Summary.IsNullOrEmpty() || Description == Summary ? string.Empty : Description;
```

I think the above logic is:
- `SummaryText`: It's printed into `<Summary>` in the XML comments.
  - use `Summary` if it's not empty
  - Otherwise use `Description`
- `DescriptionText`: It's printed into `<Remarks>` in the XML comments.
  - Use `Description` if it's not empty and it's not the same as `Summary`

Previously, `Summary` comes from `@summary`, and `Description` comes from `@doc`.

**Comment by archerzz** [comment]
Looks like the logic is the same... But I remember when I set `Summary: tcgc.description` and `Description: tcgc.details`. There are cases the behavior is not correct. I'll do more investigation after merging the TCGC adoption PR.

**Comment by iscai-msft** [comment]
@archerzz this was originally brought up from the csharp team. Can you sync with Michael and lead this issue? Thanks!

**Comment by m-nash** [comment]
@tadelesh 

Can you elaborate on

> Since I received some feedbacks to keep the original TypeSpec doc structure, I want to revisit the design in this issue.

What feedback did you get?  How would you like to change the design?

**Comment by tadelesh** [comment]
@m-nash java has a different logic to handle `@doc` and `@summary`, see haoling's reply above.
I prefer to keep original `@doc` and `@summary` and leave the doc handling logic to each language.

**Comment by archerzz** [comment]
@tadelesh Currently I have a task to clean up csharp generator logic on handling incoming doc properties. Are you going to keep `description` for `@summary`, and `details` for `@doc`? Thanks.

**Comment by tadelesh** [comment]
i mean create new `doc` and `summary` from `@doc` and `@summary` and deprecate the previous `description` and `details`.

**Comment by m-nash** [comment]
> i mean create new `doc` and `summary` from `@doc` and `@summary` and deprecate the previous `description` and `details`.

I agree here can you post this as the proposal up above so its easy to see what the issue is recommending?
