### ISSUE TITLE
[tcgc] use different auth for different `@client`

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1250]
`@useAuth` could be added to different namespace/interface, so tcgc should use the `@useAuth` in the `@client` instead of always use it from service's namespace/interface.

**Comment by timotheeguerin** [comment]
Can you detail a little more the use case here? The goal of `@useAUth` on different namespace/interface is more to give different auth per operation/area of a service. Not sure how a client should be setting that?

**Comment by tadelesh** [comment]
in current tcgc design, only client can have auth info, and current implementation always use the client's corresponding service's auth setting, instead of use the client's namespace/interface auth setting, which should be a bug.

emmm, seems not a real use case. the auth should always be defined in the service side.
