### ISSUE TITLE
[tcgc] document all built-in type with format in azure lib

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1260]
after tcgc 0.44.2, tcgc no longer has azure build-in types (azureLocation, eTag, uuid, etc.) and all handling should be moved to emitter. however, we don't have a centralized place to know all the build-type with format in azure lib. we need to create a doc for that.

**Comment by tadelesh** [comment]
could put the doc here: https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/07tcgcTypes. also tcgc readme should put a link to the doc to let user know all type related info.

**Comment by ArcturusZhang** [comment]
My opinion here is that
it is the emitter author that wants to generate something else from the built-in basic types for some selected types from azure.core, therefore it should be the responsibility of the emitter author to look up for the library you want to support for the cross language definition id.
In the PR that fixes this issue, I updated the doc to explain the `crossLanguageDefinitionId` here is the fully quanlified name of this type, and you should find it from its reference doc.
