### ISSUE TITLE
Define rest/arm resource in TypeSpec

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#1263]
**Background:**
Take a look at the definition of [resource](https://restful-api-design.readthedocs.io/en/latest/resources.html):

> A resource is an object with a type, associated data, relationships to other resources, and a set of methods that operate on it.

To declare a resource, we should have 1) a model, 2) several operations.

However, the existing decorator `@resource` we recommend to users only targets to model. It seems we don't have a way to mark "a model + its corresponding operations" as a resource. 

From [getArmResources](https://github.com/Azure/typespec-azure/blob/f14e021bc1ea936b3d8b36fddc498603d18d6188/packages/typespec-azure-resource-manager/src/resource.ts#L180), I could see the current behavior is: as long as a model is used in a template, it could be the resource model of a resource. It sounds a way to link model and operations. However, it cannot resolve the problem of https://github.com/Azure/typespec-azure/issues/1283

**Proposal:**
1. To mark a resource, 

1.1 we might need something like `@armResouorce(target: interface, resourceModel: Model)` maybe called `@restResource`
```
@armResource(Site)
interface WebApps {
  get is ArmResourceRead<Site>;
}

@armResource(Site)
interface WebApps {
  getSlot is ArmResourceRead<Site>;
}
```

1.2 we might need something like
```
@resourceType("Microsoft.ContosoProviderHub/sites")
@resourceType("Microsoft.ContosoProviderHub/sites/slots")
model Site {}
```
Then when we got an operation, we could first calculate its resource type and then find out the model marked with this resource type.

2. To mark the hierarchy, 

2.1 we might need something like `@armParentResource(target: interface, parent: interface)` <- pay attention the target is interface.
```
@armResource(Site)
interface WebApps {
  get is ArmResourceRead<Site>;
}

@armResource(Site)
@armParentResource(WebApps)
interface WebSlot {
  getSlot is ArmResourceRead<Site>;
}
```

2.2 we could also enable the nested interface like 
```
@armResource(Site)
interface WebApps {
  get is ArmResourceRead<Site>;
  @armResource(Site)
  interface WebSlot {
   getSlot is ArmResourceRead<Site>;
  }
}
```

**Comment by markcowl** [comment]
In ARM parlance, both Slot and Site are separate resources and should be modeled as such.  Why would they need to share a resource type?  Why are they not just two resources with similar properties? 

Especially considering that both have operations, and not all are the same.

Also, can you clarify the priority of this?  Microsoft.Web jhas a GA SDK, so it should not be a prioritized conversion target in this phase.

**Comment by markcowl** [comment]
This is related to these existing issues:

 - https://github.com/Azure/typespec-azure/issues/234
 - https://github.com/microsoft/typespec/issues/160

**Comment by ArcturusZhang** [comment]
@markcowl the appservice site/slot case is only an example for the ambiguous relation between the model and its corresponding operations.
Our main concern right now is about "how typespec expresses the relationship between the model of a resource and the operations of the resource".
Right now, our resourcemanager related decorators/templates are not showing those explicitly. for instance, we might have this:
```
@resource
model Foo extends TrackedResource<FooProperties>
{
// omitted...
}

@armResourceOperations
interface Foos
{
get is ArmResourceRead<Foo>;
createOrUpdate is ArmResourceCreate<Foo>;
// etc
}
```
In this spec, there is no direct relationship between this model and those operations. We believe since a resource consists from a model and a few operations, this might need to be expressed explicitly.

Other language generators might not care this information, but dotnet generator needs this badly even for simplest RPs.

**Comment by ArcturusZhang** [comment]
> @markcowl the appservice site/slot case is only an example for the ambiguous relation between the model and its corresponding operations. Our main concern right now is about "how typespec expresses the relationship between the model of a resource and the operations of the resource". Right now, our resourcemanager related decorators/templates are not showing those explicitly. for instance, we might have this:
> 
> ```
> @resource("foos")
> model Foo extends TrackedResource<FooProperties>
> {
> // omitted...
> }
> 
> @armResourceOperations
> interface Foos
> {
> get is ArmResourceRead<Foo>;
> createOrUpdate is ArmResourceCreate<Foo>;
> // etc
> }
> ```
> 
> In this spec, there is no direct relationship between this model and those operations. We believe since a resource consists from a model and a few operations, this might need to be expressed explicitly.
> 
> Other language generators might not care this information, but dotnet generator needs this badly even for simplest RPs.

So I was told that we have an API `getArmResources` could provide the "model + operation association" information, which might be OK for us to use. But we kind of would like there could be decorators to show those information explicitly and/or provide compiler diagnostic if the author is mkaing a mistake, such as they define the operations that belong to the same resource into different interfaces.

**Comment by pshao25** [comment]
Let's use https://github.com/Azure/typespec-azure/issues/234 to track. I have put some information to it.
