### ISSUE TITLE
Add `resourceType` scalar in `typespec-azure-core` library

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1268]
We also need a `resourceType` scalar to make a specific scalar to be the arm resource type.
DotNet SDK will generate `resourceType` into `Azure.Core.ResourceType`.
Other languages could simply generate it as `string`.

The definition could be
```
scalar resourceType extends string;
```

And the `TrackedResource`, `ProxyResource` template needs to be updated accordingly - their type property should be `resourceType`.

**Comment by markcowl** [comment]
Also, this should change the type of the allowedResourceTypes array in the `armResourceIdentifier` template

**Comment by markcowl** [comment]
est: 5
