### ISSUE TITLE
Add `operationId` in the operation models in TCGC

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1273]
`operationId`s are important to the downstream SDK.
For instance, dotnet SDK will include the operation id in the xml document, which should correspond to the REST API docs.
Other SDKs are using it to generate client names and operation names.
It is also useful in examples.

Could we have it in TCGC's operation model?

**Comment by timotheeguerin** [comment]
isn't that what the new crossLanguageId is for? `operationId` is limiting to the format openapi used to have which is not ideal.

**Comment by iscai-msft** [comment]
I agree with `crossLanguageDefinitionId`

**Comment by ArcturusZhang** [comment]
So one of the concrete examples of why the generator needs the precise `operationId` is here:
https://github.com/Azure/azure-sdk-for-net/pull/45688/commits/08958c390bd12849bae4b2253365bcfa8f9177cd
When the generator is generating the examples, we use operationId to match operations with the example files (by TCGC).
This `operationId` we currently getting is so unstable because it is affected by so many things - therefore as an example, two examples in the above link are deleted because their operationIds no longer match with the operation from the operation.

I agree this is not a problem caused by the operationId itself, but a problem that "we should no longer use the operationId in other places".
I will create an issue for this new item.
