### ISSUE TITLE
[Bug][TCGC] Enum used in decorator is not calculated

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#128]
**Describe the bug**
See the following Typespec snippet: https://github.com/Azure/autorest.csharp/blob/8698fe440049c0adfe370c6286db9f248ea0d7e0/test/TestProjects/MixAPIVersion-TypeSpec/MixAPIVersion-TypeSpec.tsp#L12-L27

Enum `Versions` is used in `@versioned(Versions)` **only**. In `getAllModels`, `Versions` is not calculated.

**To Reproduce**
Try to parse the above typespec definition by TCGC.

**Expected behavior**
Enums used in decorators should be calculated.

**Comment by archerzz** [comment]
It's legal to use enum values as decorator parameters. Below is another example: https://github.com/Azure/autorest.csharp/blob/c1696c88b6974a6e3d3c530d175fb08d28abb6b0/test/TestProjects/Lro-TypeSpec/Lro-TypeSpec.tsp#L26-L28
```typescript
@useAuth(
    OAuth2Auth<[AuthFlow]> | ApiKeyAuth<ApiKeyLocation.header, "x-ms-api-key">
)
```

So, generally we need to calculate enums used in decorators.

**Comment by tadelesh** [comment]
@iscai-msft , `Version` should be the only case for now. to fully support enum or model discussion for decorator's param is complicated. can we just do a special logic for it.
