### ISSUE TITLE
[Bug] {versioning in TCGC is not correctly reflected} 

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#129]
While integrating the latest OpenAI's typespec, I found there're a few operations and properties removed in v2023_12_01_Preview like https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/OpenAI.Inference/routes/images.tsp#L48 , but the operations we get with current tcgc logic still contains these operations. 

```ts
  const operationGroups = listOperationGroups(dpgContext, client);
  const paths: Paths = {};
  for (const operationGroup of operationGroups) {
    const operations = listOperationsInOperationGroup(
      dpgContext,
      operationGroup
    );
    for (const op of operations) {
      const route = ignoreDiagnostics(getHttpOperation(program, op));
      // operation logic
    }
  }
  const clientOperations = listOperationsInOperationGroup(dpgContext, client);
  for (const clientOp of clientOperations) {
    const route = ignoreDiagnostics(getHttpOperation(program, clientOp));
    // operation handling logic
  }
```

I think, tcgc should support filter those operations with a specific api version and if no api version passed, return the result of latest api version.

**Comment by tadelesh** [comment]
@iscai-msft , i doubt do we have a clear design for versioning of models and parameters, etc. in tcgc?

**Comment by iscai-msft** [comment]
we return all operations, with the new tcgc design in the branch `getAllOperations`, all operations and methods will have a list of the api versions they're available for, and that is what you can use to determine api version validation / which functions to generate

**Comment by qiaozha** [comment]
RLC will still be using the old listOperationsInOperationGroup and listOperationsInOperationGroup way and we will not work on migrating to getAllOperations for next semester as of plan. Is it possible to fix that in listOperationGroups and listOperationsInOperationGroup in a easy way? 
/cc @joheredi

**Comment by qiaozha** [comment]
> Since our current priority is to support generating latest version from TypeSpec, I propose to add an optional flag to `createSdkContext` to indicate whether TCGC only generate latest version's result.

I am fine with this approach too.
