### ISSUE TITLE
If access/usage are used at the same time, access is not propagated anymore

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#1290]
Today we have the following TCGC behavior:
- If access(public) is used on a model, propagate to all included models
- If usage() is used on a model, don't propagate (too complex)

Thought, we have an interesting side effect, that if both `access` and `usage` are used at the same time on a model, suddenly the access propogation doesn't work. 

I expect that the two features are indenpendant, and that if used together. we keep having access propagated.

CC @l0lawrence @richardpark-msft

**Comment by tadelesh** [comment]
refer doc: https://azure.github.io/typespec-azure/docs/libraries/typespec-client-generator-core/reference/decorators#@Azure.ClientGenerator.Core.access. `@access` override on model will not be propagated. only `@access(internal)` on operation will impact models' access calculation.
we decided to not to do any propagation for `@access` and `@usage` on model and let user to take responsible for that if they want to change the default calculation.
do we have a real case that are confusing? i could explain the calculation logic and see if we need to do some change.

**Comment by lmazuel** [comment]
Why would we not propagate access on models? If you have A has a property on B, and you make A public, having B as private is literally creating invalid SDK in the first place.

**Comment by tadelesh** [comment]
propagation for `@access` will cause conflict that we could not determine whether the access should be `public` or `private` (a simple example as follows). so if user want to override access, we want them to do the cascade. we just want to reduce the complexity for tcgc calculation.
```
@access(private)
model A {
  prop: B
}

@access(public)
model B {
  prop: A
}

```

**Comment by richardpark-msft** [comment]
@tadelesh, this seems like a good situation to either error out if there are conflicting directives. My main concern here is that a developer (like me!) would have no idea we're relying on an implementation detail of resolution.

@lmazuel mentioned that he didn't think this situation was an error, so it might be more idiomatic to perhaps emit a warning? 

I think the key here is that two people, rather experienced in this area, missed this bug and it took awhile for us to figure out what happened.

**Comment by lmazuel** [comment]
> propagation for `@access` will cause conflict that we could not determine whether the access should be `public` or `private` (a simple example as follows). so if user want to override access, we want them to do the cascade. we just want to reduce the complexity for tcgc calculation.
> 
> ```
> @access(private)
> model A {
>   prop: B
> }
> 
> @access(public)
> model B {
>   prop: A
> }
> ```

I disagree there is a problem here, it's always garbage in, garbage out, and decorator applies in order (namespace, then model). Your situation is quite cleat and explicit to me: A is private, B is public, because they are directly annotated, so there is no computation to do.

**Comment by tadelesh** [comment]
> @tadelesh, this seems like a good situation to either error out if there are conflicting directives. My main concern here is that a developer (like me!) would have no idea we're relying on an implementation detail of resolution.
> 
> @lmazuel mentioned that he didn't think this situation was an error, so it might be more idiomatic to perhaps emit a warning?
> 
> I think the key here is that two people, rather experienced in this area, missed this bug and it took awhile for us to figure out what happened.

if we do the propagation, i believe it will make things even more complicated since we need to define calculation priority, especially for usage propagation. our original thought is that the simplest way is if you need to override access, then take care of all related models.

**Comment by lmazuel** [comment]
Quite simple algorithm:
- If a node marked explicitly with decorator, access is that value (no computation)
- Any node without explicit decorators:
  - If there is a node in the parent hierarchy with that decorator, follow the value of the closest one
  - If no node in the parent hierarchy have an explicit decorator, follow default logic (public only if used by at least one operation, private otherwise)

Usage is more complex, I'm ok to leave usage alone for now
