### ISSUE TITLE
Add `itemName` for paged operations in generated openapi spec

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/typespec-azure#1291]
When defining a paged operation in TypeSpec, folks who are still relying on the generated openapi spec need the `itemName` field to be part of the x-ms-pageable data. typespec-autorest should output this information. 

Playground: [example](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHVzZUF1dGgoCiAgQXBpS2V5xA48xgtMb2NhdGlvbi5oZWFkZXIsICJhcGkta2V5Ij4gfCBPxCoyxS9bCiAgICB7xQYgIOQA3DrHH0Zsb3fkAKUuaW1wbGljaXQsxyVhdXRob3JpesVhVXJsOiAi5AFoczovL2xvZ2luLmNvbnRvc28uY29tL2NvbW1vbi9vxDUyL3YyLjAvyEBlIshSc2NvcGVzOiBbyUl3aWRnZXTNSi5kZWZhdWx0Il3GN30KICBdPgopCkBzZXJ2aWNlKOQAxnRpdGxlOiAiQ8Y6IFfFSSBNYW5hZ2VyIiwKfccxZXLkATkie2VuZHBvaW50fcd05QCV0D9BUElzxRnEYyAgLyoqIApTdXDkAh5lZMglU%2BYAh3MgyFNzIChwcm90b2NvbCBhbmQgaG9zdG5hbWUsIGZvciBleGFtcGxlOgrpAPRlc3R1cy5hcGku8gD%2FKS4KICovxX7IXzogc3RyaW5n5ACYfeQBCOcCvGVkKOcAvy7mAJrnAP3oAmpzKQrkAIZzcGFjZSDVKjsKCuQA41RoySDvAUgg5wFzIMdzLuQAnGVudW0gyGTlASrERccRIDIwMjItMDgtMzHELCAg5AK%2FRGVwZW5kZW5jeSjrAuLIQy52MV8wX1ByZXZpZXdfMikKICBgyUYwYCwKfQoKLy8gTW9kZWxzIC%2FTAeYAx0Eg5wFPxHlAcmVzb3VyY2UoIsYWcyIpCm3EQ%2BgA4%2BgAueQA%2FsYjIOQBL8U%2BICBAa2V5yDtOYW1lIuQAl0B2aXNpYmlsaXR5KCJyZWFkxRbENugBpDsK0lZjb2xvcsdXxQzVLUlEIG9mIHTJNydzIG1hbnVmYWN0dXJlyEDME0lkzUkuLi5FdGFnUHJvcGVydHk75AE3QGRvYygixF9yZXN1bHTEY2HHYSBsaXN0IHJlcXVlc3QuIikKQHBhZ2VkUsUp7QErTGlzdMYX5QE1ylVjb2xsZWPkBB8gdmFsdWXERiAgQGl0ZW1zCiAgxQg%2FOsdGW13lAKfKPlVSSSB0aGF0IGNhbiBiZSB1c2VkIHRv6ACT5QEMbmV4dCBzZeUAueUAn%2BcAyXPHa8QgTGlua%2BQCNMkNYD%2FqARnmAjxPcGVy5QTH%2BAJAYWxpYXPoA9rmBXsgPSDnA%2FtzUmVwZWF0YWJsZVLmAJxzICYKIMkfQ29uZGnEXmFs1iBsaWVudMcbSWQ7yG%2FrAJY97AX7UucCu8ogPO0Amj47CgppbnRlcmbkA9rmAV7qA4nkAa7HFeQBLcVKc%2BYCPuQB8sgvaewAgMlzxD085QR%2BxijmBYPEFlF1ZXJ5UGFyYW1ldGVyc%2BUAijxTdGFuZGFyZNMhICYgU2XkAh7OGD4KICDkAMDrAKznA6Agd2l0aCBhIGN1c3RvbeYB7ucCduUAvSNzdXBwcmVzc%2F8HqG9yZS91c2Utc%2BcAnC3kAxDmAOciICLMXucCTCLuARoy5AEbRm91bmTGNS7pASc8e30s8QMT5ADNfQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fdata-plane%22%5D%7D%7D)

Current output:
```
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
```

Expected output:
```
        "x-ms-pageable": {
          "itemName": "items",
          "nextLinkName": "nextLink"
        }
```

**Comment by catalinaperalta** [comment]
cc @minhanh-phan the App Config v-team needs support for this

**Comment by timotheeguerin** [comment]
[Smaller repro](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtxhVjb3JlIjsKCnVzaW5nIEHEFC5Db3JlOwoKQHNlcnZpY2UKbmFtZXNwYWNlIENvbnRvc28uV2lkZ2V0TWFuYWdlcsQrcGFnZWRSZXN1bHQKbW9kZWwgTGlzdCB7CiAgQGl0ZW1zCiAgxQg%2FOiBzdHJpbmdbXTsKxB5uZXh0TGluawogIGDJDWDJJzsKfQoKb3AgbGlzdCgpOsVXOwo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%5D%7D%7D)
