### ISSUE TITLE
Have `@access` decorator apply to namespaces

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#1299]
### Clear and concise description of the problem

We have `@access` for individual models and properties: we want to be able to apply this globally through a decorator that takes in a namespace / interface. More granularity down the line wins out

```md
| Decorator State            | Model with Public Usage  | Model with Private Usage | Model without Usage |
|----------------------------|--------------------------|--------------------------|---------------------|
| `@access(public)`          | Public                   | Public                   | Public              |
| `@access(private)(default)`| Public                   | Private                  | Private             |
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
why model with private usage has public access?
