### ISSUE TITLE
Param sequence for arm resource

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#130]
Currently, all extra parameters are always placed before the resource/parent resource key path parameters for ARM template which should be a breaking change. e.g., [tsp](https://github.com/Azure/azure-rest-api-specs/blob/9ab4f198f6fe5a803e092919168fb1053ce67260/specification/elasticsan/ElasticSan.Management/Volume.tsp#L49) [swagger](https://github.com/Azure/azure-rest-api-specs/blob/9ab4f198f6fe5a803e092919168fb1053ce67260/specification/elasticsan/resource-manager/Microsoft.ElasticSan/stable/2023-01-01/elasticsan.json#L1900).
I don't know whether it is a compiler behavior or just a `typespec-autorest` issue.

**Comment by markcowl** [comment]
@markcowl find existing issue on ARM operation templates

**Comment by markcowl** [comment]
Need a bit more info on why this is blocking.  There is a planned update to the templates to allow more flexibility with parameters that would accommodate the parameter order https://github.com/Azure/typespec-azure-pr/issues/4013.  However, the order between different parameter groups (query before path or path before query) shouldn't make any difference to client generation

**Comment by markcowl** [comment]
Closing as duplicate
