### ISSUE TITLE
Customization for arm build-in model's visibility and optional setting for resource `properties` property

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#131]
For current ARM resource model the `properties` property is optional and with visibility read and create, but existed RP's swagger may have different setting for them. Other than redefine a new `ProxyResource` model, is there other way to do customization for them?
e.g.: https://github.com/Azure/azure-rest-api-specs/blob/05c4049bc22f0ec65acc18f9835132397049cb9e/specification/elasticsan/resource-manager/Microsoft.ElasticSan/stable/2023-01-01/elasticsan.json#L1652

**Comment by markcowl** [comment]
Because the typing of templates is structural and not nominal, you can use your own resource types if you want a different 'properties' optionality/visibility.

The optionality and visibility in the templates is based on current LintDiff rules and required behaviors for RPaaS clients, so there is a disincentive to update the templates.

Need to understand how this impacts management client generation before we think about adding an extra degree of freedom to templates, but because a custom resource type should work just fine, this should not be blocking.

**Comment by tadelesh** [comment]
It will cause breaking change for lots of languages as required property will become a param in default model ctor. Confirm that custom resource type could resolve it. But it seems this is a common issue for lots of existed swaggers. To prevent too much manual work, I'm going to change conversion logic not to use predefined resource template, instead extends predefined resource base and add properties property separately.

**Comment by markcowl** [comment]
I think this is related to the inheritance hierarchy for resources as well - given how many resources don't conform to the represented TrackedResource/ProxyResource/ExtensionResource hierarchy, we may not want to use the existing model templates anyway

**Comment by markcowl** [comment]
@markcowl ensure that swagger converter has a clear path to avoid breaking client changes

**Comment by MaryGao** [comment]
@tadelesh @markcowl could you help me understand on how this issue is going to resolve? 

This would cause a big breaking for JS([here](https://github.com/Azure/autorest.typescript/issues/2335#issuecomment-1988422027)) and I was wondering how we could mitigate this.

**Comment by tadelesh** [comment]
If service team insist on setting visibility and optionality which is different from current arm template, we will use customized definition to define the resource which will make the visibility and optionality correct.

**Comment by MaryGao** [comment]
Thanks and it works for me!

**Comment by allenjzhang** [comment]
@visibility issue has been addressed.  Still need to find the best way for optionality for brownfields

- Have parallel `legacy.XXResource` in ARM with required properties
- Manually code the above in each spec
- Have a custom mutator decorator that can be augmented.

I am leaning towards last and will have an experiment PR that we can discuss.
