### ISSUE TITLE
tcgc expose skip encoding on SdkQueryParameter type

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#1314]
### Clear and concise description of the problem

At present, there's no field on `SdkQueryParameter` type indicating if the query param should be encoded or not. I believe the default it to presume it's encoded.
In swagger we have `x-ms-skip-url-encoding` and I believe there's a tsp design for this being worked on. This is the tracking issue to ensure the result is exposed in tcgc.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
This should be handled by https://github.com/microsoft/typespec/issues/3736. Closing for this design, please reopen if there's still an issue
