### ISSUE TITLE
[tcgc] do not use `UnionEnumVariant` type directly

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1360]
~In TCGC, we need to use this type, but it is not exported for now. Since `UnionVariant` is exported, I believe it is reasonable to also export `UnionEnumVariant`.~

change task to remove dep on `UnionEnumVariant` in tcgc

**Comment by markcowl** [comment]
@tadelesh Can you expound on why this is needed?  You can use the [helper to get the enumeration details of a union](https://azure.github.io/typespec-azure/docs/libraries/azure-core/reference/js-api/functions/getUnionAsEnum),  what is the scenario where this type gives you data you cannot get elsewhere?

**Comment by tadelesh** [comment]
@markcowl it is used [here](https://github.com/Azure/typespec-azure/blob/da174478ca3815d16cefc15a95c6c491b1cb8f68/packages/typespec-client-generator-core/src/types.ts#L784) to infer the type of the enum member. after checked the code, i believe it could be work around with just pass in the values. let me change the title and the labe. thanks for the info.
