### ISSUE TITLE
[Bug]: ArmResourceCreate* operation templates don't not apply the visibility read in request 

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1383]
### Describe the bug

if there's any properties that has `@visibility("read")`  in the resource model, and ArmResourceCreateOrUpdate* or ArmResourceCreateOrReplace operation template will not filter out the read only properties in the request model. 

This is violating the model validation here https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/Semantic-and-Model-Violations-Reference.md#readonly_property_not_allowed_in_request 

This is blocking our routime mgmt plane release as the generated swagger will have read only required properties. Because in the case if the read only property is required, JS client will not be able to handle it correctly. 

### Reproduction

[playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPuUBJC4u6QCm5AHYUGFyYW1ldGVyyTE%2BOwrkAOd2aXNpYmlsaXR5KCJyZWFkIuQAtXRlc3TEUTogc3Ry5QKJ5wCxyD0gcMlv8gCn6gCL6QGuQWdlIG9mIGXIP%2BUBo2FnZT86IGludDMy5QCMxClDaXR50ipjaXR5P%2BoAjccsUHJvZmls01lAZW5jb2RlKCJiYXNlNjR1cmzlANZwxjA%2FOiBieXRlc8lIVGhlIHN0YXR1c8RLdGhlIGxhc3Qg5ADFYXRpb27lAyn4AStw5AG65wOwU3RhdMRf5QHOzBTpAUDEa8wyxXjlAMJh6QH4xW9AbHJvxDt1cwp1buQC1dFU5QFc5gESLOwAyshHIGNyZcQncmVxdWVzdCBoYXMgYmVlbiBhY2NlcHRlZMRnICBBxw46ICLICyLWUGnEQOQAtOkAwchE7ACcOiAizA%2FaTHVwZGF0xE%2FFQ1XHDjogIsgLyjvpBMrpAMTmANxk5wGaU3VjY2VlZOUAxckM0z%2FFNuQBTWZhaWzJPkbFDTogIsYJ3Dh3YXMgY2FuY2XKPkPHD%2BQFIccL%2FwFAIGRlbGXpAYBExA3mAPnIC%2BQFUe8Db21vduoByukDcU1vdmVSxxXoA2rEc21vdsRoZnJvbSBsb2PmALzFbsQT8QNIyzN0b88xdG%2F6BATnAJVzcG9uc%2BsEruYAlscW7ACX7gNkxT7FZMZ85gLuzW5pbnRlcmbkBj9P6AOMcyBleHRlbmRz9gcDLsspe30K5QbfyCPKG8tZ6ADN5gSrZ2V05AGnQco1UmVhZOwFMyDnAntPcuUCp%2BUB1ssvQ8cdUmVwbGFjZUFzeW5jzD99Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
This is by design.  readOnly properties are ignored in requests in OpenAPI.
