### ISSUE TITLE
The models returned by `getAllModels` should have a deterministic order

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1394]
We have experienced several times that when bumping the version of TCGC, we saw the order of generated models changed.
The order of models from the same spec should not change in different version of TCGC

**Comment by tadelesh** [comment]
The order flip is from the removing duplication logic.
There are two ways to have a deterministic order for all types in TCGC:
1. Alphabetic order of type name
2. Follow the sequence from the compile: each `Namespace` in core will have `models`, `enums` and `unions`, but the order is also implementation-defined and may change, and TCGC will sort with root client first and then sort with the order from client's namespace.

**Comment by tadelesh** [comment]
Update decision: follow sequence from the compiler
