### ISSUE TITLE
[Bug]: [TypeSpec] [Documentation] Versioning examples for different multiple API version scenarios are all the same

### ISSUE THREAD

**Issue by darkoa-msft** [Azure/typespec-azure#1397]
### Describe the bug

There are three scenarios under multiple APIs:  
https://azure.github.io/typespec-azure/docs/howtos/Client%20Generation/09versioning#multiple-api-versions

They all contain the same (default) example.

### Reproduction

Documentation bug.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mario-guerra** [comment]
@catalinaperalta you were added because of the documentation cleanup work you've been doing, but I see the PR you asked me to review doesn't cover this content. Do you already have a plan to redo this content as well? If not I'll take care of this bug.

**Comment by catalinaperalta** [comment]
Redoing this content wasnt part of the plan unless it doesnt apply to both dpg + mpg.

**Comment by AlitzelMendez** [comment]
Hi @mario-guerra , 
I started working on this issue in this pull request:  https://github.com/Azure/typespec-azure/pull/1756

It seems that one of the problems is that the changes to the examples are made in the `tspconfig.yaml` file, but it is not the first visible tab.

Are there any other problems that need to be addressed in this documentation?
