### ISSUE TITLE
[Epic] Remove x-ms-client-flatten from azure-resource-manager

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#14]
We should not generate with flattening, as we decided at the archboard on 12/11 that we will stop with flattening as a pattern.

The plan:
- Remove x-ms-client-flatten from azure-resource-manager, so Swagger emitter do not export them
- If the service was in preview or new, no concerns
- If the service did a GA SDK already, transform in readme.md to add the flattening back

This means building a list of Mgmt teams that did GA from a Swagger that comes from TypeSpec. Last time I checked, it was very few SDKs.

An alternative solution could be to remove flattening, but add a global flag "legacy-flattening" and set that in the tspconfig.yaml instead of a transform.

**Comment by markcowl** [comment]
- Agreed that MPG emitters should not have to understand or rely on this decorator, and that we should provide a client-specific mechanism for toggling this appropriately in generated clients.  However, removing it would mean that we have to disable existing lintdiff rules - this might be a good thing, but I think that providing the appropriate client toggle mechansisms is more important than removing this decoration.

**Comment by markcowl** [comment]
- [ ] [Laurent]:  Remove the lintdiff rule for this
- [ ] Add config to toggle flattening

**Comment by lirenhe** [comment]
@markcowl, could you provide more details about what the 'existing lintdiff rules' are?
Are those rules applying to Swagger or TypeSpec?

**Comment by markcowl** [comment]
@lrenhe https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-nested-properties.md

**Comment by cataggar** [comment]
Just a quick note, that the workaround is to use directives in the readme.
https://github.com/Azure/azure-rest-api-specs-pr/pull/16697

**Comment by qiaozha** [comment]
Not sure if it's expected, I still see the x-ms-client-flatten true from the typespec-autorest emitter output today [playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtxhVjb3JlIjsNCsksyCAvcmVzdM0a20ZyZXNvdXJjZS1tYW5hZ2Vy1lJvcGVuYXBp1h12ZXJzaW9uaW5nxCANCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwyRZB5ACLxCnlAItN5gCKyR5PcGVuQVBJzy5Db3Jl0xMuVHJhaXRz0nFW6QCm5QClQGFybVByb3ZpZGVyTmFtZXNwYWNlDQpAc2VydmljZSh7DQogIHRpdGxlOiAiQXBwIENvbXBsaWFuY2UgQXV0b21hdGlvbiBUb29sIGZvciBNaWNyb3NvZnQgMzY1IiwNCn0pDQpA5wEbZWQox39zxBZhcm1Db21tb27kAJ1zxxoo9QEFLssp6ADDcy52MykNCm7oALbKfC5BcHDqAKjqAKflAPIvKioNCiAqIFRoZSBhdmFpbGFibGUgQVBJIOcApnMuxCAvDQplbnVtIMhtIOUBCsY9IMc%2FMjAyNC0wNi0yN8xAxD8gxUEgIEB1c2VEZXBlbmRlbmN59wDcyGMudjFfMF9QcmV2aWV3XzEp2UHlAeHcNnbkAJpfMDZfMjc6ICLqAKflAZHlAfdkb2MoIlBhcmFtZXRlcnPlAbxvbmJvYXJkIG9wZXLlATAiKQ0KbW9kZWwgT8YbUmVxdWVzdFByxCN0aWXxARZMaXN0IG9mIHN1YnNjcmlwxEYgaWRzIHRvIGJlyGJlZOsBI8wrSWRzOiBzdHJpbmdbXTvoAKx0ZW5hbnToATbxAJPGFyBleHRlbmRzIFByb3h5yBY8%2BAC5PiB7xV1vcCB1cGxvYWQgaXP2A4AuQXJtyBNBY%2BQApkFzeW5jylrGGyzwAJHRET47&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by markcowl** [comment]
Completed
