### ISSUE TITLE
[discussion]: How to migrate from x-ms-skip-url-encoding to allowReserved in client implementation?

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#1403]
### Describe the bug

When adopting the [allowReserved features](https://github.com/Azure/typespec-azure/issues/1318) we are aware of the differences between swagger x-ms-skip-url-encoding and typespec allowReserved.
- [x-ms-skip-url-encoding](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-skip-url-encoding): Setting this as true would prevent the automatic encoding behavior for ALL characters
- [allowReserved](https://datatracker.ietf.org/doc/html/rfc6570#section-3.2.3): Setting this as true would have RESERVED characters :/?#[]@!$&'()*+,;= in parameter values to be allowed to be sent as they are

The skipped-encoding scopes would be different, one is for the whole input and the other is only applied to reserved chars. For me there are mainly two kinds of cases introducing differences.

```
@route("/foo/{+bar}") op foo (@path bar: string): void
```

### Case 1: Should be encoded but not
```
bar := "bar/hello world"

x-ms-skip-url-encoding: /foo/bar/hello world
allowReserved: /foo/bar/hello%20world
```
Not sure for other languages but I tested this in JS and this would not be a big issue because lib would finally encode space as %20 when building request url.

### Case 2: Should be skipped but double encoded
```
bar := "bar/hello%20world"

x-ms-skip-url-encoding: /foo/bar/hello%20world
allowReserved: /foo/bar/hello%2520world
```
This would re-encode the % here as %25. One thing I am not sure is if this is a real requirement for case 2 from customers. 

Regarding this difference for short term we could take them as equivalently and maybe adopt skip encoding logic. But for long term if we consider to do the right thing, I think the correct implementation should only skip encoding reserved chars.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrisradek** [comment]
@MaryGao for case 2, I don't think we should see double-encoding with allowReserved.

For [reserved expansion](https://datatracker.ietf.org/doc/html/rfc6570#section-3.2.2), percent-encoded triplets and reserved characters may be in the substituted values, as opposed to simple expansion where you would see the double encoding. So using allowReserved I would expect that `%20` would not be double-encoded.

Running a quick test in node.js I get the following:
```js
import { parseTemplate } from 'url-template';

const bar = "bar/hello%20world";

const template = parseTemplate(`/foo/{+bar}`);
const url = template.expand({ bar });

console.log(url); // /foo/bar/hello%20world
```
You're right that case 1 is different, though I'm not sure how big a deal that is if `x-ms-skip-url-encoding` is meant to prevent double-encoding.

**Comment by MaryGao** [comment]
@chrisradek Thanks for this detail! I agree with you for case 2, we should not double-encode. This is also what the RFC is defined.

```
Reserved expansion, is identical to simple string expansion except that the substituted values may also contain pct-encoded triplets and characters in the reserved set.
```

There are a lot of misleading when I tried some other libraries which did the double encoding like [python lib](https://github.com/python-hyper/uritemplate).

```
>>> from uritemplate import URITemplate, expand
>>> url = "http://www.{+domain}/" 
>>> t = URITemplate(url)      
>>> t.expand(domain="%20replace") 
'http://www.%2520replace/'
```

**Comment by timotheeguerin** [comment]
So yeah it is slightly different but if we ever get a service that doesn't respect `1.` (invalid service in theory as this is the http spec) or do want to be able to pass encoded `%` then we can visit some kind of patch up solution for those. If there is no other concern I think we can close this and we'll figure that out if we ever encounter it.
