### ISSUE TITLE
[typespec-azure-core] `getLroMetadata` returns wrong final result

### ISSUE THREAD

**Issue by msyyc** [Azure/typespec-azure#1407]
For LRO definition of AppConfiguration https://github.com/Azure/azure-rest-api-specs/blob/ba268c5654f002bc17914e0bc157f19529f1fec1/specification/appconfiguration/AppConfiguration/routes.tsp#L538-L568, `getLroMetadata` returns final result:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/13ab4ba0-e329-4959-a8b7-5cdfac04ffb8">

While the expected result type is `Snapshot`

**Comment by msyyc** [comment]
Hi @markcowl Could you help clarify whether it is bug or author write wrong typespec?

**Comment by msyyc** [comment]
Kindly ping @markcowl

**Comment by markcowl** [comment]
@msyyc 

For the operation to be correct, it should either:

- If this is a resource lifecycle operation, use the `@createsOrReplacesResource(SnapShot)` decorator to indicate that this is a resource reate operation
- If this is not a resource lifecycle operation, ensure that the polling operation has a result field with property type 'Snapshot', or use an `@finalOperation` to indicate a 'get' operation that returns a snapshot, depending on the details of the API.
- Note that this API will be updated as part of the PR to enable non-resource PUT lros.

**Comment by YalinLi0312** [comment]
@msyyc @markcowl thanks for the help! 
I can get right result in generated code now by adding `@createsOrReplacesResource(Snapshot)` in the lro: https://github.com/YalinLi0312/azure-rest-api-specs/blob/803f0d12961c0914b2e8df817335b7b4a301711c/specification/appconfiguration/AppConfiguration/routes.tsp#L537
