### ISSUE TITLE
[Bug]: Body models for spread scenarios should be marked internal

### ISSUE THREAD

**Issue by m-nash** [Azure/typespec-azure#1414]
### Describe the bug

Right now if you have a model like this
```tsp
model Foo {
  x: int;
  @header y: string;
}
```
and you use this in an operation like this
```tsp
op method(...Foo) : Foo;
```

We end up with a model FooRequest which only has the body param `x` which is fine but this type would never be used on the public api surface and therefore should default to access of `internal`.  Today it comes through as `public`.

### Reproduction

See above

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
it should have `internal` access, see the test [here](https://github.com/Azure/typespec-azure/blob/314d527389f4b93ecfbcce460118611b5b46e88f/packages/typespec-client-generator-core/test/packages/spread.test.ts#L623)
