### ISSUE TITLE
Document `@clientName` vs `@encodedName` when to use which for azure services + linter rule?

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#142]
```tsp
// ---- no ----
model Foo {
  @encodedName("application/json", "exp")
  `expire-at`: string;
}

// ---- yes ----
// main.tsp
model Foo2 {
  exp: string;
}

// client.tsp
@@clientName(Foo2.exp, "expire-at")
```

**Comment by timotheeguerin** [comment]
Also be good to confirm `@query` and `@header`

https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/127/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CskZYXp1cmUtdG9vbHMvyCUtY2xpZW50LWdlbmVyYXRvci1jb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA7xxVBxEkuQ8U6R8g5LkNvcmU7CgpvcCB0ZXN0KAogIEBoZWFkZXIKICByZXRyeUFmdGVyOiBzdHJpbmcsCik6IHZvaWQ7CgovLyDmAIcudHNwCkBAxg1OYW1lKMRLOjpwYXJhbWV0ZXJzLspKLCAixQ3mAIjELiIpOwoKQHJvdXRlKCJmb28iKSDnAI4y5ACPLy8gLc4BIEhFQURFUuoAqygiUsRTLU1heWJlIin1ALjKLiAgYXV0b0FkZGVkRGFzaMoj1GzEONIWIFFVRVJZxFNxdWVyeSgiJGZpbHRlciIpIMYJznjFJSAgJHNlbGVjdN9x1nFCT0TEcGBvdGhlci1ib2R5LXByb3BgzmllbmNvZGVk5QGEImFwcGxpY2F0aW9uL2pzb24iLCAiaW7FPCIpIGluQm9kef8AjOoB7fEB3zLtAeDnANssICLGCeQB1N8z8QDLLCAixRPkAJhQcm9wxEQ%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D

**Comment by markcowl** [comment]
- documentation on best practices

Make this part of the DPG discussion
- discourage use of encodedName with a linter rule?

**Comment by markcowl** [comment]
est: 3

**Comment by markcowl** [comment]
Note that linter rule should be separate
