### ISSUE TITLE
The current example solution bonded with `operationId` and it is problematic

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1437]
The current example solution working in the azure-rest-api-specs repo is:
We write a json file with `operationId` field in it, and the autorest emitter will take it to put `x-ms-example` extension on the corresponding operation with that `operationId`. TCGC reads the content of the json file with the specific `operationId` and pass through the content of the example to SDK generators.

I think we have two issues in this solution:
1. from the typespec perspective, this is not a native solution. The example json runs on "conventions".
2. this relies on `operationId` but TCGC and autorest emitter calculate the `operationId` independently - TCGC copies a piece of code from autorest emitter to make sure that TCGC will get the same result as autorest emitter does.

In practice, everything is working fine right now, but still I think we have the above two issues which may potentially lead to issues in some edge scenarios.

Since we have implemented the `@opExample` and `@example` decorators, could we utilize them to get the examples? This would be native to typespec, and we never have a mismatch issue ever again. The autorest emitter could be updated to consume the values in `@opExample` to produce the example json (other tool chain might also need to be updated because some example jsons are generated)

**Comment by ArcturusZhang** [comment]
FYI @timotheeguerin @iscai-msft any thoughts on this?

**Comment by ArcturusZhang** [comment]
My current thoughts:

For short period solution, we could:
1. use `crossLanguageDefinitionId` to replace `operationId`, or make the example json to have both.
I do not quite like it because `crossLanguageDefinitionId` has its own issues, such as: what if we write new clients with new operations in client.tsp? We will lose all the examples.
2. introduce some decorators in TCGC such as `@exampleFile` to link the filepath of the example json, so that TCGC could read it

For long term, we have to:
rewrite all the example jsons using typespec builtin decorators such as `@example`, and we should remove all the example json files from the typespec spec, also updates `typespec-autorest` to make it be able to generate those example json files along with the swagger json from the information in the decorators.

**Comment by markcowl** [comment]
I think we need a very high value justification for making such a sweeping change in specs and how specifications are written.

What is the value of being able to access all of the operation examples in SDK generation?  What are we losing if sdk examples are hand-written, or we have a mechanism for picking up json examples from the examples directory? 

What is the difficulty with obtaining the operationId from the original operation name and interface name?   Could we provide the examples directory as a parameter to emitters?

It is unclear how well using example decorators for *every* operation would scale, especially if we require one or more examples for every operation.

**Comment by markcowl** [comment]
After discussion, closing as won't fix, in favor of a new issue describing a specific problem
