### ISSUE TITLE
[Discussion] Apply autoRoute for ARM singleton resource to namespace in client.tsp

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#1446]
### Clear and concise description of the problem

`@armProviderNamespace` decorator applies to ARM namespace would do following processing for autoRoute of `@singleton` resource.

```ts
    // Set route options for the whole namespace
    setRouteOptionsForNamespace(program, entity, {
      autoRouteOptions: {
        // Filter key parameters for singleton resource types to insert the
        // singleton key value
        routeParamFilter: (operation: Operation, param: ModelProperty) => {
          const paramResourceType = getResourceTypeForKeyParam(program, param);
          if (paramResourceType) {
            const singletonKey = getSingletonResourceKey(program, paramResourceType);
            if (singletonKey) {
              return {
                routeParamString: singletonKey,
                excludeFromOperationParams: true,
              };
            }
          }

          // Returning undefined leaves the parameter unaffected
          return undefined;
        },
      },
    });
```

Currently this decorator cannot be applied to Customization namespace in client.tsp. As error:
```
Only one @armProviderNamespace can be declared in a typespec spec at once.
```

We may need either open it up to client.tsp, or we need to have another decorator in TCGC to have similar effect ([for example](https://github.com/Azure/azure-rest-api-specs/blob/3a77cf7c2d53b823a9ecf6268a789f7ae3535eb5/specification/vmware/Microsoft.AVS.Management/decorator.js)).

Please let us know what's advice from TypeSpec dev.

---

[Discussion in Teams](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1723155427560?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1717740497144&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion&createdTime=1723155427560)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
I think this is just a dup of this no? https://github.com/Azure/typespec-azure/issues/1374

**Comment by weidongxu-microsoft** [comment]
Ah, yes, this is same. Glad to know you've already created the issue.
Let me close this one.
