### ISSUE TITLE
consider changing the type of `responses` from `Map<K,V>` to an array of responses

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#1453]
`JSON.stringify` does not support `Map<K, V>`, maybe because the key of a map may not be a string, but the key of JSON is required to be a string. This makes the object with `Map` property not persistable - especially for such language generators that need to pass information from emitter to the generator.

How about we change the type of `responses` from `Map<HttpStatusCodeRange | number, SdkHttpResponse>` to `SdkHttpResponse[]`, and put the `HttpStatusCodeRange | number` as a new property in `SdkHttpResponse`?

**Comment by ArcturusZhang** [comment]
If it is OK maybe we could do it recently and make it in the next release.
This breaking change is only an API breaking, and its migration should be intuitive.

**Comment by iscai-msft** [comment]
sounds good @ArcturusZhang can you drive this? Thank you!

**Comment by ArcturusZhang** [comment]
has been fixed by #1540
