### ISSUE TITLE
Onboard Microsoft.Workloads/sapVirtualInstances for first beta

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/typespec-azure#146]

**Comment by weidongxu-microsoft** [comment]
The Swagger itself was already GAed https://github.com/Azure/azure-rest-api-specs/blob/main/specification/workloads/resource-manager/Microsoft.Workloads/stable/2023-04-01/SAPVirtualInstance.json

Service want to move it out to separate package.

**Comment by ArthurMa1978** [comment]
Brownfield, don't need to convert it to TSP now.
