### ISSUE TITLE
[Bug]: [sample] can't link to correct sample when operationId is not unique

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#1469]
### Describe the bug

See openapi [issue](https://github.com/Azure/typespec-azure/issues/1467), we can't link to correct sample when operationId is not unique

### Reproduction

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQrSGmh0dHDEGg0KdXNpbmcgVHlwZVNwZWMuUmVzdDvRFkh0dHDFLkBzZXJ2aWNlKHt9KQ0KbmFtZXNwYWNlIEZvb8UgbW9kZWwgQSB7DQogIHByb3AxOiBzdHJpbmc7DQp9xUJyb3V0ZSgiYiLNQULGM81AxkIyy0IgIH3EBchEY8REICBpbnRlcmbERkPIOW9wIG9wMShAYm9keSDEBTogQSk6IHZvaWTSR2XGR%2BoAjUXIR%2B8Aj%2BYAkTPtAJHHTPUAhv0AiMs9xQXbK%2FABPC9k5ACyynFExnHfQg0K3iE%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
it should be the underlying operation id issue. operation id does not honor namespace hierarchy.

**Comment by tadelesh** [comment]
i think the ultimate solution for example is to use `@example` from typespec. tcgc will not handle this conflict since it is an underlying problem and may not exist for the ultimate solution.
