### ISSUE TITLE
Can `x-ms-azure-resource ` be safely removed

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#1474]
There is some spec still using it and seems like csharp autorest generator might make use of it.
1. Figure out if this is actually useful
2. If it is, why are spec using it not using the base resource types
3. If they have valid legacy reason then we need some deprecated decorator to get parity

**Comment by markcowl** [comment]
- This is still used by older emitters for c-sharp
- We need an ARM decorator that will be consumed by autorest to add this extension
- The decorator should be called `@customAzureResource` and have an associated linting rule that discourages its usage (this can be excluded from legacy rulesets)

**Comment by live1206** [comment]
> This is still used by older emitters for c-sharp

@markcowl Could you specify where the usage is in older emitter of csharp? I couldn't find the usage in https://github.com/Azure/autorest.csharp

**Comment by markcowl** [comment]
There are actually multiple places where this or a similar mechanism (configuring paths as resource paths) are used in c-sharp

**Comment by pshao25** [comment]
We only found ComminutyGallery fits this situation. Do you have more examples?
