### ISSUE TITLE
[Bug]: Azure Playground TypeGraph window is showing error

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#1480]
### Describe the bug

In Azure playground, it is showing error in TypeGraph window.

```
Something went wrong:
TypeError: Cannot convert a Symbol value to a string
Try again
```

### Reproduction

https://azure.github.io/typespec-azure/playground

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
Not seeing this when I follow the link

**Comment by timotheeguerin** [comment]
I repro, if you pick the arm samples and load the type graph

**Comment by timotheeguerin** [comment]
Just an issue with union with no variants. Repro in the core playground here https://typespec.io/playground?c=dW5pb24gRm9vIHsKICBzdHJpbmcsCiAgaW50MzIKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D
