### ISSUE TITLE
[TCGC][Bug]: SdkEndpointParameter missing __raw type

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1496]
### Describe the bug

In `client.initialization.properties`, we can't get the __raw type, however, we need to pass the __raw type to getWireName, so that the renamed parameter name in url template can be handled correctly

<img width="739" alt="image" src="https://github.com/user-attachments/assets/cd22862e-18a7-4eed-b8f9-aad0e322b658">

### Reproduction

```
@server(
  "{Endpoint}/anomalydetector/{ApiVersion}",
  "endpoint description",
  {
    @doc("""
Supported Cognitive Services endpoints (protocol and hostname, for example:
https://westus2.api.cognitive.microsoft.com).
""")
    Endpoint: string,
    
    @doc("Api Version")
    @path
    ApiVersion: APIVersion,
  }
)
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qiaozha** [comment]
it's also missing the clientDefaultValue in the SdkEndpointParameter

**Comment by tadelesh** [comment]
the raw value should be in template arguments of the endpoint parameter: 
![image](https://github.com/user-attachments/assets/0a76d2d9-f295-4fd9-be29-3e15a32ba38f)
