### ISSUE TITLE
[TCGC][Bug]: SdkEndpointParameter fail to extract the correct url parameters

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1497]
### Describe the bug

in the giving typespec
```
@server(
  "{host}.{subdomain}.{sufix}.com/{apiVersion}",
  "Confidential Ledger Service",
  {
    @path
    host?: string = "one",
    @path
    subdomain?: string = "two",
    @path
    sufix?: string = "three",
    @path
    apiVersion?: string = "v1"
  }
)
```
we should get four SdkEndpointParameters, host, subdomain, sufix, apiVersion for the endpointUrl, however, we only see an endpoint before the credential parameter
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/1c6e0343-1e0c-4a40-a4fa-36221470b8e1">

### Reproduction

n/a

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
endpoint is a parametrized parameter which has four templated parameters
