### ISSUE TITLE
[TCGC][Question]: should we provide endpoint SdkEndpointParameter for constant host

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1498]
### Describe the bug

```
@server("https://api.openai.com/v1", "OpenAI Endpoint")
```
in this case, the endpoint is a constant, should we allow customers to modify it, if yes, should we have a required endpoint parameter in the client side ?

Currently, tcgc still returns the required endpoint parameter to us, and because of https://github.com/Azure/typespec-azure/issues/1496#issuecomment-2335108995 we have to set it as a required endpoint parameter. which doesn't quite make sense to me.

### Reproduction

n/a

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
currently, tcgc return the endpoint parameter as required, and the endpoint parameter type has one template argument of `{endpoint}` which is required but with a client default value of `https://api.openai.com/v1`. @iscai-msft do you think we should mark this template argument with optional?

**Comment by iscai-msft** [comment]
`required` or `optional` means whether it's required or optional on the server side. While we don't like required params with client default values, I think this is ultimately a required input with a client default value. Thoughts?
