### ISSUE TITLE
TCGC misrepresents binary payloads

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#15]
NOTE: this is using the changes in https://github.com/Azure/typespec-azure/pull/6

For reference.

https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/encode/bytes/main.tsp#L246-L274

For the body parameter, the `defaultContentType` is still `application/json` and `kind` is `bytes` (correct) which has an incorrect `encode` value of `base64` (I don't know what the value _should_ be though).

**Comment by tadelesh** [comment]
I have a quick fix with the latest commit in https://github.com/Azure/typespec-azure/pull/6.
For the encode of bytes, the new logic is:
if @encode, honor @encode value, else,
if it is a body with content type `application/json`, encode will be `bytes`
if it is a body with other content type, encode will be `base64`
if it is parameter/properties, encode will be `base64`
@iscai-msft, could you confirm.

**Comment by jhendrixMSFT** [comment]
Not sure I follow. IMO, `encode` should only be set to `base64` when the content type is `application/json`.

**Comment by iscai-msft** [comment]
Yes, the correct order should be 
1. @encode decorator
2. `bytes` + `application/json` defaults to a `bytes` type with encoding of `base64`
3. `bytes` + other non-json content types, i.e. `application/octet-stream` / `image/png` output a binary payload. We currently represent this as a `bytes` type with no encoding, but I do want to follow up with the team about this

**Comment by lmazuel** [comment]
This is a recurring topic, as we have also scenario where the body is JSON, but we want to treat as bytes (SDK is passthrough), and right now we can't expresse that. There was a discussion to make this a design discussion:
https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1700613734908?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1700613734908&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion%20%F0%9F%90%AE&createdTime=1700613734908

**Comment by jhendrixMSFT** [comment]
We have solved this for Go by looking at the default content type for a response. If it's not `application/json`, `application/xml`, or `text/plain` (we are loose on the matching), then we assume it to be a binary stream. Does this seem reasonable? It's working so far.

**Comment by iscai-msft** [comment]
closing in favor of https://github.com/Azure/typespec-azure/issues/614

**Comment by jhendrixMSFT** [comment]
Reopening as I believe this is distinct from #614 which is about streaming/SSE.

To be clear, this is about "vanilla" binary responses. e.g. https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/payload/content-negotiation/main.tsp. The response types are being modeled as base64-encoded bytes which is clearly incorrect.

**Comment by iscai-msft** [comment]
@jhendrixMSFT I've added this to the upcoming sprint

**Comment by jhendrixMSFT** [comment]
@tadelesh what does the fix look like?

**Comment by tadelesh** [comment]
the response type is a `bytes` and the encode is also `bytes`. see the test [here](https://github.com/Azure/typespec-azure/blob/f752035c70fd8bfa7fb719fe4230ac28db58f6fd/packages/typespec-client-generator-core/test/packages/responses.test.ts#L261).
