### ISSUE TITLE
[Bug][TCGC]: Arm LRO library models are not included in `sdkPackage.models` 

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1530]
### Describe the bug

See the discussion: https://github.com/Azure/typespec-azure/pull/1515#discussion_r1754770163

Even we set `filter-out-core-models: false`, some Arm LRO library models are not included in `sdkPakcage.models`, like `ArmOperationStatusResourceProvisioningState`.

### Reproduction

Parse an LRO operation defined by ARM LRO template. Check the `sdkPakcage.models` with configuration `filter-out-core-models: false`. You can find an example in the link above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
the full lro logic should be considered when handling tcgc models. will be resolved when consolidating models and operations conversion logic.
