### ISSUE TITLE
`no-response-body` rule is triggering for some standard templates

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#1552]
Some templates shown in the samles trigger that rule which is confusing

reason this wasn't caught before it is that rule is only triggered on namespace starting with `Azure.` (legacy behavior from before the linter system)

### Arm

```
  delete is ArmResourceDeleteWithoutOkAsync<Employee>;
  /** A sample HEAD operation to check resource existence */
  checkExistence is ArmResourceCheckExistence<Employee>;
```

[Playground Link](https://azure.github.io/typespec-azure/playground?e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D&c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshS6QDD0EPvALRBUEkgx0lz5ACfZW51bSDIUCDkAI7ELjIwMjEtMTAtMDEtcHJldmlld8g1xDQgIEB1c2VEZXBlbmRlbmN5KPUBLegBZ3MudjFfMF9QxkhfMSnEQGFybUNvbW1vbuQBlXPHKtdIyynLVDXESGDyAKlgLAp95gDzQegA9esBDiDoAknkAMhtb2RlbCBFbXBsb3llZSBpcyBUcmFja2Vk6ACCPMgcUHJvcGVydGllcz7lASQuLukApuQB1FBhcmFtZXRlcskxPjvoAIbJX3DJRNJ8ymDpAYNBZ2Ugb2YgZcg%2F5QF4YWdlPzogaW50MzI7CscpVGhlIHN0YXR1c8QwdGhlIGxhc3QgxFFhdGlvbuUChiAgQHZpc2liaWxpdHkoInJlYWQi5AFBcOQBG%2BcDDVN0YXTEX%2BUBL8wU6QDMxGvMMsV45QCnYekBWcVvQGxyb8Q7dXMKdW7kAjbRVOUA6HN0cmluZyzoAMrpA1BoYXMgYmVlbiBjcmVhdGVkxVQgIFN1Y2NlZWRlZDogIskMItI%2FxTbEdmZhaWzJPkbFDTogIsYJ3Dh3YXMgY2FuY2XKPkPHD%2BQDp8cLykLkARjpAllp5AC85AEdZGVsZXRlZMZARMQNaW5nOiAiyAvkA9cK5QQg6ACCT%2BgBtHMKaW50ZXJm5APZ6AIk5gIbxlXEZUHKOMVSZVdpdGhvdXRPa0FzeW5j7AKL5wJSIHNhbXBsZSBIRUFE6gIgIHRvIGNoZWNr6gDDZXhpc3RlbuYDJiDGHkXJFM58Q80dzHZ9Cg%3D%3D)

## Azure core

```tsp
 createWidget is Operations.ResourceCreateWithServiceProvidedName<Widget>;
```
[playground](https://azure.github.io/typespec-azure/playground?e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fdata-plane%22%5D%7D%7D&c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHVzZUF1dGgoCiAgQXBpS2V5xA48xgtMb2NhdGlvbi5oZWFkZXIsICJhcGkta2V5Ij4gfCBPxCoyxS9bCiAgICB7xQYgIOQA3DrHH0Zsb3fkAKUuaW1wbGljaXQsxyVhdXRob3JpesVhVXJsOiAi5AFoczovL2xvZ2luLmNvbnRvc28uY29tL2NvbW1vbi9vxDUyL3YyLjAvyEBlIshSc2NvcGVzOiBbyUl3aWRnZXTNSi5kZWZhdWx0Il3GN30KICBdPgopCkBzZXJ2aWNlKOQAxnRpdGxlOiAiQ8Y6IFfFSSBNYW5hZ2VyIiwKfccxZXLkATkie2VuZHBvaW50fcd05QCV0D9BUElzxRnEYyAgLyoqIApTdXDkAh5lZMglU%2BYAh3MgyFNzIChwcm90b2NvbCBhbmQgaG9zdG5hbWUsIGZvciBleGFtcGxlOgrpAPRlc3R1cy5hcGku8gD%2FKS4KICovxX7IXzogc3RyaW5n5ACYfeQBCOcCvGVkKOcCVHMpCsRwc3BhY2XnAkTmAKznAQ87CgrkAMtUaGUg9gEwIOcBWyDHWy7kAIRlbnVtIMhi5QESxEXHESAyMDIyLTA4LTMxxCwgIOQCp0RlcGVuZGVuY3ko6wLKyEMudjFfMF9QcmV2aWV3XzIpCiAgYMlGMGAsCn0KCi8vIE1vZGVscyAv0wHmAMdBIOcBN8R5QHJlc291cmNlKCLGFnMiKQptxEPoAOPoALnkAP7GIyDkAS3FPiAgQGtlecg7TmFtZSLkAJdAdmlzaWJpbGl0eSgicmVhZMUWxDboAYw7CstWSUQgb2YgdMlgJ3MgbWFudWZhY3R1cmVyx2rME0lkyknmAPZPcGVy5QNp%2BAD6YWxpYXPoAnzmBB0gPSDnAp1zUmVwZWF0YWJsZVJlcXVlc3RzICYKIMkfQ29uZGnEXmFs1iBsaWVudMcbSWQ7yG%2FrAJY97ASdUucBdcogPO0Amj47CgppbnRlcmbkApLmAYnqAkNDcmVhdGVzIGHHGlBhcnTmASRjxRrGFiBp7ACAyXPGPVdpdGjHclByb3ZpZGVk5AG%2BPMY7PuQBVg%3D%3D)

**Comment by markcowl** [comment]
est: 5

**Comment by timotheeguerin** [comment]
Copy core rule but exclude 202
