### ISSUE TITLE
[Bug]: should we have apiVersion lifted to client initialization if not all operation has this parameter?

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1595]
### Describe the bug

In this spec
```
      model ApiVersionParameter {
        @query
        "api-version": string;
      }
      @route("/test")
      op test(...ApiVersionParameter): string;
      @route("/test1")
      op test1(): string;
```

operation test1 doesn't have any parameter call apiVersion at all, but we still have an `api-version` parameter in the client.initialization.properties. with onClient: true and optional: false

![image](https://github.com/user-attachments/assets/b0d71e85-371d-4a56-9585-a2cb2dfd7a8d)

I wonder if this makes sense? 

### Reproduction

N/A 

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
@iscai-msft could you take a look?

**Comment by iscai-msft** [comment]
yep, i was meaning to take a look today, i'll bump this in priority. thanks!

**Comment by msyyc** [comment]
I think:
-  if there is only one kind of api-version, then TCGC shall lift it into client initialization. It makes sense since  there is only one kind of api-version which will be convenient for SDK users as client level signatures. For those API that has no parameter api-version could just not use this client level signature. Just like `subscription_id` in MGMT SDK, not all API has this parameter however all language SDKs treat it as client level signatures.
- if there is multi kinds of api-version, then TCGC shall not lift it.

**Comment by weidongxu-microsoft** [comment]
Kind of valid for me...

If the client has 99 API needs api-verison, 1 API does not need api-version, should we put it to client.initialization? If yes for 99:1 but no for 1:1, then where is the switch point...

**Comment by msyyc** [comment]
Some legacy package (e.g. [sql](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/sql/resource-manager#tag-package-composite-v5)) asks SDK release with tag that contains multi swagger files configured with different api-version. But SDK team is asking for one api-version for all services, so in the future, there shall be less and less scenarios for multi kinds of api-versions.

**Comment by tadelesh** [comment]
> Different values for api-version in query parameter. For example, some legacy package (e.g. [sql](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/sql/resource-manager#tag-package-composite-v5)) asks SDK release with tag that contains multi swagger files configured with different api-version. But SDK team is asking for one api-version for all services, so in the future, there shall be less and less scenarios for multi kinds of api-versions.

i think for typespec, we could ignore that. i believe all migration to typespec will follow the new no mult-api version in one service rule.

**Comment by iscai-msft** [comment]
Ok sweet, are we all in agreement to not modify the behavior of TypeSpec here? Our current behavior is we elevate to the client if there's at least one api version parameter.

We could add linter checkers for a mix of query / header api versions, but overall our behavior stays the same? cc @qiaozha

**Comment by qiaozha** [comment]
Got it, the problem is, will you automatically append the query api-version parameter as long as it's defined in the client options even if it's not defined in that specific operation?

**Comment by iscai-msft** [comment]
Yes, the `api-version` parameter still shows in the `method.operation.parameters`, but it won't show in `method.parameters`. The mapping from `method.operation.parameters["api-version"]` will point back to the `client.initialization.properties["api-version"]` instead of a method parameter, since it will be elevated to the client

**Comment by tadelesh** [comment]
i think qiaoqiao means the specific operation without api-version param. then the `method.parameters` and `method.operation.parameters` will both not have the `api-version` param.

**Comment by iscai-msft** [comment]
Oh yes, that's already the design. I'm going to close the issue, please reopen if there's anything else. I can leave the issue open for the linter checkers, but I feel like it's not super needed
