### ISSUE TITLE
[tcgc] namespaces in TCGC

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#1604]
### Clear and concise description of the problem

As we start implementing "namespace is namespace" in our language emitters, TCGC plays an important role in helping emitters get the information they need to generate. At the same time, it is important that we are not breaking, both for ease of migration, and also because some languages (like javascript) don't really have a concept of "namespace" and won't be adopting this behavior the same way the other language emitters are.

As such, I propose a multi-part approach in getting TCGC to help with the "namespace is namespace" push.

1. Ensure that the existing `.namespace` string on `SdkClientType`s returns the correct namespace
2. Add a `.namespace` string onto `SdkModelType` and `SdkEnumType`, so we can generate these models in the correct space.
3. Add additional helper method `getNamespaceToClients(sdkContext)` that returns a mapping of namespaces to clients in those namespaces.
4. Add additional helper method `getNamespaceToModels(sdkContext)` that will return a mapping of namespaces to models in those namespaces

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
Another option is making `SkdPackage` to be hierarchy with namespace, and add a flag like `flatten-namespace` and default to true to prevent breaking change for some languages.

**Comment by chunyu3** [comment]
How about the namespace defined in `@client`? As following, the client include more parts separated by `.`, and all the parts except the latest one will be the namespace of the client, will tcgc help to merge this to `namespace` of the client?
```
@client(
  {
    name: "SubNamespace.SecondClient",
    service: FirstTest.Service,
  }
)
```

**Comment by archerzz** [comment]
For 3 & 4, what's the user scenario? There are basically 2 ways to provide the relationship between the namespaces and their belonging entities (clients, models, etc):
- a hierarchy of `SdkInputNameSpace` with child properties representing clients, models, etc.
- or a flat mapping like suggested on top

**Comment by tadelesh** [comment]
link original customer ask: https://github.com/Azure/typespec-azure/issues/1226

**Comment by iscai-msft** [comment]
> #1226

We had previously decided to move away from this because we didn't find it intuitive with how namespaces are set up. We believe we should continue with namespace solely as a `namespace` object, instead of also supporting namespace behavior based off of string parsing

**Comment by tadelesh** [comment]
> For 3 & 4, what's the user scenario? There are basically 2 ways to provide the relationship between the namespaces and their belonging entities (clients, models, etc):
> 
> * a hierarchy of `SdkInputNameSpace` with child properties representing clients, models, etc.
> * or a flat mapping like suggested on top

3 is aimed to provide the hierarchy.

**Comment by tadelesh** [comment]
> How about the namespace defined in `@client`? As following, the client include more parts separated by `.`, and all the parts except the latest one will be the namespace of the client, will tcgc help to merge this to `namespace` of the client?
> 
> ```
> @client(
>   {
>     name: "SubNamespace.SecondClient",
>     service: FirstTest.Service,
>   }
> )
> ```

the name should be the client name directly. tcgc will not do any magic to it.

**Comment by weidongxu-microsoft** [comment]
> > How about the namespace defined in `@client`? As following, the client include more parts separated by `.`, and all the parts except the latest one will be the namespace of the client, will tcgc help to merge this to `namespace` of the client?
> > ```
> > @client(
> >   {
> >     name: "SubNamespace.SecondClient",
> >     service: FirstTest.Service,
> >   }
> > )
> > ```
> 
> the name should be the client name directly. tcgc will not do any magic to it.

So, I assume when namespace refactor done, service would need to write
```ts
@client(
  {
    name: "SecondClient",
    service: FirstTest.Service,
  }
)

namespace FirstTest {
  @clientNamespace("<base_namespace>.SubNamespace")
  namespace Service {
  }
}
```

**Comment by weidongxu-microsoft** [comment]
If possible, Java would like `SdkConstantType` has `.namespace`

**Comment by tadelesh** [comment]
> If possible, Java would like `SdkConstantType` has `.namespace`

i talked with haoling last week, since it is a special logic for some languages to treat optional constant as enum, it's better to opt in a conversion directly in tcgc.

**Comment by tadelesh** [comment]
> > > How about the namespace defined in `@client`? As following, the client include more parts separated by `.`, and all the parts except the latest one will be the namespace of the client, will tcgc help to merge this to `namespace` of the client?
> > > ```
> > > @client(
> > >   {
> > >     name: "SubNamespace.SecondClient",
> > >     service: FirstTest.Service,
> > >   }
> > > )
> > > ```
> > 
> > 
> > the name should be the client name directly. tcgc will not do any magic to it.
> 
> So, I assume when namespace refactor done, service would need to write
> 
> @client(
>   {
>     name: "SecondClient",
>     service: FirstTest.Service,
>   }
> )
> @clientNamespace("<base_namespace>.SubNamespace")
> namespace SecondClient {
> }

correct. but the problem here is all models' namespace (used by operation) will not be changed.
