### ISSUE TITLE
[TCGC] Need to use `@flattenProperty` for operation parameter from `client.tsp`

### ISSUE THREAD

**Issue by mccoyp** [Azure/typespec-azure#1610]
My understanding is that `Azure.ClientGenerator.Core` should only be used from a `client.tsp` file. We need to use the [@flattenProperty](https://azure.github.io/typespec-azure/docs/libraries/typespec-client-generator-core/reference/decorators#@Azure.ClientGenerator.Core.flattenProperty) decorator in each data-plane Key Vault library, but I couldn't figure out a way to use this from `client.tsp` since we're trying to target operation body parameters with the decorator (examples from [Administration](https://github.com/Azure/azure-rest-api-specs/blob/f45bc57f3b591adaad5b6b0f2f047b82b3139209/specification/keyvault/data-plane/Security.KeyVault.Administration/routes.tsp#L257), [Certificates](https://github.com/Azure/azure-rest-api-specs/blob/3b6d03a9f99c176b19d36e9de62ac42d173e0d90/specification/keyvault/data-plane/Security.KeyVault.Certificates/routes.tsp#L143), [Keys](https://github.com/Azure/azure-rest-api-specs/blob/a086ddf9759b1e727d4f7777e973e9e4c86399e7/specification/keyvault/data-plane/Security.KeyVault.Keys/routes.tsp#L56), and [Secrets](https://github.com/Azure/azure-rest-api-specs/blob/mccoyp/kv-secrets-tsp/specification/keyvault/data-plane/Security.KeyVault.Secrets/routes.tsp#L52)).

I've tried a number of approaches, such as:
- `@@flattenProperty(FooNamespace.barOperation::parameters)` (this didn't target the parameter I wanted and instead was mapping to a built-in parameters attribute)
- `@@flattenProperty(FooNamespace.bazModel)` (since the model in one example was only used as a flattened parameter)
- `@@flattenProperty(FooNamespace.bazModel.quxAttribute)`
 
but none of them accomplished the same thing as using the decorator directly.

Is there already a way to accomplish this? Thank you for any help!

____

##### (As a side bit of feedback, I've been struggling to reference the documentation for guidance. The most relevant page for SDK customization, as far as I can tell, is the [Setup for SDK customization](https://azure.github.io/typespec-azure/docs/howtos/Client%20Generation/01setup) page -- that did help for learning how to compile with customizations, but I had to reference existing `client.tsp` files from other services to learn how to actually structure the customizations.)

**Comment by tadelesh** [comment]
There is some limitation to locate a spread parameter for TypeSpec. cc: @timotheeguerin to see if there is any workaround, and can we have a doc to clarify what kind of element is possible to be locate and how?
If you just want to make the body parameter to be flatten in client, you could try with spread directly. For example:
```
op updateSetting is Azure.Core.Foundations.Operation<
  {
    /** The name of the account setting. Must be a valid settings option. */
    @path settingName: string;

    /**
     * The parameters to update an account setting.
     */
    ...UpdateSettingRequest;
  },
  Setting
>;
```

**Comment by tadelesh** [comment]
close as it should not be a tcgc issue. @mccoyp if you have further concern, feel free to reopen or create a new one for typespec since i believe it is a typespec limitation.
