### ISSUE TITLE
[Question] TCGC consolidates all integer types less than `int32` to `int32`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#163]
**Describe the bug**

Apparently we are converting all types that are less than `int32` to `int32`: https://github.com/Azure/typespec-azure/blob/18dd4909cb4d9e86d095c3024762a1f54046268d/packages/typespec-client-generator-core/src/types.ts#L171
But we actually need those to generate into different types in some SDKs (for example dotnet SDK)

**Comment by ArcturusZhang** [comment]
@iscai-msft is this by design?

**Comment by iscai-msft** [comment]
I did this by design because at the time looking at the languages, it didn't seem that we needed anymore granularity. If this is needed I'd be happy to change, what cases would `c#` need?

**Comment by ArcturusZhang** [comment]
thank you @iscai-msft 
I am consolidating our emitter code and noticed a difference, dotnet is distinguishing those int8 or uint8 types in our emitter, but actually we did not do anything in our generator about them - therefore if we align with these, it is fine, no one will have a breaking (because we do not have any real use cases for them right now)

But in the perspective of TCGC, I believe maybe we should keep the differences of those typespec builtin types, and let each language to decide whether they want to consolidate some of them into the same type

**Comment by iscai-msft** [comment]
Yeah that's definitely valid, I will use this as an issue to change tcgc behavior, thanks @ArcturusZhang
