### ISSUE TITLE
Autorest emitter silently emit no files when version option is used an doesn't match the versions of the service

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#1647]
```
import "@typespec/versioning";

using TypeSpec.Versioning;


@versioned(Versions)
@service
namespace DemoService;

enum Versions {
  v1,
  v2,
}

model A {}
```
[Playground Link](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR07CgoKQMcsZWQoxxlzKQpAc2VydmljZQpuYW1lc3BhY2UgRGVtb1PGFjsKCmVudW0gyDAgewogIHYxLMQGMiwKfQoKbW9kZWwgQSB7fQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22options%22%3A%7B%22%40azure-tools%2Ftypespec-autorest%22%3A%7B%22version%22%3A%22v13%22%7D%7D%7D)

set
```
options:
  "@azure-tools/typespec-autorest":
    version: v3

```

**Comment by allenjzhang** [comment]
Need to introduce an error message on `no matching version found`.
