### ISSUE TITLE
[tcgc] add support for a `MultiPartFile` type

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#165]
Currently, our code at large assumes models to be JSON objects. Since we need to support `multipart/form-data`, this is not the case. For example, in the following model
```typespec
model JsonModel {
  prop: bytes
}
```
`prop` will default to a b64 encoded string, which is the correct behavior. However, in a model used for multipart, we would instead want to recognize the `bytes` as being for a file, and also add information about `content-type` and `filename`. 

```typespec
model MultipartInputModel {
  picture: bytes;
}
```

So proposal is to add a new primitive type like the following, which would be the above property `picture`'s type

```typescript
interface MultipartFormDataFile:
  kind: "multipartformdatafile";
  fileStream: SdkBytesType (with default encoding of `binary`, still has access to @encodedType);
  filename: string | undefined;
  contentType: string | undefined;
```

**Comment by iscai-msft** [comment]
Notes: 
1. raise a diagnostic error if we have a model used both as multipart and as json.
2. Typing of a `MultipartFormDataFile` will be `FileContent | [string, FileContent] | [string, FileContent, string]`
3. We do not recursively set models as multipart form data. If a multipart model has a property that is a model, that property off model will be JSON

**Comment by weidongxu-microsoft** [comment]
Looks good. Java currently would have different class for different multipart file field (i.e. `image` field generates `ImageFileDetails` class), but that would be our internal processing and it could change in future if this gets to azure-core.

I assume 2nd point
`Typing of a MultipartFormDataFile will be FileContent | [string, FileContent] | [string, FileContent, string]`
Just means a combination the types of `fileStream`, `filename`, `contentType`?
