### ISSUE TITLE
[Bug]: Add ARM linting rule to flag @get operation override on ArmResourceActionAsync and ArmProviderActionAsync

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#1672]
### Describe the bug

Default Action verb is `@post`, but we do allow verb override to such as `@get`. Should have linting rule to flag error on anything other than `@post`.

### Reproduction

[Playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfNIGF6dXJlLXRvb2xzL8gsLcYVY29yZd8sySxyZXNvdXJjZS1tYW5hZ2VyxDgNCnVzaW5nIFR5cGVTcGVjLkh0dHA70RZSZXN00hZW6QCvyRxBxGouQ29yZc8TUsd9TcZ8xXsvKiogQ29udG9zbyDIICBQcm92aWRlciDmAKZtZW50IEFQSS4gKi8NCkBhcm3IIU5hbWVzcGFjZQ0KQHNlcnZpY2Uoew0KICB0aXRsZTogIsdbyDBIdWJDbGllbnQiLA0KfSkNCkDnAW9lZCjnAMpzKQ0KbshXIE1pY3Jvc29mdC7SSvEAwEFQSSDHUHPlAKtlbnVtIMhYIOUAmcQwMjAyMS0xMC0wMS1wcmV2aWV3yDfFNiAgQHVzZURlcGVuZGVuY3ko9QE%2B6AF6cy52MV8wX1DGSV8xKcVBYXJtQ29tbW9u5AGpc8cr10nLKctVNcVJYPIArGDkATvoAPtB6AD96wEYIOgCZeUAzm1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAIc8yBxQcm9wZXJ0aWVzPuYBLC4u6QCs5AHpUGFyYW1ldGVyyTI%2BO%2BsAi8ljcMlI8wCBymXqAZBBZ2Ugb2YgZchBxDYgIGFnZT86IGludDMy5QHqxixDaXR50y1jaXR5Pzogc3Ry5gMKyC9Qcm9maWzUX0BlbmNvZGUoImJhc2U2NHVybCLlAXJwxjI%2FOiBieXRlc8tMVGhlIHN0YXR1c8RPdGhlIGxhc3Qg5ADQYXRpb27mAx8gIEB2aXNpYmlsaXR5KCJyZWFkyVnEGeUDrFN0YXTEY%2BUBtswU7AFRxHDMNcV95QDLYekB48Z0QGxyb8Q%2FdXMNCnVu5ALI0VnmAW7mASAs7gDUyEwgY3JlxCpyZXF1ZXN0IGhhcyBiZWVuIGFjY2VwdGVkxWwgIEHHDzogIsgL5APP1VNpxEPkALzpAMnJR%2BwAozogIswP3E91cGRhdMRSxkZVxw86ICLIC8w%2B6QTT6QDN5gDlZOgBrVN1Y2NlZWTlAM7JDNVCxTnkAVxmYWlsykFGxQ46ICLGCd47d2FzIGNhbmNly0FDxxDkBS7HC%2F8BT25nIGRlbGXqAZJExA7mAQXIC8RD8gObbW926gHg6gOdTW92ZVLHFukDlsR5bW92xG5mcm9tIGxvY%2BYAxcZ0xBTzA3HLNnRv0DR0b8sy%2BQCec3BvbnPsBL3mAJ%2FHF%2B0AoO4Dj8VAxmrmAIPmAxTQdMZVRXjkB65SZXN1bHQge8UZ5AW26AG0T%2BgD1nMNCmludGVyZuQGj%2BgAq%2BcEvUBnZXQgYmFkU3luY%2BQBnEHKQEFjxD3EGekFLizsAWjGDeQFheUA1%2BQFStBSMcdT6AXby1PEKyDpAI4sxw%2FrANLHE1N1YnNjcmlwxDnHP2NvcGXEHecFvA%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AlitzelMendez** [comment]
talked with Allen offline and the purpose of this issue: a new rule to flag anything other than get and post as error.
