### ISSUE TITLE
[Bug]: tcgc, diagnostic, false positive on method with spread

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#1675]
### Describe the bug

The diagnostic is error and cannot be ignored.

TCGC appears to be wrong when the method body parameter got spread (or maybe only when there is 2 spread in body?).

```
error @azure-tools/typespec-client-generator-core/no-corresponding-method-param: Missing "completeRequest" method parameter in method "complete", when "completeRequest" must be sent to the service. Add a parameter named "completeRequest" to the method.
error @azure-tools/typespec-client-generator-core/no-corresponding-method-param: Missing "embedRequest" method parameter in method "embed", when "embedRequest" must be sent to the service. Add a parameter named "embedRequest" to the method.
error @azure-tools/typespec-client-generator-core/no-corresponding-method-param: Missing "embedRequest1" method parameter in method "embed", when "embedRequest1" must be sent to the service. Add a parameter named "embedRequest1" to the method.
```
[log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4225891&view=logs&j=c28f120c-e125-5ec5-8d4c-ba1a4d871fcc&t=b83a11c4-9f3c-5115-167f-68dcfe6f5445&l=336)

[full run on existing libs](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4226171&view=logs&j=c28f120c-e125-5ec5-8d4c-ba1a4d871fcc&t=b83a11c4-9f3c-5115-167f-68dcfe6f5445)

### Reproduction

source is
https://github.com/Azure/azure-rest-api-specs/blob/016b80ae90f5fabc1e572efabd3ecb1030d444c0/specification/ai/ModelClient/routes.tsp#L26
(it is not merged to main branch, PR https://github.com/Azure/azure-rest-api-specs/pull/28438)

SDK at https://github.com/Azure/azure-sdk-for-java/tree/5e07b10d9b04fe8c73a4ee6c78f8aeb9786e0543/sdk/ai/azure-ai-inference

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
The root cause is from: https://github.com/microsoft/typespec/issues/4757. Suggestion: refine the spec definition since spread additional properties model in body is meaningless.

**Comment by weidongxu-microsoft** [comment]
Asking service to update the tsp https://github.com/Azure/azure-rest-api-specs/pull/28438/files#r1802429139
