### ISSUE TITLE
[Bug]: type existence check return false for the same union type in tcgc

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1677]
### Describe the bug

In JS, we need to generate union as type alias, however, tcgc doesn't provide union types as the references types, therefore, we need to extract the union types from the sdkPackage.models. but I found the same type has been added into emitQueue more than once.
![Image](https://github.com/user-attachments/assets/5d8b29b0-560d-4f33-8bdc-701d06511382)
![Image](https://github.com/user-attachments/assets/5b28119d-be1f-4fc3-8836-6771d1c8bbc8) 

In this case, the type should be the same as what the emitQueue has, but the type existence check returns false. 
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/azure/resource-manager/models/resources/main.tsp#L34-L40

### Reproduction

https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/azure/resource-manager/models/resources/main.tsp#L34-L40 It's a cadl-ranch test case.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
Proposal:
- Treat `SdkUnionType` as referenced type and cache them in TCGC context when doing typing conversion
- Add `unions` in `SdkPackage` to expose all the unions

cc: @iscai-msft for thoughts.

**Comment by qiaozha** [comment]
Similar issue found out in nullable type.
