### ISSUE TITLE
[Bug]: usage is incorrect for lro initial response model

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1678]
### Describe the bug

In this case https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/azure/core/lro/rpc/main.tsp#L35 the GenerationResponse is the initial response, which is an internal model for JS, but the usage we get for this model is Json & Output.  
![Image](https://github.com/user-attachments/assets/272929ff-9e4b-4e4a-8556-8b28189f6ed1)

I wonder if the usage is correct, and how to filter the model out if it's expected.  

In JS, we didn't filter the core models though this model will be filtered out by core model filter options. But since we plan to deprecate this options, we will have to provide a way to filter it out anyway?

### Reproduction

N/A

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArcturusZhang** [comment]
I personally do not think so.
TCGC should not make assumptions how a SDK generator would use those models related with an operation.
A generator could decide to generate the initial response as part of its API, and this model is really one of the possible return types of this operation.
Therefore from TCGC's perspective, this is by design and correct.

**Comment by tadelesh** [comment]
the initial response could be filtered with this pr's change: https://github.com/Azure/typespec-azure/pull/1887
