### ISSUE TITLE
[Bug]: sdkMethod.response.type is missing for some LROs

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#1688]
### Describe the bug

Generating https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databasewatcher/DatabaseWatcher.Management/watcher.tsp#L141-L154

`sdkMethod.response.type` is `undefined` which seems incorrect as this LRO returns a `Watcher` type for the final result. If it helps, the `sdkMethod.lroMetadata.finalResponse` is also `undefined`.

I believe this regressed somewhere in `v0.46.x` as it was working in `v0.45.x`.

### Reproduction

Generate https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databasewatcher/DatabaseWatcher.Management/watcher.tsp#L141-L154 using tcgc `v0.47.1`

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
i could not repro with the spec. the response type and final response type of lro metadata is all `Watcher`.
![Image](https://github.com/user-attachments/assets/8734b7c2-8c4b-433a-97b0-8ae26a8c3c6e)
![Image](https://github.com/user-attachments/assets/3494ecf3-3b82-4cea-8e82-d3dfe16c943b)

**Comment by jhendrixMSFT** [comment]
I don't think it's that simple. The `sdkMethod.operation` contains the correct response type. Put another way, `sdkMethod` and `sdkMethod.operation` don't agree on the response type.

**Comment by tadelesh** [comment]
for lro, tcgc will use the final response from `getLroMetadata` to be the method response, which the operation's response is the initial response.

**Comment by tadelesh** [comment]
talked with typespec team and the conclusion is to fix the tsp. see https://github.com/Azure/azure-rest-api-specs/pull/31423
