### ISSUE TITLE
TypeSpec versioning concerns

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#1695]
I notice that we have an [epic for versioning story](https://github.com/Azure/typespec-azure/issues/1626) and @timotheeguerin also proposed new design [here](https://github.com/Azure/typespec-azure/issues/1621#issuecomment-2411693874) but I still want to discuss if the high-level philosophy in versioning is correct.

TypeSpec versioning design is based on diffs from version to version. Generally all versions should be in `one` tsp(we may have plans to sperate to preview and stable ?).

This could work fine with quite simple iteration between versions. For other cases it is not easy to express the diffs. For example we want to update the an operation from non-LRO to LRO. Ideally we'd like to see changes like below.

```diff
- delete is ArmResourceDeleteSync<BgpPeer>;
+ delete is ArmResourceDeleteWithoutOkAsync<BgpPeer>;
```
To achieve this, we need `@sharedRoute` to build two operations and reviewers also need to carefully review the diff to know the real change. So these diffs are not direct.

[tsp](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/kubernetesruntime/KubernetesRuntime.Management/bgppeer.tsp#L52)
```
  @sharedRoute
  @added(Versions.v2024_03_01)
  delete is ArmResourceDeleteSync<BgpPeer>;

  @sharedRoute
  @renamedFrom(Versions.v2024_03_01, "delete")
  @removed(Versions.v2024_03_01)
  oldDelete is ArmResourceDeleteWithoutOkAsync<BgpPeer>;
```

Also the detailed data(operations/models) would in in different version state, this results in a lot of complexity.
- not easy to understand which version is which kind of API shape
- not easy to update specific version for some bugfix
- not easy to retire some specific versions
- not easy to add new version
- how to ensure existing version is immutable with typespec and its library is still iterating

With more versions coming in authors need to care more specs(I would assume all publicly available versions need to be retained), the old existing versions are like techinical debt which no longer change but need to care about during adding new stuff.

I was just thinking if we could design the language and its tools to allow
- authors only need to focus on current version and compared version
- reviewers/authors could easily know real diffs
- we easily know which version's spec

**Comment by timotheeguerin** [comment]
1. The need for `@sharedRoute`: This is unfortunate and we could potentially make it better by having the http library understand versioning and review the http service at each version. Though this now has quite large performance implication.

2. Not easy to understand which version is which kind of API shape
This is the balance between defining the version snapshot like we had with swagger and copy pasting or having this evolving spec. 

3. not easy to update specific version for some bugfix
would argue it much better here as you most likely should apply the bug fix to the whole spec and not just one api version, do you have example of this being tricky?

4. not easy to retire some specific versions
agree and part of the versioning improvements would involve working on a tool to help with that

5. not easy to add new version
Part of of the versioning improvements cover helping with adding bulk new items to the api. I do agree that changing operation for example could have a better alternative. However some of our policy around versioning is that it not a goal to make it easy to make non additive changes. Apis should upgrade with additive change and if its hard to describe other things then its not as much as a design flaw as a warning that maybe you shouldn't be doing that.

6. how to ensure existing version is immutable with typespec and its library is still iterating
Not sure how to action on that


Part of the proposal also talks about this but we shouldn't mix Azure style of versioning from what most external people want for versioning where it is more about documentation and its always just evolving the same endpoint(no api version selector)

**Comment by markcowl** [comment]
closing as duplicate (and including this dicussion in) the attached parent issue.
