### ISSUE TITLE
[tcgc] handle singleton key exclusion

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#1709]
Handle exclusion of singleton keys from operation parameters namespace [here](https://github.com/Azure/typespec-azure/blob/0f289160fadd84b6e0935d014740407f7e10354e/packages/typespec-azure-resource-manager/src/namespace.ts#L224) . Will require us to add logic to deal with `@typespec/http.setRouteOptionsForNamespace`

**Comment by tadelesh** [comment]
a common solution: filter method parameter or model property that is decorated with `@path` but not in http operation path parameter list.
