### ISSUE TITLE
Modify typespec-azure-core/verb-conflict to allow @@get and @@post operations for @@actions

### ISSUE THREAD

**Issue by AlitzelMendez** [Azure/typespec-azure#1735]
Right now, the actions are triggering this rule:

[Playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHVzZUF1dGgoCiAgQXBpS2V5xA48xgtMb2NhdGlvbi5oZWFkZXIsICJhcGkta2V5Ij4gfCBPxCoyxS9bCiAgICB7xQYgIOQA3DrHH0Zsb3fkAKUuaW1wbGljaXQsxyVhdXRob3JpesVhVXJsOiAi5AFoczovL2xvZ2luLmNvbnRvc28uY29tL2NvbW1vbi9vxDUyL3YyLjAvyEBlIshSc2NvcGVzOiBbyUl3aWRnZXTNSi5kZWZhdWx0Il3GN30KICBdPgopCkBzZXJ2aWNlKOQAxnRpdGxlOiAiQ8Y6IFfFSSBNYW5hZ2VyIiwKfccxZXLkATkie2VuZHBvaW50fcd05QCV0D9BUElzxRnEYyAgLyoqIApTdXDkAh5lZMglU%2BYAh3MgyFNzIChwcm90b2NvbCBhbmQgaG9zdG5hbWUsIGZvciBleGFtcGxlOgrpAPRlc3R1cy5hcGku8gD%2FKS4KICovxX7IXzogc3RyaW5n5ACYfeQBCOcCvGVkKOcAvy7mAJrnAP3oAmpzKQrkAIZzcGFjZSDVKjsKCuQA41RoySDvAUgg5wFzIMdzLuQAnGVudW0gyGTlASrERccRIDIwMjItMDgtMzHELCAg5AK%2FRGVwZW5kZW5jeSjrAuLIQy52MV8wX1ByZXZpZXdfMikKICBgyUYwYCwKfQoKLy8gTW9kZWxzIC%2FTAeoAx2NvbG9yIG9mIGEg5wFc5ACGdW7kAJrmANtDxSLkALboAVbnAMFCbGFja8clIMYm5QDBxRg6ICLFCCLJL1doaXRl0y%2FFGDogIsUIyi9S6gJAyy1SZWQ6ICJSZWTKKUdyZWXoAKzMK8UYOiAixQjKL0JsdfQAhsQX5QC0deQAhOQBQSoqIEHsARRAcmVzb3VyY2UoIsYWcyIpCm3kAWTIT%2BgB2uQBWMYjIOQCUMU%2BICBAa2V5yDtOYW1lIuQBuEB2aXNpYmlsaXR5KCJyZWFkxRbENugCxTvoALnLVuUBtcdXxQw67AGszTJJROQB3XTJPCdzIG1hbnVmYWN0dXJlyEXME0lkzXsuLi5FdGFnUHJvcGVydHk76AEcxF1yZXBhaXIgc3RhdGXxAkRAbHJvU3RhdHVz7QJPUsU0xBll9AJVxiXHWnMgc3VjY2VlZGVkxVMgIFPIEDogIskM6wJkzj5mYWlsyTtGxQ06ICLGCdk1d2VyZSBjYW5jZco8Q8cP5AVAxwvRQHdhcyBzZW50IHRv5QFw8wFnU2VudFRvTcsZ5ADH0RXsAoFzdWJtaXTkBU3nAW1yZXF1ZXN05QUq7QFw7AKL5gFlUscr7AKY6QGs6gITz1rFTSDIDuUBqegCX%2BsBvO0CZWTEVOQFyXRpbWUgd2hlbsVfx1hpcyBzY2hlZHVsZWTkAR1vY2N16AESyRlEYXRlVGnkAvd1dGPIDd9lx2XmAOXkAX9jcmVhdOkBtccO31rfWsdadXDEJchaxw7fWt9ax1pjb%2BQG7cpcyRDXXusDf3BhcmFtZXRl5ALq6wIO5QHkdXPJZvUCHOYDmlDEQuoGk%2FQEMSBiZeQJaeYBzOkApkBwYXRoCiDHJOwEM%2B8FOydz5ACn8QVCxBTkBUBAcGFyZW50UsgZ5gCj7gVYUGFy7gLE5AUf6AClyV3uBWHENP8FZfkFZUlE5AKmdXNl5QFWcmVvcmRlxCXQcMQL7wUt8gFFxCX%2FBXT%2FBXTvBXRkZXRhaWxzxGBh6ACd7wQV6gE38QQZxBVSxjXwBB5JZGVudGlmaWVzIHdobyBzaWduZWQgb2bmAMjPaugDv8UlT2ZmQnnuAgIvIEFu6AnJ5gCr5AuvbGV0b24g6AIG5QDTUHJvdmlkZXMgYW5hbHl0aWNzIGFib3V0xXXkAYTkAz5tYWludGVu5AV6xk3mAM3wAlXJQ%2F8CWegBDUHJc%2BwCXmnoAQhy5QFP5ACIyVkgb2JqZWN0LiDEKnJl5ATbb25seSBvbuYClmQgJ2N1csR5J%2B0ClclBSeYCfPYCkmnkBmDHQOQNOusC8nVtYmXlCad1c2XlAfzqA6HHaXVzZUNvdeQK%2FWludDY01z%2FkBIhzyz3lBIPvA9zGD85N6QPW7AK2xFHGR3PwAYvMJ%2BoJKOwG5e0BdMwvJ3MgdW5pcXXkA0btAUXMJf8BSPUDlc9l6wmb%2BQQLzzNmdWxsIGFkZHJlc%2BYA8iDIDv8Dv%2BUDEk9wZXLlDhv4C5RhbGlhc%2BgNLuYOzyA9IOcNT3NSZXBlYXRhYmxl5wO6cyAm5QkSxh9Db25kacReYWzWIGxp5QMQxRtJZDvIb%2BsAlj3sD0%2FoAzrKIDztAJo%2BOwoK5AOWcmbkDS7mA1HnA0nrAOsg5woC5wurxCPnBp7rA8gg5AEoxS%2FoAfBzaGFyZWRSb3V0ZQogIGdldMYpyVfGVuQDf8kTcy5H5Abc7wC1xik8xj8%2BO%2F8AiGRl5Ad6%2FwCP6gCPRMUv%2FwCV%2BgCV5Q60xkrmD7luZXZlcgogIOQBW%2BUBR8Ydy0%2FnAMBD5QjacyBvcucIi3PqAMRhc3luY2hyb25vdXNseegHrm9sbGluZ8lJ5wUPcy74AVvkA0fmCUBPclXFY8df7gDeTG9uZ1J1buQRpOgA5uYAnMg26gF66gF76gCs5QCd6QCDz1zIUVJlYWTRR%2BYBe%2FgA9ukIpf8A9%2FcBw%2BQA%2FeYCC%2F8A9ekA9cZH8QCmTGlzdOoMX8Yrc%2BYAnGxpc%2BcAg%2FACMshUxD3yAiTEFlF1ZXJ55Qm75Qn95QOQPFN0YW5kYXJk0yEgJiBTZWxlY88YPvMCa%2BkHE%2FMBr8kc6QG4yhL%2FAbvLK8dy%2FgLGz2vGH99u9gJ60HjpAOrmCwfyA1zkAPLkByDyBB%2FtDVXnAmMjc3VwcOQGAf8VDG9yZS91c2Utc%2BcBpi3pBGRzIiAiVGhp5QDVYSBjdXN0b23qBILoAIfoEtsuIuQC2HLkBIooIucTmXMve8YJSWR9L%2BcOxi97yUNJZH3lBxbvC%2FvEcEZvdW5k6gSp%2BwShzDrmDDXmAo%2FzARrqAlYqKiBT5w3g6gyd5gtUxDDoB0P%2FA6f3BJ5AZ2XEa%2BgOQeYAg%2FACG%2FMDq0FjxBvyA1nzAMrZGSAmIMcKSWRSZXNwb25zZUjlFlDmAP198gcb5At56gpo9waBxCXxBn7pAQXEHv8Gbf8HAsVD8gOBzX%2FrDzvLFvwDcldpdGjnCBvnC85k5A171XPsBFDKb%2B0A49ds6wRMzlPvBgvKVuwFw9tZ7QW8zlvrBcDFQfkFxMQe%2FQXI1F7nDYggYWxs5Q4n5g%2FG8QvZ%2BAMfxXTqAyPzAh7kAyfnDbj0AKH0B71vbOQGKGlvbvIDJ8RD7AMS8g5L8QjG7QMI7Av9%2BwMKzCf0AwzMIP8DDvoDDsxF9QaRcmVwbGHkAenvAJHrAx7NGP4GklLGTtd35gMU0mfvAO3XZOUDGNZZ6QMazUf%2FCSvHYSjMNOUCZ%2FsBeeoJMfsAsfoJN%2FYAvuUDfc1Q8wN%2FzCD9A4HPZOcQpCAiZ2xvYmFsIiBSUEPqAm7lDuzmBdlkcyB3aXRo6AKjaW5mb3JtxSXrEKhvdmVy5APG5xn95w8N5gelxxTkB%2Fp0deQPC29wyCjqArZScGPpALnkA3R7feobVMY5U%2BUOX%2BoOZyAgxSPtDZMKPjsK&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fdata-plane%22%5D%7D%7D)
.

The message is: Operation template 'LongRunningResourceAction' requires HTTP verb 'POST' but found 'GET'.

we want to allow get as it is also a common action

**Comment by markcowl** [comment]
Actually, this is by design.  GET cannot be long-running

**Comment by AlitzelMendez** [comment]
FYI @allenjzhang
