### ISSUE TITLE
[TCGC][LRO] LRO initial response model should not be generated

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#1750]
Link https://github.com/Azure/typespec-azure/issues/1538#issuecomment-2367621254, create a seperate issue to make it more clear.
### Issue
For below example, `LroOperationStatus` model is initial response, and should not be generated. But TCGC will return the model with name `LroOperationStatusError` and 'public' access, thus after adopting TCGC's access, this model will be generated, which is incorrect. 

```ts
model LroOperationStatus<TStatusResult = never, TStatusError = Foundations.Error> {
    @key("operationId")
    @visibility("read")
    id: Azure.Core.uuid;

    @visibility("read")
    @lroStatus
    status: JobStatus;

    @visibility("read")
    createdDateTime?: utcDateTime;

    @visibility("read")
    expirationDateTime?: utcDateTime;

    @visibility("read")
    lastUpdateDateTime?: utcDateTime;

    error?: TStatusError;
    result?: TStatusResult;
  }

  op LroLongRunningRpcOperation<
    TParams extends TypeSpec.Reflection.Model,
    TResponse extends TypeSpec.Reflection.Model,
    Traits extends {} = {}
  > is Azure.Core.RpcOperation<
    TParams & RepeatabilityRequestHeaders,
    Foundations.AcceptedResponse<LroLongRunningStatusLocation<TResponse> &
      Foundations.RetryAfterHeader> &
      RepeatabilityResponseHeaders &
      LroOperationStatus,
    Traits
  >;

  @route("/jobs/{id}")
  op getJob is LroLongRunningPollOperation<JobResult>;

  @pollingOperation(LongRunning.getJob)
  @route("/jobs")
  op createJob is LroLongRunningRpcOperation<
    {
      @body body: JobData;
    },
    JobResult
  >;
```

### Solution
TCGC returns usage `0` to indicate the model should not be generated.

**Comment by ArcturusZhang** [comment]
I personally do not think so.
TCGC should not make assumptions how a SDK generator would use those models related with an operation.
A generator could decide to generate the initial response as part of its API, and this model is really one of the possible return types of this operation.
Therefore from TCGC's perspective, this is by design and correct.

**Comment by haolingdong-msft** [comment]
If TCGC keeps the current usage and access for LRO intial response, we should have a way to let emitter know when to update access and do not generate this model. But this will make TCGC's access less helpful as emitter still need to update it based on usage.
/cc @ArcturusZhang  @tadelesh
