### ISSUE TITLE
Cookie support in tcgc

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#1792]
Basic cookie support was added in TypeSpec http(for request parmater. Right now tcgc will crash if it get cookies, should maybe emit a diagnostic if this is not a goal to support

https://github.com/Azure/typespec-azure/pull/1791 uptook the change but as it was a little more advanced to emit the diagnostic filed an issue

**Comment by MaryGao** [comment]
Our nightly ci failed with the same reason. And I don't think we have general cookie parameter support in azure core or codegen for JS yet. @lmazuel @lirenhe Is this our goal to support them? Do we have real requirement?

**Comment by timotheeguerin** [comment]
@MaryGao thats just the ts compilation right? It doesn't fail on existing specs?

**Comment by MaryGao** [comment]
Offline confirmed with @timotheeguerin this is an community contribution for a feature wanted for third party and we don't have a requirement yet for emitter so we could ignore the parameter and emit warning to let customers be aware of that.
