### ISSUE TITLE
Property `extendedLocation` is not identified as an allowed resource envelope property

### ISSUE THREAD

**Issue by witemple-msft** [Azure/typespec-azure#183]
Some Azure services use a property `extendedLocation` in their resource envelope. As far as I can tell, this is a valid resource envelope property for Azure RPs, but the TypeSpec Azure Core doesn't recognize it:

```tsp
@singleton
model VirtualMachineInstance
  is ExtensionResource<VirtualMachineInstanceProperties> {
  /** Name of the virtual machine instance. */
  @key
  @segment("virtualMachineInstances")
  @visibility("read")
  @path
  name: string;

  /** Gets or sets the extended location. */
  extendedLocation: ExtendedLocation;
}
```

This produces a warning:

```
Property "extendedLocation" is not valid in the resource envelope.  Please remove this property, or add it to the resource-specific property bag.TypeSpec(@azure-tools/typespec-azure-resource-manager/arm-resource-invalid-envelope-property)
```

The workaround is to suppress the warning, but ideally we would recognize this property and provide a common definition of ExtendedLocation if appropriate.

**Comment by markcowl** [comment]
@markcowl Look for dup issue

**Comment by allenjzhang** [comment]
https://github.com/Azure/typespec-azure/pull/736
