### ISSUE TITLE
Override description from operation template

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#1844]
Currently when we use a template, e.g., ArmResourceRead, its responses have its own description like
```
"responses": {
  "200": {
    "description": "Azure operation completed successfully.",
    "schema": {
      "$ref": "#/definitions/EmployeeListResult"
    }
  },
  "default": {
    "description": "An unexpected error response.",
    "schema": {
      "$ref": "../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse"
    }
  }
}
```
But brownfield service defined its own description. We should have a way to override these descriptions.

**Comment by markcowl** [comment]
@pshao25 We should *not* try to match the response description for existing swaggers.  This should be a non-goal.  Descriptions of response models make sense, but the descriptions of response status codes in swagger are of limited value.

If there is a need in some very strange case to do this, you can use the `Response` parameter in each operation template to replace the responses and add your own documentation [like this](https://azure.github.io/typespec-azure/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPuUBJC4u6QCm5AHYUGFyYW1ldGVyyTE%2BO%2BgAhslfcMlE0nzKYOkBg0FnZSBvZiBlyD%2FlAXhhZ2U%2FOiBpbnQzMjsKxylDaXR50ipjaXR5Pzogc3Ry5QLrxyxQcm9maWzTWUBlbmNvZGUoImJhc2U2NHVybCLkAWBwxjA%2FOiBieXRlc8lIVGhlIHN0YXR1c8RLdGhlIGxhc3Qg5ADFYXRpb27lAv4gIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUDhVN0YXTEX%2BUBo8wU6QFAxGvMMsV45QDCYekBzcVvQGxyb8Q7dXMKdW7kAqrRVOUBXOYBEizsAMrIRyBjcmXEJ3JlcXVlc3QgaGFzIGJlZW4gYWNjZXB0ZWTEZyAgQccOOiAiyAsi1lBpxEDkALTpAMHIROwAnDogIswP2kx1cGRhdMRPxUNVxw46ICLIC8o76QSf6QDE5gDcZOcBmlN1Y2NlZWTlAMXJDNM%2FxTbkAU1mYWlsyT5GxQ06ICLGCdw4d2FzIGNhbmNlyj5Dxw%2FkBPbHC%2F8BQCBkZWxl6QGARMQN5gD5yAvkBSbvA29tb3bqAcrpA3FNb3ZlUscV6ANqxHNtb3bEaGZyb20gbG9j5gC8xW7EE%2FEDSMszdG%2FPMXRvyi%2F3AJVzcG9uc%2BsEg%2BYAlscW7ACX7gNkxT7FZMZ85gLuzW5pbnRlcmbkBhRP6AOMcyBleHRlbmRz9gbYLsspe%2BgFOm4gYWx0ZXJu5AMOZGVzY3JpcOgA4eYAskN1c3RvbUFybegAtzxUPuQBr84SOwrlBwPIcspq6wCo6AEc5gT6Z2V0ykfFNVJlYWQ8CiAgIMkqLMUOyGcgPfMAjcgrPiB8IEVycm9yyBoKICA%2BO%2BQFH%2BUDDk9y5QM65QJpy3NDxx1SZXBsYWNlQXN5bmPKU8Q%2F5QOK0DdQYXRjaFPMLCzzBeHFQOYC0M9A5QLNZVdpdGhvdXRPa9N3bGlzdEJ5yDBHcm91cM9ETMUiUGFyZW501DxTdWLqAc7GO8YzzBnMOegGjiBzYW1wbOsDnGFjxUR0aGF05gKZ6QZRdG8gZGlmZmXkAITvAxzFKe4AskHFSO8BN%2BsDp8gN5gHA8wCSSEVBROoGesR%2BY2hlY2vqAKpleGlzdGVu5gf0IMYeRckU7wH7zR3uB88%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D)

But again matching the description of the status code responses in swagger should be an explicit non-goal of conversion
