### ISSUE TITLE
Handle resource that does not satisfy the definition of resource

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#1847]
CommunityGallery is an example. Service claims CommunityGallery/CommunityGalleryImage/CommunityGalleryImageVersion are all resources in these [lines](https://github.com/Azure/azure-sdk-for-net/blob/e666aabc5f0028225436c3d08e95fa49800bae5a/sdk/compute/Azure.ResourceManager.Compute/src/autorest.md?plain=1#L104-L106). However, in the swagger definition. they do not meet a resource's requirement because it lacks id property.

We should now decide whether CommunityGallery could do `is Azure.ResourceManager.ProxyResource` or just do `extends PirCommunityGalleryResource` from TypeSpec perspective. 

Current behavior is: .net SDK takes CommunityGallery as resource (means it has resource/data/collection) because of the above configuration, but extends PirCommunityGalleryResource.
 
If we choose `CommunityGallery is Azure.ResourceManager.ProxyResource`: .net SDK takes CommunityGallery as resource, but extends ResourceData.
 
If we choose `CommunityGallery extends PirCommunityGalleryResource`: .net SDK no longer takes CommunityGallery as resource, it becomes a normal model.

**Comment by markcowl** [comment]
Closing as duplicate
