### ISSUE TITLE
Common type replacement for Compute

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#1849]
See this [document](https://loop.cloud.microsoft/p/eyJ3Ijp7InUiOiJodHRwczovL21pY3Jvc29mdC5zaGFyZXBvaW50LmNvbS8%2FbmF2PWN6MGxNa1ltWkQxaUlXOXhaV2sxUTJSVGFqQlRRbWd4UW00dFVWQk9NbkZMTUZoV2NFOXBZVVpRYUhOblVGUm9SMUpPZEc4ME0yTXpVa3N4VFRsUmNEUlBWbkZtVlhkdlpXa21aajB3TVZWUlYwVlpVRTFHU0U5WFF6Uk1WMVphTlVGSlJWYzNURXRMVGtSUFRrOHlKbU05Sm1ac2RXbGtQVEUlM0QiLCJyIjpmYWxzZX0sInAiOnsidSI6Imh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQuY29tL3NpdGVzLzRiOGNkNTZiLTZkNDAtNGFiMy1iZWE1LTE3NDRkNGQ3M2NkZj9uYXY9Y3owbE1rWnphWFJsY3lVeVJqUmlPR05rTlRaaUxUWmtOREF0TkdGaU15MWlaV0UxTFRFM05EUmtOR1EzTTJOa1ppWmtQV0loYjNGbGFUVkRaRk5xTUZOQ2FERkNiaTFSVUU0eWNVc3dXRlp3VDJsaFJsQm9jMmRRVkdoSFVrNTBielF6WXpOU1N6Rk5PVkZ3TkU5V2NXWlZkMjlsYVNabVBUQXhWVkZYUlZsUVNVbGFWbGd6VUZSVlNETktRekpTU1RReVRWRllNa3RRUTFNbVl6MG1abXgxYVdROU1RJTNEJTNEIiwiciI6ZmFsc2V9fQ%3D%3D). Compute has its own common type. We should decide whether to replace its own common type to the one in our arm library. 

Current decision: we only replace Resource, ResourceWithOptionalLocation, userAssignedIdentities, SystemData

**Comment by markcowl** [comment]
@allenjzhang Please clarify any work for the TypeSpec team
