### ISSUE TITLE
[Bug]: incorrect paths for some routes that contain query params

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#1899]
### Describe the bug

For [this](https://github.com/Azure/azure-rest-api-specs/blob/feature/blob-tsp/specification/storage/Microsoft.BlobStorage/routes.tsp#L1812) route.

`@route("/{containerName}/{blob}?comp=appendblock")`

The `sdkMethod.operation.path` has an incorrect value: `/{containerName}/{blob}?AppendBlob/{containerName}/{blob}?comp=appendblock`

### Reproduction

Build blob storage tsp https://github.com/Azure/azure-rest-api-specs/blob/feature/blob-tsp/specification/storage/Microsoft.BlobStorage

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
i could not repro with the spec. could you upgrade to latest version to see it is resolved?

**Comment by tadelesh** [comment]
![Image](https://github.com/user-attachments/assets/64c51c4c-4bac-40a9-b607-f4be2de1b210)
from the debug screenshot, the compiler return path is already wrong. it should not be a tcgc issue.

**Comment by jhendrixMSFT** [comment]
For whatever reason, the issue no longer repros, so will not move the issue to the compiler.
