### ISSUE TITLE
[Bug]: tcgc result metadata is not being extracted correctly

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#1985]
### Describe the bug

For this tsp
```
@error
model Error {
    code: int32;
    message: string;
}
 
@pagedResult
model Bar {
    @items
    lists: string[];
    @TypeSpec.nextLink
    nextLink: string;
}
 
model Child extends Bar {
    message: string
}
 
@post
op test(): Error | Child; 
```

the itemsSegments and nextLinkSegments are correct, but the method.nextLinkPath and method.response.resultPath is empty string. 
![Image](https://github.com/user-attachments/assets/ffc840d0-b716-4e15-b04e-490573bd5abe)

### Reproduction

N/A

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
it is a bug for tcgc to handling page result with inheritance.
