### ISSUE TITLE
[Bug][TCGC] `__raw` property is null if it's an implicit discriminator property

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#201]
**Describe the bug**

Define an implicit discriminator property
```typescript
@doc("Single base model without any child model.")
@discriminator("kind")
model SingleBase {
    size: int32;
}
```

And its `__raw` property of `SdkBuiltInType` is null.
![image](https://github.com/Azure/typespec-azure/assets/4516/7dbf0d18-1a34-4e8f-b592-896fe45cb404)

**To Reproduce**
Just try to parse the definition defined above.

**Expected behavior**
Since it's primitive type, we should give a string type to `__raw` property?

**Comment by tadelesh** [comment]
All the `__raw` type is an original tsp type. For implicit discriminator property, there is no original property, so the `__raw` is `undefined`. It is by design.
