### ISSUE TITLE
[Feature Request] Add linter rule for ArmResourceActionAsync<_, _, void>

### ISSUE THREAD

**Issue by mikeharder** [Azure/typespec-azure#211]
If a spec is using `ArmResourceActionAsync<_, _, void>`, it will generate a POST with both `202` and `204` responses, which violates this linter rule:

https://github.com/Azure/azure-openapi-validator/blob/main/docs/post-response-codes.md
https://github.com/Azure/azure-openapi-validator/blob/main/packages/rulesets/src/spectral/functions/post-response-codes.ts

This can be fixed in one of two ways:

* Use the `never` type for the response, which removes the 204 (`ArmResourceActionAsync<_, _, never>`)
* Use `ArmResourceActionNoResponseContentAsync` instead of `ArmResourceActionAsync`

Either way, we think TypeSpec Linter should error on the `void` response type.

**Comment by markcowl** [comment]
est: 3

**Comment by tjprescott** [comment]
I think this is already part of the `arm-post-operation-response-codes` rule.

![image](https://github.com/Azure/typespec-azure/assets/5723682/7a354b03-959a-4106-9d14-8a9245be1220)

[Playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPukBJOQB0SBvZiBlyEDmARpwYXR0ZXJuKCJeW2EtekEtWjAtOS1dezMsMjR9JCLlAP1rZXkoIsg3xEfGF3BhdGjECHNlZ%2BQCRsojc8Ug5AHvOiBzdHLlArznAOTpAL1w6QCi8gDa6gC%2B6QC9QWfzALxhZ2U%2FOiBpbnQzMjsKxylDaXR50ipjaXR5P%2BoAjccsUHJvZmls01lAZW5jb2RlKCJiYXNlNjR1cmzlANJwxjA%2FOiBieXRlc8lIVGhlIHN0YXR1c8RLdGhlIGxhc3Qg5ADFYXRpb27lA1wgIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUD41N0YXTEX%2BUCAcwU6QFAxGvMMsV45QDCYekCK8VvQGxyb8Q7dXMKdW7kAwjRVOUBXOYBEizsAMrIRyBjcmXEJ3JlcXVlc3QgaGFzIGJlZW4gYWNjZXB0ZWTEZyAgQccOOiAiyAsi1lBpxEDkALTpAMHIROwAnDogIswP2kx1cGRhdMRPxUNVxw46ICLIC8o76QT96QDE5gDcZOcBmlN1Y2NlZWTlAMXJDNM%2FxTbkAU1mYWlsyT5GxQ06ICLGCdw4d2FzIGNhbmNlyj5Dxw%2FkBVTHC%2F8BQCBkZWxl6QGARMQN5gD5yAvkBYTvA29tb3bqAcrpA3FNb3ZlUscV6ANqxHNtb3bEaGZyb20gbG9j5gC8xW7EE%2FEDSMszdG%2FPMXRv%2BgQE5wCVc3BvbnPrBOHmAJbHFuwAl%2B4DZMU%2BxWTGfOYC7s1uaW50ZXJm5AZyT%2BgDjHMgZXh0ZW5kc%2FYHNi7LKXt9CuUHEsgjyhvLWegAzeYEq2dldOQBp0HKNVJlYWTpBZc%2BO%2BQEjOUCe09y5QKn5QHWyy9Dxx1SZXBsYWNlQXN5bmPOP%2BUC99A3UGF0Y2hTzCws8wVOxUDmAj3PQOUCOmVXaXRob3V0T2vTd2xpc3RCecgwR3JvdXDPREzFIlBhcmVudNQ8U3Vic2NyaXDlAhzGO8YzzBnMOegF%2ByBzYW1wbOsDCWFjxUR0aGF05gIG6QW%2BdG8gZGlmZmXkAITvAonFKe4AskHFSO4A7SzsAxUsIHZvaWTzAItIRUFE6gXgxHdjaGVja%2BoAo2V4aXN0ZW7mB7ggxh5FyRTvAfTNHewBAn0K&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D)

**Comment by mikeharder** [comment]
Rule `arm-post-operation-response-codes` was added on 3/20/24 (after this issue was opened), so yes I assume it covers this scenario.
