### ISSUE TITLE
[Question] How to assign a different type as key type in a Record<T>?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#216]
In tsp, `Record<T>` represents a dictionary with value type of `T` and key type is always `string`.

In real life, the `userAssignedIdentities` property in `ManagedServiceIdentity` is a dictionary: https://github.com/Azure/typespec-azure/blob/ebfe63960277356c611f15b2404a0ae6f2d9e6ed/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L390
To be more accurate, the key type of it is actually `ResourceIdentifier`, could we express this in some ways?

**Comment by timotheeguerin** [comment]
it is not possible today please see this typespec design issue https://github.com/microsoft/typespec/issues/2842

side note for typespec language issues file them in the microsoft/typespec repo. We cannot transfer them across orgs. (and in this case would be a good use case for a `Discussion` question)
