### ISSUE TITLE
[Bug] TCGC incorrectly models spread parameters

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#219]
Reference: https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/parameters/body-optionality/main.tsp#L64

TCGC models this with params `name: string` and `body: BodyModel`. My understanding is that the former should be omitted.

Playground examples showing expected behavior

https://typespec.io/playground?c=bW9kZWwgQm9keU3FCnsKICBuYW1lOiBzdHJpbmc7Cn0KCm9wIGZ1bmMoLi4uySopOiB2b2lkOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbW9kZWwgTWl4ZWRNxQt7CiAgQHBhdGgga2V5OiBzdHJpbmc7CiAgbmFtZcoQfQoKb3AgZnVuYyguLi7KQCk6IHZvaWQ7&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by iscai-msft** [comment]
This is being fixed as part of our new "spread is spread" initiative https://github.com/Azure/typespec-azure/issues/1043
