### ISSUE TITLE
[Feature Request] Allow for disabling of @typespec/http/no-service-found for Models-Only packages

### ISSUE THREAD

**Issue by l0lawrence** [Azure/typespec-azure#232]
There is a need to create a Models-Only package for EventGrid SystemEvents (as seen [here](https://github.com/Azure/azure-rest-api-specs/pull/27672)). 

While doing this generates locally - In order to get the TypeSpec Validation CI green we would need to be able to bypass the `@typespec/http/no-service-found` warning because there won't ever be any Routes in this package.

**Comment by markcowl** [comment]
@l0lawrence Can't this just be suppressed using a point suppression on the namespace?

**Comment by markcowl** [comment]
@l0lawrence Can we close this as resolved?

**Comment by l0lawrence** [comment]
Yes thank you!
