### ISSUE TITLE
[ARM]:  Support resource with multiple paths

### ISSUE THREAD

**Issue by markcowl** [Azure/typespec-azure#234]
- Create a canonical pattern for an ARM resource that can be hosted under multiple paths
  - Resources at each of these paths have the same resource schema and may have the same or different operations
  - example: PolicyDefinition (subscription, resource group)
  - Resources may also have recursive parentage (ManagementGroups)

**Comment by pshao25** [comment]
We have several (maybe we can say many) RPs in which a same resource model defined is used in different clients. For example, [this client](https://github.com/Azure/azure-rest-api-specs/blob/508e46868618ea226265c3ff8ffcda3a341cfa96/specification/web/resource-manager/Microsoft.Web/stable/2023-12-01/WebApps.json#L107) and [this client](https://github.com/Azure/azure-rest-api-specs/blob/508e46868618ea226265c3ff8ffcda3a341cfa96/specification/web/resource-manager/Microsoft.Web/stable/2023-12-01/WebApps.json#L9061) share the same resource model `Site`. 

> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}
> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/slots/{slot}

The only way we could write its TypeSpec now seems like [this](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIFNpdGUgaXMgVHJhY2tlZMh%2BPMQYUHJvcGVydGllcz7lARwuLukAnuQB0FBhcmFtZXRlcsUtLCBLZXnEFyA9ICLkAZ0iPjvoAIxFbXBsb3llZSBwyVLuAILKaukBhUFnZSBvZiBlyDvlAXphZ2U%2FOiBpbnQzMjsKxylDaXR50ipjaXR5Pzogc3Ry5QLtfQrHbukAtcVpQHBhdGjECHNlZ%2BQCvCgic2xvdHMi5AFexArNQeQBt%2BgBAE9wZXJhdOQBjAppbnRlcmbkAolXZWJBcHDmAMNnZXTkAVdByjNSZWFk5QEqPjvGIFNsb9kkLOoAqXMgPcoN5gFU&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D).

**Comment by pshao25** [comment]
https://github.com/Azure/typespec-azure/issues/1282 should be handled simultaneously.

**Comment by markcowl** [comment]
Design is here: https://gist.github.com/markcowl/825f8827d1e280a1c5ffeb57eb968677
