### ISSUE TITLE
[Bug] ResourceIdentifier doesn't not allow null/empty allowedResources

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#244]
**Describe the bug**
Currently we are unable to specify an ARM id without specifying `allowedResources`. Passing in `[]` will generate an empty allowed list which is incorrect. Extension doc [link](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-arm-id-details)

```
@doc("A type definition that refers the id to an Azure Resource Manager resource.")
@format("arm-id")
@OpenAPI.extension(
  "x-ms-arm-id-details",
  {
    allowedResources: AllowedResourceTypes,
  }
)
scalar ResourceIdentifier<AllowedResourceTypes extends ResourceIdentifierAllowedResource[] = []>
  extends string;
```

Possible solution:

- Adding `ResourceIdentifier` without template parameter as we can't conditionally skip whole decorator.

This may be coupled with another existing issue on moving `ResourceIdentifier` to `Azure.Core`, maybe as `ArmResourceIdentifier` and depprecate current one in ARM lib.

**To Reproduce**
[Playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn0KCm1vZGVsIEZvb%2BYA0y8gU2VlIGxpbmUgNTI3LCB0aGUgd2hvbGUgeC1tcy1hcm0taWQtZGV0YWlscyBzZWN05ADrc2hvdWxkIG5vdCBiZSBlbWl0dGVkCiAg6AKRSWQ66QIISWRlbnRpZmllcjxbXT47CuQAheQBSkHoAXrrAZPJQeQBTeYAqkVtcGxveWVlIGlzIFRyYWNrZWTIWjzIHFByb3BlcnRpZXM%2B6QGp5AJWIG9mIGXIQOYBn3BhdHRlcm4oIl5bYS16QS1aMC05LV17MywyNH0kIuUBgmtleSgiyDfER8YXcGF0aMQIc2Vn5ALLyiNzxSDkAnQ6IHN0cuUDQecA5OkAvXDpAKLyANrqAL7pAL1BZ%2FMAvGFnZT86IGludDMyOwrHKUNpdHnSKmNpdHk%2F6gCNxyxQcm9maWzTWUBlbmNvZGUoImJhc2U2NHVybOUA0nDGMD86IGJ5dGVzyUhUaGUgc3RhdHVzxEvkAjFsYXN0IOQAxWHkAh7lA%2BEgIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUEaFN0YXTEX%2BUCAcwU6QFAxGvMMsV45QDCYekCK8VvQGxyb8Q7dXPmA7jRU%2BUBWy4u6QND0SEs7ADfyFzkAnViZcR56QCGZWTEcCDNYtk8dXBkYXTEP8UzVccO32tkZWxldMhnRMQN2TRjcmXkANxyZXF1ZXN0IGhhxERlbiBhY2NlcMlEQccO5QQA7QKXbW92yj7pAplNb3ZlUscV6AKSxHdtb3bkAKBmcm9tIGxvY%2BUB7cZixBPxAnDLM3RvzzF0b%2FoDLOcAlXNwb25z6wQJ5gCWxxbsAJfuAozFPsVkxnzmAhbNbmludGVyZuQGH0%2FoArRzIGV4dGVuZHP2BuMuyyl7fQrlBr%2FII8oby1noAM3mA9NnZXTkAd9ByjVSZWFk6QS%2FPjvkA7TlActPcuUCJeUCDssvQ8cdUmVwbGFjZUFzeW5jzj%2FlAmrQN1BhdGNoU8wsLPMEdsVA5gJ1z0DlAn1lV2l0aG91dE9r03dsaXN0QnnIMEdyb3Vwz0RMxSJQYXJlbnTUPFN1YnNjcmlw5QIcxjvGM8wZzDnoBSMgc2FtcGzrAw1h5gacdGhhdOYCBukE5nRvIGRpZmZl5ACE7wKJxSnuALJBxUjvATfrAxTIDeYCiz7kAlM%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%5D%7D%7D)
```
    "Foo": {
      "type": "object",
      "properties": {
        "resourceId": {
          "type": "string",
          "format": "arm-id",
          "description": "A type definition that refers the id to an Azure Resource Manager resource.",
          "x-ms-arm-id-details": {
            "allowedResources": []
          }
        }
      },
      "required": [
        "resourceId"
      ]
    },
```

**Expected behavior**
```
    "Foo": {
      "type": "object",
      "properties": {
        "resourceId": {
          "type": "string",
          "format": "arm-id",
          "description": "A type definition that refers the id to an Azure Resource Manager resource.",
        }
      },
      "required": [
        "resourceId"
      ]
    },
```
**Additional context**

**Comment by markcowl** [comment]
Fixed.
