### ISSUE TITLE
[Feature Request] Introduce spread to supprt MRG V2

### ISSUE THREAD

**Issue by hemantkathuria** [Azure/typespec-azure#249]
Below one is the new type needed to support MRGV2.

https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/common-types/resource-management/v5/mobo.json
 
Further details are available here : https://armwiki.azurewebsites.net/rpaas/mrgv2.html#api-specification-update

Request to introduce a spread so that every typespec don't replicate the object.

**Comment by markcowl** [comment]
est: 3

**Comment by markcowl** [comment]
Closing in favor of https://github.com/Azure/typespec-azure/issues/1160
