### ISSUE TITLE
How to express example and title node from swagger in tsp

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#289]
Title example: https://github.com/Azure/azure-rest-api-specs-pr/blob/69142cc803bd9e4bbe0737cb0af1e25db2cc2f63/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2024-05-01/hdinsight.json#L1574
Example example: https://github.com/Azure/azure-rest-api-specs-pr/blob/69142cc803bd9e4bbe0737cb0af1e25db2cc2f63/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2024-05-01/hdinsight.json#L1675

**Comment by timotheeguerin** [comment]
`@summary` is the way to do title but looks like we are not respecting that in autorest emitter. 

https://azure.github.io/typespec-azure/playground?c=QHN1bW1hcnkoIlRpdGxlIGlzIGhlcmUiKQptb2RlbCBGT28ge30%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by timotheeguerin** [comment]
`@example` is not supported today we have an issue for it
