### ISSUE TITLE
[Bug] Casing style linting rule incorrectly reporting needing camelCasing for $filter

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#29]
I think we should exclude non-alphabet characters in casing check.

**Comment by timotheeguerin** [comment]
Should we? Shoulkdn't $filter get a nicer name instead? Like `@query("$filter) filter`?

**Comment by markcowl** [comment]
Closing as won't fix

**Comment by markcowl** [comment]
- Add a message that indicates the specific issue (non alphanumeric character) and maybe potential solutions.
