### ISSUE TITLE
Model and enum type from `getAllModels` does not have namespace

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#290]
The context is there is pushback to use TypeSpec namespace directly as client namespace, so it is not included in common types.
But it will block .NET and TypeSpec emitter.

**Comment by tadelesh** [comment]
there is no agreement across language for namespace in client

**Comment by iscai-msft** [comment]
This isn't blocking because c# and java can access the `.__raw` property 
```typescript
// Old Code
const modelNamespace = getModelNamespace(tspModel)

// New Code
for (const model of getAllModels(context)) {
  const modelNamespace = getModelNamespace(model.__raw);
}
```
