### ISSUE TITLE
Remove alias model in `getAllModels`

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#300]
We should not return alias for `getAllModels`. Current implementation could not distinguish between anonymous model and alias. Need to figure out the solution.

**Comment by tadelesh** [comment]
@iscai-msft @lmazuel @timotheeguerin 
I don't know whether the following understanding for alias model is right. Alias model is actually a syntax helper for defining an anonymous model. Each time you use it, it will be a new anonymous model. For the following TypeSpec, two `Test` in body will be convert to two different anonymous models. So, `getAllModels` should also return two models with generated name.
```
alias Test = {
  name: string;
};

@route("/one")
@put
op one(body: Test): NoContentResponse;

@route("/two")
@put
op two(body: Test): NoContentResponse;
```

**Comment by timotheeguerin** [comment]
Yeah nearly in that alias is not limited to models but any expression. It's just a way to provide a reusable expression that has not actual name in the type graph

**Comment by m-nash** [comment]
@tadelesh can you help me understand why you need to distinguish between an anonymous model that was written inline vs an anonymous model that came from an alias.  To me these don't have any unique behavior in a client library.

**Comment by tadelesh** [comment]
> @tadelesh can you help me understand why you need to distinguish between an anonymous model that was written inline vs an anonymous model that came from an alias. To me these don't have any unique behavior in a client library.

@m-nash regarding the original goal to removing alias model from `getAllModels`, this is my question. But for now, I believe we do not need to specially handle the anonymous model from alias. It is just an anonymous model and we should return it from `getAllModels` as a normal model. I think this should be a non-issue.

@iscai-msft @lmazuel  what do you think?

**Comment by timotheeguerin** [comment]
yeah you shouldn't do any special handling for model coming from alias. Alias are a concept that is internal to the typespec compiler in a sense. It shouldn't have any mapping in emitters(Exception with a few that would want to show back the original syntax like ref doc generation or api view).
