### ISSUE TITLE
Please restore mocha testing support

### ISSUE THREAD

**Issue by tjprescott** [Azure/typespec-azure#302]
I've been working on PRs to add rules after he switch from mocha to vitest and have experience a massive regression in ability to run tests efficiently.

I can no longer run all tests from the test explorer due to a bug reported here:
https://github.com/vitest-dev/vscode/issues/257

This forces me to run tests group-by-group (basically per file). However, even here, the performance of vitest is terrible and takes about 5x as long as the same run in mocha.

Some random examples (this is consistent for me regardless of the test)

#### vitest
![image](https://github.com/Azure/typespec-azure/assets/5723682/d4caaddf-b416-4e3f-8394-ed8d60bde1f7)

#### mocha
![image](https://github.com/Azure/typespec-azure/assets/5723682/b918b3a2-af52-410e-93e6-2618a2457d44)

#### vitest
![image](https://github.com/Azure/typespec-azure/assets/5723682/92f3d3db-12c5-4f4f-b5a3-b92773ee5745)

#### mocha
![image](https://github.com/Azure/typespec-azure/assets/5723682/c16dc928-e981-4019-9829-24ebf992ecbf)

#### vitest
![image](https://github.com/Azure/typespec-azure/assets/5723682/701581b5-fcbd-4425-86f6-3a187ecc91d7)

#### mocha
![image](https://github.com/Azure/typespec-azure/assets/5723682/f3cddc44-2d33-4334-817c-0d776456d505)

For both of these reasons, I ask that we restore the ability to run tests with mocha so devs can use whichever framework is most performant for their setup.

**Comment by markcowl** [comment]
unfortunately, cannot have both configurations
