### ISSUE TITLE
[Bug] isMultipartFileInput calculation logic seems incorrect in TCGC

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#308]
`bytes` could happen everywhere and compiler would not complain if it's hard to interpret bytes in emitter side.

This is from the [discussion](https://github.com/Azure/typespec-azure/pull/200/files#r1478887293). TCGC would take type as truthy isMultipartFileInput if it's bytes and in MFD operation. I was thinking the following case:
- first `bytes` is encoded with an explicit encode
- second `bytes` exists in another model under body(not in the first layer of body model)

So translating them to File would not be proper.  Maybe we could either lint them out or disable the flag as false in these cases.
```
@route("/upload") @post uploadFile(
  @header contentType: "multipart/form-data",
  @body body: {
    name: string;
    foo: {
      name: string;
      @encode("base64") 
      base64Encode: bytes;
      noEncode: bytes;
      noEncodeArrays: bytes[];
    };
  },
): void;
```
/cc @iscai-msft @lmazuel

**Comment by lmazuel** [comment]
Closing the issue, since there isn't any design issue in your particular TSP, but @MaryGao feel free to raise new issues or concerns as necessary.

**Comment by MaryGao** [comment]
Thanks for the explaination and i think `isMultipartFileInput` as false is correct to me. No concerns now.
