### ISSUE TITLE
[Bug] Azure.Core getLroMetadata result in a Model as finalResult, for a delete operation

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#31]
**Describe the bug**

**To Reproduce**
TypeSpec source (deviceupdate): https://github.com/Azure/azure-rest-api-specs-pr/blob/0788c5a7d5375a141d66f2cb82266f7c8190550d/specification/deviceupdate/Microsoft.DeviceUpdate/routes.tsp#L80-L102

compiler 0.51.0
typespec-azure-core 0.37.1

![image](https://github.com/Azure/typespec-azure/assets/53292327/f02a38bb-23a9-4c71-95a5-759c3970ddee)

This `deleteUpdate` is almost exactly same as the `importUpdate` above (while `importUpdate` would have `"void"` as `finalResult`).

**Expected behavior**

A `delete` operation have more reason to have `"void"` as `finalResult`.

**Additional context**

PS: for the standard LRO in Azure.Core [LongRunningResourceDelete](https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-core/lib/operations.tsp#L339), it does have `"void"` as `finalResult`.

**Comment by markcowl** [comment]
@weidongxu-microsoft   I believe this is because the 'delete' operation is not decorated with `@deletesResource`, which should be fixed by the upcoming PR enabling LRO support in ARM specs.

**Comment by archerzz** [comment]
> @weidongxu-microsoft I believe this is because the 'delete' operation is not decorated with `@deletesResource`, which should be fixed by the upcoming PR enabling LRO support in ARM specs.

I tried on `DevCenter` SDK the [`DeleteDevBox` operation](https://github.com/Azure/azure-sdk-assets/blob/06b6e869584dc9ad7561d5d49f4506c36cb22a15/net/sdk/devcenter/Azure.Developer.DevCenter/tests/SessionRecords/DevBoxClientTests/StartAndStopDevBoxSucceeds.json#L2313-L2319). The problem can be fixed by adding `@deletesResource(DevBox)`.

**Comment by markcowl** [comment]
closing as fixed.
