### ISSUE TITLE
[bug] `getLroMetadata` return wrong `finalStateVia`

### ISSUE THREAD

**Issue by msyyc** [Azure/typespec-azure#310]
For the [ARM LRO scenario](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPukBJOQB0SBvZiBlyEDmARpwYXR0ZXJuKCJeW2EtekEtWjAtOS1dezMsMjR9JCLlAP1rZXkoIsg3xEfGF3BhdGjECHNlZ%2BQCRsojc8Ug5AHvOiBzdHLlArznAOTpAL1w6QCi8gDa6gC%2B6QC9QWfzALxhZ2U%2FOiBpbnQzMjsKxylDaXR50ipjaXR5P%2BoAjccsUHJvZmls01lAZW5jb2RlKCJiYXNlNjR1cmzlANJwxjA%2FOiBieXRlc8lIVGhlIHN0YXR1c8RLdGhlIGxhc3Qg5ADFYXRpb27lA1wgIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUD41N0YXTEX%2BUCAcwU6QFAxGvMMsV45QDCYekCK8VvQGxyb8Q7dXPmAzPRU%2BUBWy4u6QK%2B0SEs7ADfyFzkAnViZcR56QCGZWTEcCDNYtk8dXBkYXTEP8UzVccO32tkZWxldMhnRMQN2TRjcmXkANxyZXF1ZXN0IGhhxERlbiBhY2NlcMlEQccO6QN76QKXbW92yj7pAplNb3ZlUscV6AKSxHdtb3bkAKBmcm9tIGxvY%2BUB7cZixBPxAnDLM3RvzzF0b%2FoDLOcAlXNwb25z6wQJ5gCWxxbsAJfuAozFPsVkxnzmAhbNbmludGVyZuQFmk%2FoArRzIGV4dGVuZHP2Bl4uyyl7fQrlBjrII8oby1noAM3mA9PmAadPcuUCAeUB6kHKQEPHHVJlcGxhY2VBc3luY%2BkE2iwgTHJvSGVhZGVycz1Bcm3FHslyxhk%2B5ADV&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D) with latest arm template, `getLroMetadata` shall return right `finalStateVia` with "azure-async-operation" instead of "original-uri":
![image](https://github.com/Azure/typespec-azure/assets/70930885/68f1d952-71c1-4ad5-b847-7e3b670f2776)

- Additional context:
For example, `typespec-autorest` works as expected in this scenario:
![image](https://github.com/Azure/typespec-azure/assets/70930885/eddb551b-8d37-4a7a-810c-4c443d1ca677)

**Comment by markcowl** [comment]
This is by design,  the final-state-vai for PUT operations is always original-uri
