### ISSUE TITLE
[TCGC] can't judge a property is multipart for anonymous payload 

### ISSUE THREAD

**Issue by msyyc** [Azure/typespec-azure#319]
generated code of [tsp](https://github.com/Azure/azure-rest-api-specs/blob/812012235b51ef1edf0e99f6ce9741c2c4c9df9a/specification/purview/Azure.Analytics.Purview.DataMap/routes.tsp#L767-L774) is not right:

![image](https://github.com/Azure/autorest.python/assets/70930885/5f22a4d9-ae03-4786-a363-10a7b9ac4157)

And the cadl-ranch scenario can also reproduce it:
https://github.com/Azure/cadl-ranch/pull/504/files#diff-6cd2a3081b7878b35614372bc58ebd160b688d8bc3811f4eb6797ff795829722

**Comment by msyyc** [comment]
I think it is related with https://github.com/Azure/typespec-azure/blob/ff7726fba2db9dc8ab1fa0385b7a1590b77b36bf/packages/typespec-client-generator-core/src/types.ts#L472-L476

After analysis, the root cause is related with `@typespec/http`: https://github.com/microsoft/typespec/issues/2961

**Comment by tadelesh** [comment]
fixed in https://github.com/Azure/typespec-azure/pull/395
