### ISSUE TITLE
Give a good name for templated model without `@friendlyName`

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#334]
original issue: https://github.com/Azure/typespec-azure-pr/issues/3418
1. let's get the consensus giving a non-duplicated name for templated model if there is no `@friendlyName` is a must and shall apply to all languages
2. add test case in cadl-ranch
3. get agreement for naming logic and implement in tcgc `getLibraryName`, `getAllModels` uses `getLibraryName`, so it is transitive

cc: @iscai-msft

**Comment by tadelesh** [comment]
@pshao25 could you help to explain what .NET did and link the related test here? thanks

**Comment by weidongxu-microsoft** [comment]
Java emitter would be fine, if TCGC goes with `Template<Model1, Model2>` to `TemplateModel1Model2`. (it should be fine as long as it is not just `Template` which could cause lots of duplicated names.

**Comment by pshao25** [comment]
.Net has same requirement to Java.

BTW, is `getLibraryName` expected to give the name of anonymous model?

**Comment by tadelesh** [comment]
> .Net has same requirement to Java.
> 
> BTW, is `getLibraryName` expected to give the name of anonymous model?

Nope. Anonymous model name is in the `generatedName` property of tcgc model type.

**Comment by pshao25** [comment]
I think we could have a temporary solution: if we cannot find any other overridden name, give me a flag instead of just returning its original name.
