### ISSUE TITLE
Should allow easier way to rename template parameters to maintain swagger compatibility

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#35]
A common scenario is the name of the PUT body is being named as body in swagger. To reduce brownfield onboarding diff & SDK breaking changes, we need an easier way to allow renaming particular the name on the wire.

As today, we can use workaround. The `@@projectedName` will rename the wire name while `x-ms-client-name` extension will update the client name. 

```typescript
@@OpenAPI.extension(Employees.createOrUpdate::parameters.resource,
  "x-ms-client-name",
  "body"
);
@@projectedName(Employees.createOrUpdate::parameters.resource, "json", "body");
```
This will produce:
```json
          {
            "name": "body",
            "in": "body",
            "description": "Resource create parameters.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Employee"
            },
            "x-ms-client-name": "body"
          }
```

**Comment by markcowl** [comment]
@markcowl  Create  design issue around cleaning up false breaking change issues in swagger that are real breaking change issues in DPG emission

**Comment by markcowl** [comment]
Closing in favor of the epic around breaking change rules
