### ISSUE TITLE
[Bug] Open union of float value type becomes int value type

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#353]
**Describe the bug**
```
union FloatExtensibleEnum {
    float32,
    One: 1.0,
    Two: 2.0,
    Four: 4.0,
}
```
I defined an extensible enum with type `float32`, and several values `1.0`. 

**To Reproduce**
Call https://github.com/Azure/typespec-azure/blob/53cc4dee48de3e8b774643d5946bed1f768f8609/packages/typespec-client-generator-core/src/types.ts#L800

**Expected behavior**
Value type `float32`

**Actual behavior**
Value type `int32`

**Additional context**
See this line: https://github.com/Azure/typespec-azure/blob/53cc4dee48de3e8b774643d5946bed1f768f8609/packages/typespec-client-generator-core/src/types.ts#L658

The value type comes from actual value type which becomes `1` after it reads into memory, which is originally `1.0`. Since we now have the ability to identify the real type of extensible enum as open union, we should respect the type defined in the spec, i.e. `float32`.

**Comment by lirenhe** [comment]
cc @tadelesh and @iscai-msft

**Comment by iscai-msft** [comment]
i'll look into this.
@timotheeguerin should tsp know that the type of `1.0` is a float and not an int?

**Comment by timotheeguerin** [comment]
typespec doesn't today see this isssue https://github.com/microsoft/typespec/issues/2240 you have to figure out yourself if you care
