### ISSUE TITLE
[Bug] getClientType doesn't give usage and namespace

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#354]
**Describe the bug**
For this case https://github.com/Azure/cadl-ranch/blob/228d218417abb3c73a70550b920685940195f281/packages/cadl-ranch-specs/http/type/union/main.tsp#L44 of this type `string | "b" | "c"`, when I call `getClientType`, the usage is None. The description is empty too.

**To Reproduce**

**Expected behavior**
Usage should be RoundTrip

**Additional context**

**Comment by lirenhe** [comment]
cc @tadelesh and @iscai-msft

**Comment by tadelesh** [comment]
Before you call `getClientType`, have you called `getAllModels`?

**Comment by tadelesh** [comment]
@pshao25 I'll close this for now since I could not reproduce it. If you are still meet such problem, feel free to reopen and provide more info.
