### ISSUE TITLE
[Bug] Only one type generated for two different models

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#355]
**Describe the bug**
For these two operations https://github.com/Azure/cadl-ranch/blob/228d218417abb3c73a70550b920685940195f281/packages/cadl-ranch-specs/http/type/union/main.tsp#L44 of `get` and `set`, the type `string | "b" | "c"` is involved in both input body and output body. `GetClientType` gives me only one type `GetResponseProp1` for the two models. Previously it gives me two types: `GetResponseProp1` for `get` operation, and `SendRequestProp1` for `set` operation. Please check this behavior change is expected.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by lirenhe** [comment]
cc @tadelesh and @iscai-msft

**Comment by tadelesh** [comment]
I think current logic is correct. `string | "b" | "c"` is an anonymous enum and has been used in both input and output as property.

**Comment by pshao25** [comment]
> I think current logic is correct. `string | "b" | "c"` is an anonymous enum and has been used in both input and output as property.

Then why it is named as `GetResponseProp1` not `SendRequestProp1`? Is that "first come first name"? If so I really concern about if I change the order of these two operations, would the name change?

**Comment by tadelesh** [comment]
Yes. For naming logic of anonymous model, it follows first come, first name, because it is impossible to lock the sequence of naming. But it will only happen in recsursive anonymous model.

**Comment by tadelesh** [comment]
Offline sync with @pshao25 , it is by design and there is no perfect solution. Close for now.
