### ISSUE TITLE
[Bug] ARM Library: Patch does not generate Updatable model for complex envelope types

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#383]
**Describe the bug**
Seeing one onboarding team hitting PatchBodyParametersSchema lintDiff. The root cause is this resource includes ManagedServiceIdentity from common type definition which type property is marked as required. Our auto update model generation does not seem to extend to the common types but still $ref to its original definition. As original definition contains `required` properties thus triggering this warning.

**To Reproduce**
[Playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPukBJOQB0SBvZiBlyEDmARpwYXR0ZXJuKCJeW2EtekEtWjAtOS1dezMsMjR9JCLlAP1rZXkoIsg3xEfGF3BhdGjECHNlZ%2BQCRsojc8Ug5AHvOiBzdHLlArwKICAuLi7mASNkU%2BYCUUlkZW50aXR5O%2BgBAukA23DpAMDyAPjqANzlANsuLi5VcGRhdGVhYmzLHDxPcHRpb25hbMsT1n4%2BPuUAnuQAgFRoZSBzdGF0dXPkASl0aGUgbGFzdCDEQWHETuUDJSAgQHZpc2liaWxpdHkoInJlYWTlAPBw5AG25wOsU3RhdGU%2FOukDduUB0swc5QDz5AJWyCJPyGRzCmludGVyZuQDKOgA8%2BYA6nXlAOfkAfdByjhQYXRjaFN5bmPpAfws8wEqPsRw&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%2C%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%2C%22%40azure-tools%2Ftypespec-azure-core%2Fcanonical-versioning%22%2C%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D)

**Expected behavior**
In update model, as we are starting to master the properties in TypeSpec models, we should stop generating $ref to original common definitions but generate an update model locally.

**Comment by markcowl** [comment]
[Here is one solution](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPukBJOQB0SBvZiBlyEDmARpwYXR0ZXJuKCJeW2EtekEtWjAtOS1dezMsMjR9JCLlAP1rZXkoIsg3xEfGF3BhdGjECHNlZ%2BQCRsojc8Ug5AHvOiBzdHLlArwKICAuLi7mASNkU%2BYCUUlkZW50aXR5O%2BgBAlBhdGggcmVxdWVzdCBib2R5IGZvcuoA8fEBA1VwZGF0ZeUA4i4uLvYBjkZvdW5kYXTlAYVBcm1UYWdz5wEeeeUAlsR4xUhhYmxl5wMVZCDnAvMgaecAo8R8IMkOPzog9gDKxUllyVhSUC3kBBhpZmljIHDGdWll5QLHIMsQPzrpANHqAbjlARTmAO7ca%2BQAlXMgT3DkAOBhbMo%2FPMYf5ADUyxX%2FASJuc%2BgBochlyjw%2BPucDmekBju4A0e4Bmco46QJ%2FQWfzAn5hZ2U%2FOiBpbnQzMukBNUPkAW%2FRKmPmAXfrAk%2FELFByb2ZpbNNZQGVuY29kZSgiYmFzZTY0dXJs5QKUcMYwPzogYnl05AFlx0hUaGUgc3RhdHVzxEt0aGUgbGFzdCDkAMXlARnlBR4gIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUFpVN0YXTEX%2BUDw8wU6QLkxGvMMsV45QDCYekD7cVvQGxyb8Q7dXMKdW7kBMrRVOkBXFN1Y2Nlc%2BcCWcUNZWRlZDogIskMIizoAOtGYWlsdXLnASfEDcUpxgnKJkNhbmNlbGzlAP3GK8YSxS3IC8ov5ADV6QSqaXMgYmXkANrpAOdlZMZE7ADCOiAizA%2FaTHXkAsrET8VD5QLYxj9Vb8YL2jvmAIdkZWxldOgAg0TEDcZAyAvXQGNyZeQBZOgEj2hhxFBlbiBhY2NlcMlQQccOOiAiyAvGUOYCqukF3ekDN21vdspV6QM5TW92ZVLHFegB1uQAjm1vduQAw2Zyb20gbG9j6wGQxBPxAxDLM3RvzzF0b8ov9wCVc3BvbnPrBWjmAJbHFuwAl%2B4DLMU%2BxWTGfOYCts1uaW50ZXJm5Af8T%2BgDVHMgZXh0ZW5kc%2FYIwC7LKXt9CuUInMgjyhvLWegAzeYEc2dldOQCAkHKNVJlYWTpByE%2BO%2BQEVOUB4k9y5wZHzi9Dxx1SZXBsYWNlQXN5bmPOPy8v5gKc0DpQYXRjaFPMLyzzBRnFQ%2BYCm89A5QKYZVdpdGhvdXRPa9N6bGlzdEJ5yDBHcm91cM9ETMUiUGFyZW501DxTdWJzY3Jp5QY4xzvGM8wZzDnoBcYgc2FtcGzrAydhY8VEdGhhdOYCCekFiXRvIGRpZmZl5ACE7wKMxSnuALJBxUjvATfrAxfIDeYCjvMAkkhFQUTqBbLEfmNoZWNr6gCqZXhpc3RlbuYJTCDGHkXJFO8B%2Fs0d7AEJfQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D) tat teams can use until this is fixed

**Comment by konrad-jamrozik** [comment]
Here is a discussion about `PatchBodyParamterSchema` rule:
- https://github.com/Azure/azure-sdk-tools/issues/7771

**Comment by petrkotas** [comment]
Hi @markcowl thank you for the solution, I have tried in the PR https://github.com/Azure/azure-rest-api-specs-pr/pull/18316. Unfortunately without luck. I have two properties `HcpOpenShiftClusterResource` and `HcpOpenShiftNodePoolResource`, I tried to apply the variant as is proposed here for HcpOpenShiftClusterNodepoolResource, it game me additional error of identity not in the right place. For both resources, the original error `PatchBodyParameterSchema` remained. 

May I ask for further suggestions?

**Comment by markcowl** [comment]
@petrkotas sent a PR to your branch with a fix

**Comment by pratyush-prateek** [comment]
Hello @markcowl 

We are onboarding as a new resource provider on RPaaS and the rule `PatchBodyParametersSchema` is failing for us as well. The PATCH request body is getting generated automatically for us where the request body parameters are marked as required. Due to that, the rule `PatchBodyParametersSchema` is getting failed for us. Could you provide a solution for this in the documentation for passing CI checks?

Our PR - https://github.com/Azure/azure-rest-api-specs-pr/pull/18659

**Comment by markcowl** [comment]
Fixed.
