### ISSUE TITLE
The properties id and name of ArmResource in typespec are in-consistant with their definition in swagger

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#401]
The properties id and name of ArmResource in typespec are required, but they are optional in swagger. And it caused breakings in JS. Also the required and readOnly limitations for input models are conflicting with between. How could customers feed a required param but readonly?

- swagger https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json#L14-L29
- typespec https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L23-L32

This is from the [dicssion](https://github.com/Azure/typespec-azure/issues/131#issuecomment-1988428974).

**Comment by allenjzhang** [comment]
From schema correctness perspective, `required` and `read` signify the properties are always available and only settable by service. You are guaranteed not to have null values. It is pretty clear and concise. The loose definition of the common-type swagger definition is not exactly right or helpful in generating good Client SDK models.

@MaryGao, can you elaborate on your scenario this is breaking? If this is for PATCH, the update model based on ARM op template will automatically strip out read only properties.

**Comment by allenjzhang** [comment]
#762
