### ISSUE TITLE
[Feature Request] Automatically add endpoint parameter if user doesn't define it

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#415]
**Is your feature request related to a problem? Please describe.**
Some customers don't define endpoint in their spec. This is an [example](https://github.com/bterlson/typespec-todo/blob/e962a20b5fb8baf3bf9d0f025912c93c591da4f9/main.tsp#L9-L14).

**Describe the solution you'd like**
TCGC might automatically add this endpoint parameter if there is not one.

**Describe alternatives you've considered**

**Additional context**

**Comment by lmazuel** [comment]
Makes total sense to me, we should do it
