### ISSUE TITLE
nextLink property should not be marked `readOnly: true`

### ISSUE THREAD

**Issue by mikekistler** [Azure/typespec-azure#418]
A recent change in TypeSpec Azure adds `readOnly: true` to the `nextLink` property in a pageable list response. 

`readOnly: true` is meaningless on a property of a response-only schema, and pageable list responses are always response-only -- they are never part of a request body.

We should not be including meaningless attributes in the OpenAPI that is generated from TypeSpec.

**Comment by markcowl** [comment]
@mario-guerra  There is a current discussion about this with differing opinions, can you coordinate coming to consensus?

**Comment by mikekistler** [comment]
Capturing a workaround shared in email:
> There is a one-line change to a spec that will update the visibility of these types across the whole spec:
> ```
> @@visibility(Azure.Core.Page.nextLink)​
> ```
>  [as shown in this playground](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.github.io%2Ftypespec-azure%2Fplayground%3Fc%3DaW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%252B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPukBJOQB0SBvZiBlyEDmARpwYXR0ZXJuKCJeW2EtekEtWjAtOS1dezMsMjR9JCLlAP1rZXkoIsg3xEfGF3BhdGjECHNlZ%252BQCRsojc8Ug5AHvOiBzdHLlArznAOTpAL1w6QCi8gDa6gC%252B6QC9QWfzALxhZ2U%252FOiBpbnQzMjsKxylDaXR50ipjaXR5P%252BoAjccsUHJvZmls01lAZW5jb2RlKCJiYXNlNjR1cmzlANJwxjA%252FOiBieXRlc8lIVGhlIHN0YXR1c8RLdGhlIGxhc3Qg5ADFYXRpb27lA1wgIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUD41N0YXTEX%252BUCAcwU6QFAxGvMMsV45QDCYekCK8VvQGxyb8Q7dXPmAzPRU%252BUBWy4u6QK%252B0SEs7ADfyFzkAnViZcR56QCGZWTEcCDNYtk8dXBkYXTEP8UzVccO32tkZWxldMhnRMQN2TRjcmXkANxyZXF1ZXN0IGhhxERlbiBhY2NlcMlEQccO6QN76QKXbW92yj7pAplNb3ZlUscV6AKSxHdtb3bkAKBmcm9tIGxvY%252BUB7cZixBPxAnDLM3RvzzF0b%252FoDLOcAlXNwb25z6wQJ5gCWxxbsAJfuAozFPsVkxnzmAhbNbmludGVyZuQFmk%252FoArRzIGV4dGVuZHP2Bl4uyyl7fQrlBjrII8oby1noAM3mA9NnZXTkAd9ByjVSZWFk6QS%252FPjvkA7TlActPcuUCJeUCDssvQ8cdUmVwbGFjZUFzeW5jzj%252FlAmrQN1BhdGNoU8wsLPMEdsVA5gJ1z0DlAn1lV2l0aG91dE9r03dsaXN0QnnIMEdyb3Vwz0RMxSJQYXJlbnTUPFN1YnNjcmlw5QIcxjvGM8wZzDnoBSMgc2FtcGzrAw1hY8VEdGhhdOYCBukE5nRvIGRpZmZl5ACE7wKJxSnuALJBxUjvATfrAxTIDeYCi%252FMAkkhFQUTqBQ%252FEfmNoZWNr6gCqZXhpc3RlbuYG5yDGHkXJFO8B%252B80d7AEJ5AKI7AVl6gkqLlBhZ2UubmV4dExpbmspOwo%253D%26e%3D%2540azure-tools%252Ftypespec-autorest%26options%3D%257B%257D&data=05%7C02%7Cmikekistler%40microsoft.com%7C99b6c1a5a25d40389dc608dc4ac4274b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638467453547925566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=AUGPhsKy41ao5QbrmxMcxtxtQjwPgpGTpH1qDG3CSUc%3D&reserved=0)

**Comment by mario-guerra** [comment]
@mikekistler can this issue be closed?

**Comment by mikekistler** [comment]
Fixed by #549
