### ISSUE TITLE
[Feature Request] String property decorated with format: arm-id should use Azure.Core.ResourceIdentifier

### ISSUE THREAD

**Issue by abatishchev** [Azure/typespec-azure#427]
**Is your feature request related to a problem? Please describe.**

Given a property on the model, such as:

https://github.com/Azure/azure-rest-api-specs/blob/1d9bdf047d98fb6844ce9309301ca719c1cc003d/specification/common-types/resource-management/v5/customermanagedkeys.json#L42

```json
"userAssignedIdentityResourceId": {
  "type": "string",
  "format": "arm-id",
  "description": "User assigned identity to use for accessing key encryption key Url. Ex: /subscriptions/fa5fc227-a624-475e-b696-cdd604c735bc/resourceGroups/<resource group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myId. Mutually exclusive with identityType systemAssignedIdentity."
}
```

**Describe the solution you'd like**
It should produce a C# model with a property of type [Azure.Core.ResourceIdentifier](https://learn.microsoft.com/en-us/dotnet/api/azure.core.resourceidentifier?view=azure-dotnet)

```c#
[JsonProperty("userAssignedIdentityResourceId")]
public Azure.Core.ResourceIdentifier UserAssignedIdentityResourceId { get; set; }
```

**Describe alternatives you've considered**

The model may contain both propreties:

```c#
[JsonProperty("userAssignedIdentityResourceId")]
public string UserAssignedIdentityResourceId { get; set; }

[JsonIgnore]
public Azure.Core.ResourceIdentifier UserAssignedIdentityResourceIdentifier =>
    new Azure.Core.ResourceIdentifier(UserAssignedIdentityResourceId);
```

**Comment by markcowl** [comment]
This would require taking an Azure.Core dependency in generated service code, it is out of scope for the current emitter.
