### ISSUE TITLE
[Bug] TypeSpec for CustomerManagedKeyEncryption in Common Type v5 mismatches with corresponding Swagger spec

### ISSUE THREAD

**Issue by abatishchev** [Azure/typespec-azure#428]
**Describe the bug**

CustomerManagedKeyEncryption in Common Type v5 defines both Guid properties as **non-nullable**:

```json
"federatedClientId": {
  "type": "string",
  "format": "uuid",
  "description": "application client identity to use for accessing key encryption key Url in a different tenant. Ex: f83c6b1b-4d34-47e4-bb34-9d83df58b540"
},
"delegatedIdentityClientId": {
  "type": "string",
  "format": "uuid",
  "description": "delegated identity to use for accessing key encryption key Url. Ex: /subscriptions/fa5fc227-a624-475e-b696-cdd604c735bc/resourceGroups/<resource group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myId. Mutually exclusive with identityType systemAssignedIdentity and userAssignedIdentity - internal use only."
}
```

https://github.com/Azure/azure-rest-api-specs/blob/1d9bdf047d98fb6844ce9309301ca719c1cc003d/specification/common-types/resource-management/v5/customermanagedkeys.json#L42-L53

So does this repo's replica:

https://github.com/Azure/typespec-azure/blob/b10f51eb365962e60674b38f1aca6aa09f68519c/packages/samples/specs/resource-manager/common-types/v5/customermanagedkeys.json#L42-L53

But the corresponding TypeSpec spec defines one of the values as **nullable**:

https://github.com/Azure/typespec-azure/blob/b10f51eb365962e60674b38f1aca6aa09f68519c/packages/typespec-azure-resource-manager/lib/customer-managed-keys.tsp#L39-L43

**Expected behavior**

`federatedClientId` must be redefined as just `federatedClientId: uuid`.

_or_

The Common Types should be updated, what I don't think the case.

**Comment by abatishchev** [comment]
+ @weshaggard who made the original change: https://github.com/Azure/typespec-azure/commit/8b8d7c05f168d9305a09691c4fedcb88f4a57652

**Comment by abatishchev** [comment]
However, looking at the discussion on the original PR for adding the model to Common Types v4: From https://github.com/Azure/azure-rest-api-specs/pull/20144/files#r940546434 and then at the ARM RPC ([legacy public version](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-contracts.md#customer-managed-key-encryption), it's the **opposite** (sort of):

- `federatedClientId` is present (but has default value "")
- `delegatedIdentityClientId` is not present

**Comment by markcowl** [comment]
@abatishchev  GUID is a struct, so if it is not marked as required in Swagger (and none of these properties are), they should all be `GUID?`, then the service type at least would be resilient over versions

**Comment by abatishchev** [comment]
I'd be happy to submit a PR to mark the other one nullable too
