### ISSUE TITLE
LintDiff violation for 204 response from ArmResourceActionNoContentAsync

### ISSUE THREAD

**Issue by cataggar** [Azure/typespec-azure#439]
In https://github.com/Azure/azure-rest-api-specs-pr/pull/17524, I attempted to move to use `ArmResourceActionNoContentAsync`.

```
restrictMovement is ArmResourceActionNoContentAsync<VirtualMachine, VirtualMachineRestrictMovement>;
```

This generated these responses:
``` json
        "responses": {
          "202": {
            "description": "Resource operation accepted.",
            "headers": {
              "Retry-After": {
                "type": "integer",
                "format": "int32",
                "description": "The Retry-After header can indicate how long the client should wait before polling the operation status."
              },
              "Location": {
                "type": "string",
                "description": "The Location header contains the URL where the status of the long running operation can be checked."
              }
            }
          },
          "204": {
            "description": "Action completed successfully."
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse"
            }
          }
        },
```

LintDiff then complains about the `204` response code, sayding:

> PostResponseCodes, RPC-Async-V1-11, RPC-Async-V1-14
Long-running POST operations must have responses with 202 and default return codes. They must also have a 200 return code if only if the final response is intended to have a schema, if not the 200 return code must not be specified. They also must not have other response codes.

**Comment by markcowl** [comment]
This is by design. The recommendation is to use `ArmResourceActionNoResponseContentAsync` or to simply use `ArmResourceActionAsync` with a `never` response type.
