### ISSUE TITLE
[ARM] Use common-type {scope} parameter for extension resource path param {resourceUri}

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#44]
Currently we hardcode extension resource path parameter as local `resourceUriParameter`. The convention ARM has been using is `{scope}` which was added as global ref `ScopeParameter` in  v4 and v5. This has produced different swagger content. I am confirming with language SDK teams on code impact.

Adding following common type declaration produces correct reference when correct version is selected.
```
packages/typespec-azure-resource-manager/lib/parameters.tsp#93

  @armCommonParameter("ScopeParameter", Azure.ResourceManager.CommonTypes.Versions.v4)
  @armCommonParameter("ScopeParameter", Azure.ResourceManager.CommonTypes.Versions.v5)
  resourceUri: string;

=>
-              "$ref": "#/parameters/Azure.ResourceManager.ResourceUriParameter"
+             "$ref": "../../../../../../../../../specs/resource-manager/common-types/v5/types.json#/parameters/ScopeParameter"
```

However, since v3 does not support this, compilation fails for specs reference v3 common-type. 

I propose we remove this check and when cooresponding version not found, produce as it is `{resourceUri}`. This could allow us flexibility on switching this since small number of TypeSpec has used this.

@daviwil

**Comment by markcowl** [comment]
est: 2

**Comment by daviwil** [comment]
Not sure how easy it will be to implement the fix for this issue, but I'll look into it!

**Comment by allenjzhang** [comment]
An easy workaround `@@path(ResourceUriParameter.resourceUri, "scope");` does work partially that setting the name in the Parameter. However the path `{resourceUri}` is unchanged.

Treating this an autorest emitter bug to fix that.

**Comment by allenjzhang** [comment]
With this fix, following code will restore full backcompat with `/{scope}/` and `ref: .../ScopeParameter`

```
@@path(ResourceUriParameter.resourceUri, "scope");
@@Azure.ResourceManager.Private.armCommonParameter(ResourceUriParameter.resourceUri,
  "ScopeParameter",
  Azure.ResourceManager.CommonTypes.Versions.v5
);
```
