### ISSUE TITLE
typespec-autorest does not honor @clientName 

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#442]
See: https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtY2xpZW50LWdlbmVyYXRvci1jb3JlIjsKdXNpbmcgQcQzLkPFJEfIIy5Db3JlOwoKQMY8TmFtZSgiVGVzdFJlbmFtZSIpCmVudW0gxBJ7CiBBLAogQgp90y9Nb2RlbMk0bcQOxTXFGCB7CiAgcHJvcDE6IHN0cmluZwp9&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D

**Comment by timotheeguerin** [comment]
This was partially by design that the only thing it support was what it supported with `@projectedName` and we just wanted parity. However it would probably make sense to expand the usage.

**Comment by markcowl** [comment]
+1, we should either add x-ms-client-name or change the schema name, since it isn't actually part of the API

**Comment by tadelesh** [comment]
Previously, we have `@projectedName("client", "xxx")` to rename the type in swagger with `x-ms-client-name`. So my idea is do the same thing for `@clientName`.

**Comment by timotheeguerin** [comment]
That didn't work on the model name [See playground](https://azure.github.io/typespec-azure/playground?c=QHByb2plY3RlZE5hbWUoImNsaWVudCIsICJCYXIiKQptb2RlbCBGb28ge30%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D), that is my point, we only kept parity.

**Comment by tadelesh** [comment]
> That didn't work on the model name [See playground](https://azure.github.io/typespec-azure/playground?c=QHByb2plY3RlZE5hbWUoImNsaWVudCIsICJCYXIiKQptb2RlbCBGb28ge30%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D), that is my point, we only kept parity.
> 
> but I don’t have anything against adding more cases

Oh, I see. Thanks for explanation.

@markcowl then we should add both `@extension("x-ms-client-name", "xxx")` and `@clientName("xxx")` to keep client generated from swagger and tsp to be the same.

**Comment by timotheeguerin** [comment]
Why soupy need to add x-ms-client-name on the model, we should just change the definition name

**Comment by tadelesh** [comment]
> Why soupy need to add x-ms-client-name on the model, we should just change the definition name

Model name is ok to change name directly. But properties renaming need to keep backward compatible.

**Comment by tadelesh** [comment]
Oh. I see. Thanks for the explanation.

**Comment by tadelesh** [comment]
For model/enum/interface/union renaming, since it is not an API info, we should just rename the name. For parameters/properties renaming, we should use @clientName.

**Comment by timotheeguerin** [comment]
Confused here @tadelesh, don’t we need this? The point was more that autorest should rename the definition not add x-Ms-client-name

**Comment by tadelesh** [comment]
Oh, I got your point. My view is from convert swagger to TypeSpec, so I think we don't need to add @clientName, instead just rename the name. From autorest emitter view, the requirements are:
1. for name that is used in wire, @clientName emit with x-ms-client-name
2. for name that is not used in wire, @clientName change the swagger definition name directly

**Comment by markcowl** [comment]
The consensus is to update typespec-autorest to honor `@clientName` in more cases:

For Models:
  `@clientName` should change the schema name
For Enums and Unions
  `@clientName` should change the schema name and the `x-ms-enum` `name` field

**Comment by timotheeguerin** [comment]
other thing it should change is the body parameter name and `x-ms-client-name` for path and query
