### ISSUE TITLE
typespec-autorest could not ref to the defined enum

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#450]
See [example](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=bW9kZWwgVGVzdCB7DQogIHdpdGhvdXREZWZhdWx0OiBLaW5kID3FBy5BOw0KfQ0KDQplbnVtxhrFNEEsxAZCxQZDDQp9&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D).

The property with default value of enum could not ref to the defined enum, instead will redefine a new one with default.

**Comment by markcowl** [comment]
You cannot use $ref with openapi2 defaults

**Comment by tadelesh** [comment]
Since m4 will merge enum. This should be a non-issue.
