### ISSUE TITLE
typespec-autorest emitter could not handle discriminated model with multi inherence layer

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#458]
See [example](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=ZW51bSBBbmltYWxUeXBlew0KICBEb2csxAhDYXQNCn0NCg0KQGRpc2NyaW1pbmF0b3IoImtpbmQiKQ0KbW9kZWzHPyDFPMQaOstRIMdCzCpXaXRoU2hhcmRQcm9wZXJ0aWVzIGV4dGVuZHPNTGRlxHVwdGlvbjogc3RyaW5nzU5Eb2fPONRa9QCXLkRvyEzITkNhdM9O1ztDYXQ7DQp9&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D).

**Comment by markcowl** [comment]
This is specifically out of scope, given that this project is only fixing critical bugs

**Comment by tadelesh** [comment]
It is used by green field rp, which is one of the reasons the service refused to use TypeSpec.

**Comment by tadelesh** [comment]
It is used in one of the green field service though they have already abandoned to use TypeSpec. I believe we need to give a solution for it.

**Comment by timotheeguerin** [comment]
This works with openapi3 and is understood by the `getDiscriminatorUnion` compiler helper so this is just a bug in autorest emitter which doesn't make use of this.
