### ISSUE TITLE
TCGC usage calculation revisit

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#460]
Revisit current calculation logic since .NET and Java has some extra logic.

Java's requirements:
- [x] Usage calculation should consider visibility
If a model is only used in a read-only property, despite the property from a round trip model, the model should be labeled with usage input.
- [x] Body model of patch method with "application/merge-patch+json" content type should be excluded when usage calculation. But patch method with "application/json" content type should not. Finished with https://github.com/Azure/typespec-azure/pull/455
- [ ] Method with multiple content types should be excluded when usage calculation.

.NET requirements:
- [x] Same as Java 2
- [ ] Same as Java 3

**Comment by iscai-msft** [comment]
@tadelesh is visibility still a requirement? I think there's some design that needs to happen there, we shouldn't just directly add visibility to `Usage`, I'm not sure that's the right course of action

**Comment by tadelesh** [comment]
> @tadelesh is visibility still a requirement? I think there's some design that needs to happen there, we shouldn't just directly add visibility to `Usage`, I'm not sure that's the right course of action

talked with java and .net folks, we all agree to keep current impl. after typespec has native visibility support, we could change the logic.


close this issue since no further asks about usage.
