### ISSUE TITLE
[Dt] Service CodeGen: Service Emitter Specification & Test Suite

### ISSUE THREAD

**Issue by markcowl** [Azure/typespec-azure#527]
- Test Suite to exercise the required functionality for
  - Model Emitters
  - Operations Interfaces
  - Http Routing

**Comment by allenjzhang** [comment]
To clarify, for this epic, we would like to have an E2E Cadl-ranch like testing infrastructure to exercise different specs with manually or generated client to ensure scenarios working. 

For expected generated artifacts such as models, code, it is best handled in package testing or samples.
