### ISSUE TITLE
Limitation for tsp to handle operation id from swagger

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#55]
For tsp, interface name could not be same with the model name, meanwhile, interface name will be recognized as operation id for SDK and generated swagger. However, for some RP, model name is same with the operation id, see [example](https://github.com/Azure/azure-rest-api-specs/blob/d1eb3c20113d1018f25a8d97fdfa5f8bb5c659ea/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/preview/2023-10-03-preview/HybridCompute.json#L1728).

Two possible solutions:
1. use `@projectedName` to rename interface, but current `typespec-autorest` does not honor `@projectedName`.
2. introduce another new decorator in `typespec-azure-resource-manager` to identify operation id for each operation.

I prefer 2.

**Comment by markcowl** [comment]
@tadelesh  The correct thing to do here is to use the client name projection to set the operationId

[Here is a sample showing the OperationId changing when the client projected name of the interface is changed](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ9Ufb3BlbmFwacwcYXp1cmUtdG9vbHMvyCgtxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAMXIG0HEZS5Db3JlzhJSx3dNxnbRSk9wZW5BUEk7CgpAYXJtUHJvdmlkZXJOYW1lc3BhY2UKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zb8guSHViQ2xpZW50IiwKICDnAWE6ICIyMDIxLTEwLTAxLXByZXZpZXciLAp9KQpAZG9jKMhFIOgAoiDITyDmASJtZW50IEFQSS4iKQpAdXNlRGVwZW5kZW5jeSj1ANvoARVzLnYxXzBfUMZyXzEp5QDaQ29tbW9u5AD3c8co10bLKctSNSkKbugBFCBNaWNyb3NvZnQu8gEJ5AFJ5QDfQSDSHSDoAgUiKQptb2RlbCBFbXBsb3llZSBpcyBUcmFja2Vk6ACRPMgcUHJvcGVydGllcz4g5AGGxmDkAaMgb2YgZccmIinEG3BhdHRlcm4oIl5bYS16QS1aMC05LV17MywyNH0kxiNrZXkoIsg2xEbJOmjECHNlZ%2BQBesojc8Ug5AD%2BOiBzdHLlAnR96ADm6QDAcOkApfEA3OoAwOsAv0Fn8gC%2BYWdlPzogaW50MzI7CskqQ2l0edErY2l0eT%2FqAJDJLVByb2ZpbNJbQGVuY29kZSgiYmFzZTY0dXJsxRdwxi8%2FOiBieXRlc8ZJdmlzaWJpbGl0eSgicmVhZMZBxV9UaGUgc3RhdHVzxGJ0aGUgbGFzdCDkAOBhdGlvbuQCrMVWxETlA6BTdGF0xGDlAgbMFOsBRcRWzDTFY%2BUAxGHpAjLEWkBscm%2FEPHVzCmVudW3SVOUBYC4u6QLU0SEs6gEqxHXIXeQCfmJlxHrpAIdl5gD3zELbPXVwZGF05AVTxDRVxw3fbWcgZGVsZXTHaUTEDNs1Y3Jl5ADhcmVxdWVzdCBoYcRFZW4gYWNjZXDIRUHHDSzkAVxpbnRlcmbkA7BP6AGfcyBleHRlbmRz9gUd5AUNyCl75AGecHJvamVjdGVk5AMnKCJj5wTlIOkC9%2BQBlWFybchIykDLfsgs5gL%2BZ2V05AEBQco1UmVhZOkD7D475ALd5QDsT3LlAUnlATDLL0PNHUFzeW5jzj7lAYzQNlBhdGNoU8wsLPMDoMVA5gGWz0DlAZ9lzUHFLWxpc3RCecgmR3JvdXDPOkzFIlBhcmVudNQ8U3Vic2NyaXDkATfHO8YzzBnMOX0K&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)
