### ISSUE TITLE
[TCGC][Bug] getAllModels, Optional literal do not have correct generated name

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#553]
**TSP definition:**
```tsp
model Model {
  literal: "literal";
  optionalLiteral?: "optionalLiteral";
}
```

**Java code:**
In Java's generated code, we will generate an enum for the `optionalLiteral`, the enum is called `ModelOptionalLiteral`, like below. I guess this optional literal is like anonymous model, and will need TCGC to generate a correct name for it.
```java
public enum ModelOptionalLiteral {
    /**
     * Enum value optionalLiteral.
     */
    OPTIONAL_LITERAL("optionalLiteral");

    /**
     * The actual serialized value for a ModelOptionalLiteral instance.
     */
    private final String value;

    ModelOptionalLiteral(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ModelOptionalLiteral instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed ModelOptionalLiteral object, or null if unable to parse.
     */
    public static ModelOptionalLiteral fromString(String value) {
        if (value == null) {
            return null;
        }
        ModelOptionalLiteral[] items = ModelOptionalLiteral.values();
        for (ModelOptionalLiteral item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}

```

Discussed with @tadelesh offline, TCGC does not handle the name for it currently. It is better if TCGC can handle it.
@archerzz  @pshao25 Does `.Net` have this behavior? What will .Net generate for optional literal?

**Comment by iscai-msft** [comment]
i think this is something we can add. The root of the difference is java and .net want constants returned as single-value enums, while js and python will keep it as a single value constant.

We should have an input to tcgc that allows you to toggle this behavior. If an enum is returned in this case, we will automatically return a generated name `ModelOptionalLiteral` as well. To confirm, do .net and java want this enum to be fixed?

**Comment by haolingdong-msft** [comment]
Hey @iscai-msft , thanks for the confirmation, for Java, it is fixed enum.

**Comment by tadelesh** [comment]
@pshao25 could you help confirm .net behavior?

**Comment by pshao25** [comment]
We are extensible enum currently, but it is very subject to change. So we don't have any request for TCGC for now.

**Comment by haolingdong-msft** [comment]
This is for model properties only. If it is on header or query parameters, we will use `string` directly.

**Comment by iscai-msft** [comment]
the difference is right now, the `constant` type doesn't have a name property on it. 

It makes sense to add this behavior in tcgc though, where we add `.name` and `.isGenerated` onto constants. This way languages (like .net and java) who would like to generate an enum / object for constants have a name to go off of

For now, I would say this isn't a blocker for tcgc adoption. You can keep your current code that comes up with a name for these constants (worst case you need to look into `SdkConstantType.__raw` to build the name for that constant).
