### ISSUE TITLE
Resource type has key property same with the parent

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#56]
Example: Resource type 'ProvisionedCluster' has a key property named 'default' which conflicts with the key name of a parent or child
This is happening as we have 2 'default' in few of our [API paths](https://github.com/Azure/azure-rest-api-specs-pr/blob/837a592fba321281578323101f3c3ca1447eedf2/specification/hybridaks/resource-manager/Microsoft.HybridContainerService/stable/2024-01-01/provisionedClusterInstances.json#L200). For example: `{connectedClusterResourceUri}/providers/Microsoft.HybridContainerService/provisionedClusterInstances/default/upgradeProfiles/default`.

**Comment by markcowl** [comment]
@tadelesh This is not conflict, it is a parent singleton resource with a child that is also a singleton.  [Here is a sample of how this pattern should be modeled](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgpAYXJtUHJvdmlkZXJOYW1lc3BhY2UKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zb8guSHViQ2xpZW50IiwKICDnAS06ICIyMDIxLTEwLTAxLXByZXZpZXciLAp9KQpAZG9jKMhFIOgAiiDITyDmAQptZW50IEFQSS4iKQpAdXNlRGVwZW5kZW5jeSj1AMPoAP1zLnYxXzBfUMZyXzEp5QDaQ29tbW9u5AEpc8co10bLKctSNSkKbugBFCBNaWNyb3NvZnQu8gEJ5AFJ5QDfQSDSHSDoAe3kANPkAY1sZXRvbgptb2RlbCBFbXBsb3llZSBpcyBUcmFja2Vk6ACcPMgcUHJvcGVydGllcz4g5AGRxmvkAa4gb2YgZccmIinEG3BhdHRlcm4oIl5bYS16QS1aMC05LV17MywyNH0kxiNrZXkoIsg2xEbJOmjECHNlZ%2BQBhcojc8Ug5AEJOiBzdHLlAmd96ADx6QDAcOkApSIp7wDc6gDA6wC%2FQWfyAL5hZ2U%2FOiBpbnQzMjsKySpDaXR50StjaXR5P%2BoAkMktUHJvZmls0ltAZW5jb2RlKCJiYXNlNjR1cmzFF3DGLz86IGJ5dGVzxkl2aXNpYmlsaXR5KCJyZWFkxkHFX1RoZSBzdGF0dXPEYnRoZSBsYXN0IOQA4GF0aW9u5AK3xVbEROUDk1N0YXTEYOUCEcwU5gFFcGFyZW506AHzKOgBM%2FMCKkRlZmF1bHRDaGlsZOQCLlByb3h5yDk8e330AhxkxjQgY8Q1%2FwIh7wIhxzvFb%2FsCJcwncmVu%2FAIr5AE87AEa5QFJ5QCnYekDI%2BUD92xyb%2BQBInVzCmVudW3yATrlAOkuLukDxdEhLOoCEMR1yF3kATZiZcR66QCHZeYBFsxC2z11cGRhdOQGEMQ0VccN321nIGRlbGV0x2lExAzbNWNyZeQA4XJlcXVlc3QgaGHERWVuIGFjY2VwyEVBxw0s5AFcaW50ZXJm5AShT%2BgChXMgZXh0ZW5kc%2FYF9i7LKXvkAZ5hcm3II8oby1noApXmA79nZXTkANxByjVSZWFk6QStPjvkA57lAMdPcuUBJOUBC8svQ80dQXN5bmPOPuUBZ9A2UGF0Y2hTzCws8wRhxUDmAXHPQOUBemXNQcUtbGlzdELpA0hHcm91cM86TMUiUOUDqdQ8U3Vic2NyaXDkATfHO8YzzBnMOe0BtugD10jmA0H8AWPIK%2BQDbP8A6eYA6c8xfQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by markcowl** [comment]
Closing as fixed, please reopen if there are additional issues
