### ISSUE TITLE
Incorrect corresponding method param for Azure.Core.MaxPageSizeQueryParameter

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#580]
### Describe the bug

The corresponding method param for Azure.Core.MaxPageSizeQueryParameter is incorrect. It should map to an entry in `sdkMethod.parameters` but it appears to map back to itself.

### Reproduction

Using tcgc `0.41.0-dev.42`

Build https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/payload/pageable/main.tsp

In `sdkMethod.operation.parameters` the entry for the `maxpagesize` query param doesn't map back to the entry in `sdkMethod.parameters`.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jhendrixMSFT** [comment]
After some discussion, it sounds like we might want tcgc to explose these core types?

**Comment by iscai-msft** [comment]
Yeah, we want to explose these, and I don't think most emitters want this parameter. If this is still an issue can you reopen @jhendrixMSFT ? Thanks!
