### ISSUE TITLE
[Bug]: typespec-azure-resource-manager and typespec-azure-core still uses enum

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#584]
### Describe the bug

https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L435-L451

https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-core/lib/foundations.tsp#L17-L33

If they are open enum, it should be written as union.
see https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/06types

### Reproduction

SDK emitters would deprecate `@fixed` and interpret typespec `enum` as closed enum. That require all open enum written as `union` in core libs and spec repo.

[playgroud](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7CskfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLlJlc3Q70BVIdHRw0RVWyXLIG0HEWS5Db3JlLlRyYWl0czsKCkBzZXJ2aWNlKHt0aXRsZTogIlRleHQgYXV0aG9y5ACufSkKQOcAvWVkKFPGLsdccykKbmFtZXNwYWNlIMQ4Qcg3OwoKZW51bSDPMCB7CiAgQHVzZURlcGVuZGVuY3ko6wCWyCcudjFfMF9QcmV2aWV3XzIpCiAgdjE6ICIyMDIxLTDEAyIsCn0KCmludGVyZsR9UmVzb3VyY2VPcGVyYXTERAogIGV4dGVuZHPsAPjSKDxOb1JlcGVhdGFibGVSZXF1ZXN0cyAmIE5vQ29uZGnEJGFszhhsaWVudMcTSWQ%2BIHt95wDuSW5saW7KXFN0YXRl5gDzZG9jKCJUaGUgb8gdIGhhcyBub3Qgc3RhcnRlZC4i5ADnTm90U8YQLArXOGlzIGluIHByb2dyZXNzxjdSdW7kAenZNMRsY29tcGxldGVkIHN1Y2Nlc3NmdWxsecZAU8QSZWTbdsRCZmFpbOgAqUbFDN0vYmVlbiBjYW5jZWxlZCBieSB0aGUgdXNlcsZCQ8ca5QHKQHLnAZkoInByb2plY3RzIikKbW9kZWwgUMYR5gFJa2V5xAd2aXNpYmlsaXR5KCJyZWFkxVJpZDogc3TmAn8gIGRlc2NyaXDkAI8%2FyhgKICDkArPNEXN0YXR1czrsAihGb3VuZOYCIS7uAdDLMjI69QHyO%2B4Cm%2BkDFOUAwWxpc3TkAcPyAonpApxMaXN0POcA9T7ETQ%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)
typespec-autorest still interpret it as open enum `"modelAsString": true`.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
This was done by design to give one sprint migration help to in flight teams. If we made the change immediately users spreading our enums(now unions) would have received errors that are much more confusing than the current warning with a codefix.

**Comment by weidongxu-microsoft** [comment]
Thanks Timothee.

I can understand that the behavior of typespec-autorest is to provide this one sprint migration time.

However, without the change of enum -> union in core libs, SDK emitter would had to wait for the completion of core lib change, before itself do the change (it had to take `enum` as open enum, till core lib done the migration).

I am fine with the SDK emitter wait for next sprint. It just that some language emitter already switched, hence there be some inconsistency between emitters.

**Comment by timotheeguerin** [comment]
Yeah we should not see any bare enums (apart from the ones in the typespec lib) as the linting rule to ban those is in. 
The behavior for this sprint is:
- use `@fixed` to be explicit if you want a fixed enum
- use open union
- no unannotated enum

next sprint:
- remove `@fixed`

**Comment by weidongxu-microsoft** [comment]
Thanks Timothee. Got it, then emitter would switch in next sprint as well. You can close the issue.

**Comment by weidongxu-microsoft** [comment]
@markcowl 
The one in typespec-azure-core still is `enum` https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-core/lib/foundations.tsp#L17-L33

And devcenter uses it https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devcenter/DevCenter/DevBox/models.tsp#L733

**Comment by weidongxu-microsoft** [comment]
Attempt a PR here https://github.com/Azure/typespec-azure/pull/851

**Comment by weidongxu-microsoft** [comment]
There are a few other `enum`s in ARM lib, e.g. https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/common-types/types.tsp#L112-L125

Are they supposed to be `union` as well?
