### ISSUE TITLE
Investigate and fix visibility of properties bag in ARM  resource templates

### ISSUE THREAD

**Issue by markcowl** [Azure/typespec-azure#589]
At least one RP is showing an issue due to the default visibility of the 'properties' bag in ARM resource templates. ("read", "create").  Details are [here](https://teams.microsoft.com/l/message/19:5aaa7fae6eae4b6b9bae42e5295c10a3@thread.tacv2/1711656264257?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=9a661795-1b01-4a5b-9dd5-be571422334c&parentMessageId=1711656264257&teamName=Azure%20CLIs%20partners&channelName=Azure%20CLI%20CodeGen&createdTime=1711656264257): 

- [x] Investigate the impact of changing the visibility setting on RPaaS implementations
- [x] Consider a non-breaking update that would set the visibility to "read", "create", "update" for new specs.

**Comment by allenjzhang** [comment]
#650

**Comment by markcowl** [comment]
**Describe the breaking change**
Updates the visibility of ARM properties bags so that properties are updatable.  This will remove `x-ms-mutability` extension form the properties bag in generated swagger.  This was previously discussed and approved by Jeffrey and Mike. 

The reason for the change is to allow true representations of resources in generated SDKs, to allow Azure CLI generated Update commands to update RP-specific properties, and as a prerequisite to allowing PATCH modeling to be parallem with Azure.Core PATCH templates, which is an important ask for MPG.

**Back-compat design to avoid immediate breaking**
Visibility augment decorators can be used to mimick existing x-ms-mutability

**Link to detailed breaking design**
Link:

**Impact**
This change affecting:

- [x] ARM
- [ ] Data-plane
- [x] Existing specs: all
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: June

**Additional information**
Will add link to typespec-next PRs here:

**Comment by markcowl** [comment]
Completed
