### ISSUE TITLE
List operation with additional response property

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#59]
Current list operation template could not customize response model. Lots of brown field RPs have additional property for the response list model, [example](https://github.com/Azure/azure-rest-api-specs/blob/d1eb3c20113d1018f25a8d97fdfa5f8bb5c659ea/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/definitions.json#L4093). Instead of define a raw operation, is it possible to enhance the template?

**Comment by allenjzhang** [comment]
Added Template parameters to allow override.
