### ISSUE TITLE
How to convert swagger with batch config to TSP

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#60]
Example:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/postgresql/Azure.ResourceManager.PostgreSql/src/autorest.md?plain=1#L15
https://github.com/Azure/azure-rest-api-specs/tree/eca38ee0caf445cb1e79c8e7bbaf9e1dca36479a/specification/postgresql/resource-manager

**Comment by allenjzhang** [comment]
Do we need to support batch?

I guess this would be a SDK generation issue. If both versions have been mastered in TypeSpec, with MPG in place, my understanding is language SDKs (like .NET or Python) should handle the versions seamlessly. This would be an requirement for MPG, is it not?
If the two versions are discret in TypeSpec (say preview & stable), wouldn't we need to rely on TCGC to amalgamate the two still?

**Comment by allenjzhang** [comment]
Do we need to support batch?

I guess this would be a SDK generation issue. If both versions have been mastered in TypeSpec, with MPG in place, my understanding is language SDKs (like .NET or Python) should handle the versions seamlessly. This would be an requirement for MPG, is it not?
If the two versions are discret in TypeSpec (say preview & stable), wouldn't we need to rely on TCGC to amulgumate the two still?

**Comment by markcowl** [comment]
I think this is essentially the same thing as this: https://github.com/Azure/typespec-azure/issues/106

**Comment by markcowl** [comment]
- we should nto convert specs like this
