### ISSUE TITLE
[Bug]: missing-x-ms-identifiers misleading messages

### ISSUE THREAD

**Issue by mjlshen** [Azure/typespec-azure#604]
### Describe the bug

https://github.com/Azure/typespec-azure/blob/94c846a3b19095e623bcb35521412f85388078a9/packages/typespec-azure-resource-manager/src/rules/missing-x-ms-identifiers.ts#L19-L20 suggests the use of `@extension("x-ms-identifiers", [<prop>])`, however the actual decorator should be `@OpenAPI.extension("x-ms-identifiers", [<prop>])`

https://azure.github.io/typespec-azure/docs/libraries/azure-resource-manager/rules/missing-x-ms-identifiers

### Reproduction

https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZaHR0cMwZYXp1cmUtdG9vbHMvyCUtxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuUmVzdDvQFUh0dHDIFUHESi5Db3JlzhJSx1xNxls7CgpAc2VydmljZSgiV2lkZ2V0xxoiKQpuYW1lc3BhY2UgQ29udG9zby7NIjsKCm1vZGVsIEFkZHJlc3MgewogIGNpdHk6IHN0cmluZzsKIMQKZWV0yhJ9yDXoAIlQcm9wZXJ0aWXGQGFycmF5OshTW10KfQo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
The former does work if you have `using OpenAPI;` but we could use the fully qualified name in the message to reduce confusion
