### ISSUE TITLE
How to deal with cross package resource or models reference

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#62]
Example of resource which parent resource is in another package:
singleton resource from recovery service backup: https://github.com/Azure/azure-rest-api-specs/blob/80c21c17b4a7aa57f637ee594f7cfd653255a7e0/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/bms.json#L21C6-L21C6
its parent resource is from recovery service: https://github.com/Azure/azure-rest-api-specs/blob/d1eb3c20113d1018f25a8d97fdfa5f8bb5c659ea/specification/recoveryservices/resource-manager/Microsoft.RecoveryServices/stable/2023-08-01/vaults.json#L377
How should we model such resource? Another situation is some package is using another package's model definition, shall we import the `models.tsp` from another package? (Do not have real example for now)

**Comment by markcowl** [comment]
I think this is out of scope.  RecoveryServices is a single RP, and should be represented with a single package (or, perhaps, not converted as it is an outlier on this).

We could always use low-level APIs, so this should not block conversion, putting the benefits of converting this spec into question.
