### ISSUE TITLE
[Bug]: incomplete crossLanguageDefinitionId

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#629]
### Describe the bug

In some cases, the value for `crossLanguageDefinitionId` is incomplete. It shows up as `Azure.ResourceManager.Foundations.`. Note The trailing `.` with no type name.

### Reproduction

Using tcgc 0.42.0-dev.3

Generate https://github.com/Azure/autorest.go/tree/main/packages/typespec-go/test/tsp/ApiCenter.Management

For type `ErrorAdditionalInfoInfo`, note that the value for `crossLanguageDefinitionId` is `Azure.ResourceManager.Foundations.`

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
It is happened in anonymous model. I changed the logic with using generated name from tcgc.
