### ISSUE TITLE
Resource type is enum

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#63]
These two RPs use an enum to abstract a group of similar resources. I wonder what is the best way to model them in TSP.
[example](https://github.com/Azure/azure-rest-api-specs/blob/48a49f06399fbdf21f17406b5042f96a5d573bf0/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L30C106-L30C106)

**Comment by markcowl** [comment]
This could only be represented by low-level APIs.  This will not be supported by TypeScript templates because it is an anti-pattern.
