### ISSUE TITLE
[Bug]: SdkEnumType.crossLanguageDefinitionId can be undefined

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#632]
### Describe the bug

The definition of `SdkEnumType.crossLanguageDefinitionId` states that it's not optional, but it's been observed that in some cases it's `undefined`. If this is expected, then the field should be defined as optional.

### Reproduction

Using tcgc 0.42.0-dev.3

Generate https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/union/main.tsp

For synthesized enum type `EnumsOnlyCasesLr` the field `crossLanguageDefinitionId` is undefined.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
It is happened in union as enum without naming. I changed the logic with using generated name from tcgc.
