### ISSUE TITLE
@clientName empty string support

### ISSUE THREAD

**Issue by l0lawrence** [Azure/typespec-azure#645]
Is it possible to have `@clientName(blah, "")` treat `blah` as if generating an anonymous model? 

I have the following scenario where in the existing TypeSpec there are 4 similar models `XXOptions` that all currently contain a singular `lock_tokens` parameter:
```
  @action("acknowledge")
  op acknowledgeCloudEvents is StandardOperations.ResourceAction<
    EventSubscription,
    {
      @doc("AcknowledgeOptions.")
      @body
      acknowledgeOptions: AcknowledgeOptions;
    },
    AcknowledgeResult
  >;

model AcknowledgeOptions {
    lock_tokens: string[];
}

```

and I would like to be able to use @clientName on `acknowledgeOptions` as such:

```
@clientName(AcknowledgeOptions, "")
```

so the resulting operation that generates would parse out the parameters of AcknowledgeOptions

`@@clientName(AcknowledgeOptions, "", "python")` 

`def acknowledge_cloud_events(self, topic_name, event_subscription_name, *, lock_tokens, **kwargs)`

**Comment by markcowl** [comment]
dupliacte of #659
