### ISSUE TITLE
[Bug]: Block clientName to be empty string

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#647]
### Describe the bug

Should raise a diagnostic that it's not allowed

### Reproduction

```typescript
import "@azure-tools/typespec-client-generator-core";

using Azure.ClientGenerator.Core;

@clientName("")
model Foo {}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lmazuel** [comment]
@timotheeguerin suggested something like:
```
if(arg === "") {
  reportDiagnostic(program, {
    code: "client-name-blank",
    target: context.getArgumentAtIndex(0)
  })
}
```

**Comment by timotheeguerin** [comment]
I would also suggest checking for a whitespace string not just empty string
