### ISSUE TITLE
[Bug]: `x-ms-mutability` issue to support CreateOrUpdate scenario in PUT operation

### ISSUE THREAD

**Issue by kairu-ms** [Azure/typespec-azure#650]
### Describe the bug

The swagger genereated from TypeSpec set RP `properties` mutability by ["read", "create"] which block the update command generation of Azure CLI and PowerShell. Azure CLI and PowerShell use Put operation to update the resources.

### Reproduction

This issue is reported in this [teams channel](https://teams.microsoft.com/l/message/19:5aaa7fae6eae4b6b9bae42e5295c10a3@thread.tacv2/1711656264257?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=9a661795-1b01-4a5b-9dd5-be571422334c&parentMessageId=1711656264257&teamName=Azure%20CLIs%20partners&channelName=Azure%20CLI%20CodeGen&createdTime=1711656264257)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by allenjzhang** [comment]
resolved dup of #589
