### ISSUE TITLE
[Feature Request] Adding ARM v6 common-type support

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#653]
### Clear and concise description of the problem

ARM has just released V6 common-type definition, we need to update TypeSpec ARM library before being widely adopted by specs.

Diff is small:

- Added `nextLink` in `PrivateEndpointConnectionListResult` and `PrivateLinkResourceListResult`

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
@allenjzhang Currently there are only a small number of types in v6.  Need to understand why this is here and when it will be required.

**Comment by markcowl** [comment]
Fixed this release
