### ISSUE TITLE
[tcgc] add @makeModelAnonymous decorator

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#659]
### Clear and concise description of the problem

We want the ability to say that we actually want to treat a defined model as an anonymous model, as something that is more of a convenient grouping than an actual logical grouping

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lmazuel** [comment]
We may want to call it `@spreadModel` to be more clear about the intent. Technically, this feature only value is that we know Python will spread it, and it may be too indirect to be clear.

**Comment by msyyc** [comment]
How about `@spreadAsAlias`? Since Python will spread the parameters only when model is anonymous (that is `alias`).

**Comment by tadelesh** [comment]
I prefer `@madeAnonymous`. The root logic for TCGC to do spread is whether the effective model is anonymous. I don't want to add a special logic to set any model used with spread as anonymous model.

**Comment by weidongxu-microsoft** [comment]
Just `@@clientName(model, "", "python")` :-) ?

Joke aside. If this is for the operation to flatten its request body, why not just this?
```ts
@flattenRequestPayload
op clientMethod is Service.Interface.ServiceOp;
```

Not sure if we still want to do TOM. TOM may want to use `@serviceOperation` as
```ts
@serviceOperation(Service.Interface.ServiceOp)
op clientMethod(modelProp1, modelProp2, modelProp3);
```

**Comment by jsquire** [comment]
@iscai-msft:  Can you add some examples of what the TypeSpec and resulting client generation are intended to look like with and without the proposed change?   I don't have historical context and there's not enough in the issue that I'm following the proposal.  Thanks!

**Comment by iscai-msft** [comment]
No need for this anymore since we're going ahead with "spread is spread"
