### ISSUE TITLE
[docs] Include install steps for azure-rest-api-specs repo

### ISSUE THREAD

**Issue by mikeharder** [Azure/typespec-azure#672]
The install steps currently recommend manually installing the latest versions of all packages:

https://github.com/Azure/typespec-azure/blob/dd9907ce0d65c08fcdad976b6a066cc7cbb0fd46/docs/getstarted/installation.md#L19

Users working in repo `azure-rest-api-specs[-pr]` should instead run `npm ci` to install the package versions specified in `/package-lock.json`.

**Comment by markcowl** [comment]
est: 1
