### ISSUE TITLE
[Bug][TCGC]: Incorrect `discriminator` value of discriminator property if it's union type

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#676]
### Describe the bug

See `DocumentIntelligence`. There is a union `OperationKind` defined as discriminator type: https://github.com/Azure/azure-rest-api-specs/blob/6fc313ed7a6e926d4409d4ddb435f6532922652f/specification/ai/DocumentIntelligence/models.tsp#L272

It's used as type of the discriminator of `OperationDetails`: https://github.com/Azure/azure-rest-api-specs/blob/6fc313ed7a6e926d4409d4ddb435f6532922652f/specification/ai/DocumentIntelligence/models.tsp#L1227

`OperationDetails` has a few child models. However, when TCGC parses those models, value of `discriminator` property of `DocumentModelBuildOperationDetails.kind` is false.
![image](https://github.com/Azure/typespec-azure/assets/4516/dd0fa467-1d53-4855-b60f-d21cb1719842)

### Reproduction

Just parse the tsp definition in the links above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
It is another circular calculation issue.

**Comment by archerzz** [comment]
Looks like the `context.modelsMap` fails to find the value from the given key:
![image](https://github.com/Azure/typespec-azure/assets/4516/160f09c6-dbd6-4e86-b05c-01133ee0ebb7)

The map has a `Pet` model as key, but the passed-in model `Pet` cannot match it.
