### ISSUE TITLE
System data definition is different from swagger

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#679]
TypeSpec definition for `createdAt`: https://github.com/Azure/typespec-azure/blob/daa3b1559b9e6f082456b6ce0867f52fc36af924/packages/typespec-azure-resource-manager/lib/common-types/types.tsp#L347
Swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/b5512186602fbe490d273aab7ebddc21f8e7f855/specification/common-types/resource-management/v5/types.json#L527

**Comment by markcowl** [comment]
@markcowl link to common-types updates issue

**Comment by tadelesh** [comment]
cc: @allenjzhang

**Comment by pshao25** [comment]
I suppose the expected type is `utcDateTime`? BTW, the document is different too. We should make them same too.

**Comment by allenjzhang** [comment]
fixed in pending PR #945
