### ISSUE TITLE
[Bug]: Inconsistencies between v5/types.json and typespec

### ISSUE THREAD

**Issue by dolauli** [Azure/typespec-azure#681]
### Describe the bug

By utilizing the emitter typespec-autorest, we have the capability to transform typespec into swagger 2. In the case of the generated swaggers, they will incorporate certain shared definitions from v5/types.json. However, there exist discrepancies between types.json and typespec, encompassing aspects such as naming conventions, readonly properties, required fields, descriptions, and more. For a comprehensive understanding of these inconsistencies, please refer to the following link: https://github.com/Azure/azure-rest-api-specs/pull/28717. This pull request outlines the necessary changes to ensure the consistency of types.json with typespec. 

Except for above, there is another one, which is in typespec, there is an empty model https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L40, while in swagger, we do not have this model.

And we will need to fix those inconsistencies either in typespec or in swagger.

### Reproduction

To find those inconsistencies, you just need to refer to my drafted pr to find those typespec types in https://github.com/Azure/typespec-azure/tree/main/packages/typespec-azure-resource-manager/lib.

**Note:** If the decorator @friendlyName is specified, the frendlyName will be used.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
Closing in favor of the issues above
