### ISSUE TITLE
[Bug]: `rpc-operation-request-body` rule is reporting false positive when using with `@get` and empty params

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#684]
### Describe the bug

Rule is reporting an error when you don't actually set any params as you pass `{}`

### Reproduction

[playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIEh0dHA7xwxWyUvIEkHEMi5Db3JlOwoKQHVzZUF1dGgoxRZBcGlLZXnEEGVudGljYXRpb24pCkBzZXJ2aWNlxS1EZXBlbmRlbmN5xjPFSS7HZnMudjFfMF9QcmV2aWV3XzIpCm5hbWVzcGFjZcd3VGVzdMR3ZG9jKCJBIGRhdGEgc3RyZWFtLiIpCm1vZGVsIE1lc3NhZ2VEYXRhU8UbIHsKICBAYm9kecQIxTtUaGXHOCDEGMQ9IMUKOiBieXRlczsKxCtoZWFkZXLUNWNvbnRlbnQg5AFIxj3HElR5cGU6ICJhcHBs5wEBL29jdGV0LcY5IjsKfQoKaW50ZXJm5ADW5gChT3BlcsUsc%2BYAq3RhZygixhvFXMZ%2FRG93bmxvYWQgdGhlIE1lZGlhIHBhecUSZnJvbSBhIFVzZXIgdG8gQuQBqmVzcyBt5gEL5gCiQHJvdXRlKCLHFXMv5gCTc8UdZ2V0xlNpcyBScGPpAJI8e30s8gFSPuQAxw%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%5D%7D%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tjprescott** [comment]
Same with `@delete`.
