### ISSUE TITLE
[Bug][getAllOperations]: alias model is not calculated

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#69]
**Describe the bug**
- If a normal anonymous model is defined, it will be given a name in TCGC.
- If an anonymous model is defined through alias, it won't be given a name.

I found that usage of alias model is not calculated as well. It's always `None`.

**To Reproduce**
Try to compile the test case using `getAllOperations` branch: https://github.com/Azure/autorest.csharp/blob/31e7b662d82c01fa8e6725437c1daa2227a2aeb8/test/TestProjects/Spread-TypeSpec/Spread-TypeSpec.tsp#L97-L101

**Expected behavior**
Anonymous model defined by an alias should be calculated.

**Comment by iscai-msft** [comment]
we shouldn't be returning models that are aliases, so if anything we need to make sure that we're not returning aliases

**Comment by tadelesh** [comment]
> we shouldn't be returning models that are aliases, so if anything we need to make sure that we're not returning aliases

Current `getAllModels` will return alias model. I don't remember clearly if it is because after compiling, we could not distinguish a model type is from model or alias definition.

**Comment by tadelesh** [comment]
follow up with tsp team to see how to separate them.

**Comment by tadelesh** [comment]
Folk the alias problem into another issue: https://github.com/Azure/typespec-azure/issues/300

**Comment by tadelesh** [comment]
This issue is likely a usage calculation problem. Will investigate soon.

**Comment by iscai-msft** [comment]
closing in favor of #300
