### ISSUE TITLE
[Bug] wrong return type for LRO delete

### ISSUE THREAD

**Issue by msyyc** [Azure/typespec-azure#691]
context: https://github.com/Azure/autorest.python/issues/2531
For typespec https://github.com/Azure/azure-rest-api-specs/blob/71a0c7adf2a6e169ab9a33c7cf36bb93db083e86/specification/deviceregistry/DeviceRegistry.Management/assetEndpointProfiles.tsp#L146, TCGC return wrong type instread of `None`
![image](https://github.com/Azure/autorest.python/assets/70930885/093d3a67-aef8-4528-85fe-37c0e2cbbc20)

**Comment by tadelesh** [comment]
We have a PR trying to fix it in TCGC, however, we are not sure when to use `finalResult` when to use `logicResult`. The doc is not clear to azure core lib.

**Comment by msyyc** [comment]
If we can't fix it in short time, as workaround, we may enforce return type of delete to void by default (e.g. java [did](https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java#L438-L440))

**Comment by msyyc** [comment]
fixed by https://github.com/Azure/typespec-azure/pull/559
