### ISSUE TITLE
[Bug][TCGC 0.41.4]: discrminiator property type usage should be `RoundTrip` 

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#723]
### Describe the bug

See this test case in `autorest.csharp`: https://github.com/Azure/autorest.csharp/blob/d58078ea0825133656ba7854024428658ea0586d/src/TypeSpec.Extension/Emitter.Csharp/test/Unit/modelType.test.ts#L125
`Pet` is used as both input and output. Its usage should be `RoundTrip`. The usage of the type of its discriminator property `kind` should be `RoundTrip` as well.

But after upgrading from TCGC `0.41.3` to `0.41.4`, the usage of the type of `kind` is `None`.
Here is the test case: https://github.com/Azure/autorest.csharp/blob/d58078ea0825133656ba7854024428658ea0586d/src/TypeSpec.Extension/Emitter.Csharp/test/Unit/modelType.test.ts#L207
Here is the test error
![image](https://github.com/Azure/typespec-azure/assets/4516/ff0ff180-d329-421f-b32f-03db439889f6)

As you can see, now TCGC calculates the usage to be `None`.

### Reproduction

Just try to parse the test case above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
TCGC's result is `Input | Output`. Could you please double check .NET logic?

**Comment by archerzz** [comment]
> TCGC's result is `Input | Output`. Could you please double check .NET logic?

Looks like the `context.modelsMap` fails to find the value from the given key:
![image](https://github.com/Azure/typespec-azure/assets/4516/160f09c6-dbd6-4e86-b05c-01133ee0ebb7)

The map has a `Pet` model as key, but the passed-in model `Pet` cannot match it.

**Comment by tadelesh** [comment]
Versioning projection issue. You need to use `context.program.projector` to get projected type after you call `navigateTypesInNamespace`.
