### ISSUE TITLE
[Bug][TCGC 0.41.4]: `@clientName` not work 

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#730]
### Describe the bug

Try a TypeSpec spec including `@clientName`, like: https://github.com/Azure/azure-rest-api-specs/blob/2897e4040dd3d922061ae55bc002358aeaded619/specification/devcenter/DevCenter/client.tsp#L166

In the generated codes, `@clientName` is not honored. See this preview gen from csharp: https://github.com/Azure/azure-sdk-for-net/pull/43608

Looks like for some reason, the decorator value is not correctly saved: 
![image](https://github.com/Azure/typespec-azure/assets/4516/bc709219-12bd-4a78-b49f-4aac56fc1556)

### Reproduction

Just try the above TypeSpec spec.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lirenhe** [comment]
@iscai-msft  / @tadelesh ,  could you help to resolve this with priority?  Seems it blocks our codegen to move to the latest version of TCGC.

**Comment by tadelesh** [comment]
Regression of versioning support for this issue: https://github.com/Azure/typespec-azure/issues/233. I've fixed it.
