### ISSUE TITLE
[TCGC] design discussion on support ServiceVersion in Client

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#746]
### Clear and concise description of the problem

.NET and Java need to generate [`ServiceVersion` in client](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning-select-api-version). It may not be same as the list of api-versions in main.tsp.

A default list of ServiceVersion could be the api-versions at or before `api-version` in emitter options.

For instance, by default,
```ts
enum ApiVersions {
  v2023_04_01: "2023-04-01",
  v2023_10_01_preview: "2023-10-01-preview",
  v2024_02_01: "2024-02-01",
  v2024_03_01_preview: "2024-03-01-preview",
}
```
and tspconfig `api-version=2023-10-01-preview` would mean the list be `2023-04-01 + 2023-10-01-preview`

A stable `api-version` would filter stable api-versions, e.g. tspconfig `api-version=2024-02-01` implies the list be `2023-04-01 + 2024-02-01`

### Real service example

OpenAI targets latest i.e. `2024-04-01-preview`
ServiceVersion enum would contain prior api-versions.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/OpenAIServiceVersion.java

### Alternative

Use `SdkClientType.apiVersions`. Map this list to language `ServiceVersion`. If emitter need additional filtering, do this in language emitter.

---

Below likely not need to be covered now.

There could be a case that service wants to override this default list.

One possible solution is e.g. a decorator in client.tsp, for example:
```ts
model ClientOptions {
  ...

  @clientLevelParameter
  @serviceVersion
  serviceVersion: ServiceVersion;
}

enum ServiceVersion {
  v2023_04_01: "2023-04-01",
  @defaultServiceVersion
  v2024_02_01: "2024-02-01",
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by weidongxu-microsoft** [comment]
Another potential case is that typespec can allow multiple `@service` with different list of api-versions. Current emitter option cannot handle this.

**Comment by lmazuel** [comment]
The multiple `@service` is not a priority today, as this is against Azure guidelines (we refuse service teams to do it, and forced them to publish a new unifided version of their RestAPI for instance).

I agree this is important to be able to project on a non-contigous subset of api-versions.

@iscai-msft @tadelesh I wonder if for an input like `2023-04-01,2024-02-01", we could loop through the list, project all of them to get all program (here we would get two program: 2023 and 2024), and merge back those programs (the final program is the sum of both programs). What do you think?

**Comment by weidongxu-microsoft** [comment]
Here in this issue, the main design issue is whether TCGC would include the `ServiceVersion` model in its types.

The projection part could wait for future need. E.g. for now, we are good just project to `2023-04-01`, and generate ServiceVersion of only 1 value `2023-04-01`. A similar situation is just project to `2024-02-01` (as long as service does not do breaking changes, this project should cover prior stable versions as well), and generate ServiceVersion of 2 values `2023-04-01` + `2024-02-01`.

**Comment by tadelesh** [comment]
For current TCGC behavior, the projection will not affect `Version` model. Whether you set any version, it will return the full list, and the root cause is the version model for TypeSpec will not do projection. I agree we could do some filtering for the `Version` model according to azure specific rule.

**Comment by weidongxu-microsoft** [comment]
After discussion with Chenjie, there is 2 more considerations (that could be language-specific).

1. The name of the ServiceVersion class. From doc, .NET and TypeSpec would use name as `ServiceVersion`. Java would use a prefixed name like `DevCenterServiceVersion` (the name itself it not an issue, but it would get affected by point 2, if client have different list of ServiceVersion).
2. Whether we allow different list of ServiceVersion in different client. E.g. if a client is added in `2024-02-01`, should the `ServiceVersion` of this client contain only `2024-02-01`.

**Comment by tadelesh** [comment]
Some thoughts:
1. Current TCGC's type `SdkClientType` has `apiVersions` property which should be the list for language to construct the `ServiceVersion` enum.
2. Versions enums for each service need to filter version according to version projection like weidong said, and it's better to pair them to the `SdkClientType` I think.
3. `getDefaultApiVersion` should take version projection into consideration.

**Comment by tadelesh** [comment]
Some decision:
1. For the version enum defined for service api version, tcgc will do filtering.
2. All client's `apiVersions` property will do filtering.
3. `getDefaultApiVersion` will do filtering.

@MaryGao after fix, you could get right api version with `getDefaultApiVersion`.
@weidongxu-microsoft since each service will have different api version set, you should use `apiVersions` property in `SdkClientType` to generate your own `ServiceVersion` model/enum. that property will be filtered with api version configured.

**Comment by weidongxu-microsoft** [comment]
@tadelesh 

Java would use a single ServiceVersion for all client (for Azure of single `@service`).
Even if the client does not exist in V1, it would still accept a same ServiceVersion.

There is discussion of whether we would allow service to clearly specify which version to include, e.g. via
```
@serviceVersion(ApiVersion.v2023_04_01);
@serviceVersion(ApiVersion.v2024_02_01);
```
But I guess that be another issue.

**Comment by tadelesh** [comment]
> @tadelesh
> 
> Java would use a single ServiceVersion for all client (for Azure of single `@service`). Even if a new client did not exist in V1, it would still accept a same ServiceVersion.
> 
> There is discussion of whether we would allow service to clearly specify which version to include, e.g. via
> 
> ```
> @serviceVersion(ApiVersion.v2023_04_01);
> @serviceVersion(ApiVersion.v2024_02_01);
> ```
> 
> But I guess that be another issue, as this one closed.

i believe it should be a new feature for tcgc. you could open another issue to discuss.

**Comment by weidongxu-microsoft** [comment]
see https://github.com/Azure/typespec-azure/issues/865
