### ISSUE TITLE
[tcgc] `isFinished` calculation issue

### ISSUE THREAD

**Issue by chunyu3** [Azure/typespec-azure#756]
When a body of an operation which use operation template, and the body type is alias and contains generic type property, tcgc does not calculate the correct `isFinished` for this body type.
Face service met with this problem,  the spec is https://github.com/Han-msft/azure-rest-api-specs/tree/hachiang/face-typespec/specification/ai/Face

```
@returnsDoc("A successful call returns an array of the most similar faces represented in faceId if the input parameter is faceIds or persistedFaceId if the input parameter is faceListId or largeFaceListId.")
@sharedRoute
@post
@route("findsimilars")
op FindSimilarOperation<T extends TypeSpec.Reflection.Model> is Azure.Core.RpcOperation<
  {
    @doc("faceId of the query face. User needs to call \"Detect\" first to get a valid faceId. Note that this faceId is not persisted and will expire 24 hours after the detection call.")
    faceId: uuid;

    @doc("The number of top similar faces returned. The valid range is [1, 1000]. Default value is 20.")
    @minValue(1)
    @maxValue(1000)
    maxNumOfCandidatesReturned?: int32 = 20;

    @doc("Similar face searching mode. It can be 'matchPerson' or 'matchFace'. Default value is 'matchPerson'.")
    mode?: FindSimilarMatchMode = "matchPerson";

    ...T;
  },
  Body<FindSimilarResult[]>,
  ServiceTraits,
  FaceErrorResponse
>;
```

```
findSimilar is FindSimilarOperation<{
    @doc("An array of candidate faceIds. All of them are created by \"Detect\" and the faceIds will expire 24 hours after the detection call. The number of faceIds is limited to 1000.")
    faceIds: uuid[];
  }>;
```
The `isFinished` flag of the body model is `false`

expected:
true

**Comment by lirenhe** [comment]
@iscai-msft this problem is coming from the latest version of TCGC and it would impact service team to release their SDK.
Could you help to work on it with priority? 

cc @lmazuel

**Comment by iscai-msft** [comment]
This issue confused me, but it turns out that `isFinished` is a property in the compiler, not in tcgc, @chunyu3 you must be accessing this through `.__raw`. @timotheeguerin do you have any insight into this issue / know who to contact about it?

Also @chunyu3 what are you using this property for? Asking because currently your code is accessing `.__raw`, this might be helpful to bubble up in tcgc, but does depend on the viability for all languages. Thanks!

**Comment by chunyu3** [comment]
close it since `isFinished` is not honor this.
