### ISSUE TITLE
Setting `additionalProperties` to true

### ISSUE THREAD

**Issue by youngbupark** [Azure/typespec-azure#77]
When we use 0.47.x tsp libraries, the following code generates `additionalProperties: true` by having `extends Record<unknown>` in tsp model definition. 
However, the latest (0.51.x) tsp does not generate `additionalProperties: true`. How can we emit this property back with the latest tsp? 

```typespec
@doc("ExtenderResource portable resource properties")
model ExtenderProperties extends Record<unknown> {
  ...EnvironmentScopedResource;

  @doc("The secrets for referenced resource")
  secrets?: {};

  @doc("The recipe used to automatically deploy underlying infrastructure for the extender portable resource")
  recipe?: Recipe;

  @doc("Specifies how the underlying service/resource is provisioned and managed.")
  resourceProvisioning?: ResourceProvisioning;
}
```

Output (Left: 0.33.0 Right: 0.51.0)

<img width="1201" alt="image" src="https://github.com/Azure/typespec-azure/assets/11863108/b11bb1e1-7a47-41e7-b6f3-74e24555c53f">

**Comment by markcowl** [comment]
For Azure APIs, the advice is to use `model is Record<T>` instead of `model extends Record<T>`.  This results in `additionalProperties: {}` in swagger, which is equivalent to `additionalProperties: true`
