### ISSUE TITLE
[tcgc] switch `...` to always mean spreading, regardless of model or alias

### ISSUE THREAD

**Issue by iscai-msft** [Azure/typespec-azure#772]
This issue is blocked by #771 

### Clear and concise description of the problem

Right now, tcgc has `...MyModel` maintain the logical grouping, but `...MyAlias` spread out the parameters. This is because there is a lack of support for `op(MyModel)` language definitions, and because we want to regroup models spread in azure core templates.

However, this behavior is often confusing and has led to a lot of back and forth. After talking with the TypeSpec team, we want to change the default, because eventually with more language support, `...MyModel` should mean spread. The TypeSpec team will also modify the spreading currently done in `Azure.Core` templates (#771). If we implement this change concurrently with the `Azure.Core` changes, emitters shouldn't really see any code changes

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
closing because we're documenting this change in #1043

**Comment by tadelesh** [comment]
reopen since this is only for tcgc change.
