### ISSUE TITLE
[Bug]: unprocessed request body is `void`

### ISSUE THREAD

**Issue by Alancere** [Azure/typespec-azure#795]
### Describe the bug

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apicenter/ApiCenter.Management/ApiDefinition.tsp#L50

![image](https://github.com/Azure/typespec-azure/assets/46921893/50033a2f-4967-4d04-990b-504665f96349)

### Reproduction

![image](https://github.com/Azure/typespec-azure/assets/46921893/2abd4b9f-7933-4f60-8a55-14282f1c306b)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
related issue: https://github.com/microsoft/typespec/issues/3299
