### ISSUE TITLE
[TCGC][Discussion] model types, when should standalone models be generated

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#823]
TSP:
```ts
@access(Access.internal)
model StandAloneUnion {
  data: url | bytes;
}
```
For this case, currently TCGC will not return the model. TCGC by design will only return the model if both `@access` and `@usage` are defined. But Java will generate the class `StandAloneUnion`, so after switching to TCGC, there would be code diff in Java. Details can be found in the pr: https://github.com/Azure/autorest.java/pull/2698#discussion_r1584381046

Would like to bring up the discussion on whether we need to generate the standalone models if only `@access` is defined.

**Comment by tadelesh** [comment]
@pshao25 this should be a must for .NET to generate orphan model, right?

**Comment by pshao25** [comment]
The principle is "overriding access shouldn't change the usage". Can you update your tests?

**Comment by tadelesh** [comment]
> The principle is "overriding access shouldn't change the usage". Can you update your tests?

when we implement usage/access override in tcgc, you said only when an orphan model has access and usage override, they should be generated, is that still correct for .net now?

**Comment by pshao25** [comment]
> > The principle is "overriding access shouldn't change the usage". Can you update your tests?
> 
> when we implement usage/access override in tcgc, you said only when an orphan model has access and usage override, they should be generated, is that still correct for .net now?

Correct

**Comment by tadelesh** [comment]
discussed with @weidongxu-microsoft offline. get consensus this logic is ok.

**Comment by haolingdong-msft** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/ai/Face/client.tsp#L27-L50 
Face AI has this kind of case: only defined `@access`, but not `@usage`.
Currently Java generated code will have breaking changes. If we thought both @access and @usage should be defined in order to generated the model. We should ask them to modify spec.
/cc @weidongxu-microsoft @tadelesh @pshao25
