### ISSUE TITLE
[Bug]: New model `UserAssignedIdentities` will cause breaking changes for SDK

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/typespec-azure#824]
### Describe the bug

In 0.42, tsp-arm seems to introduce a new model `UserAssignedIdentities`: https://github.com/Azure/typespec-azure/blob/ac594eb6e52b4f41d6aaba774bd7f8f94490a870/packages/typespec-azure-resource-manager/lib/common-types/managed-identity.tsp#L37
though previously, it's a property whose type is defined as `Record`: https://github.com/Azure/typespec-azure/blob/4c7a78aeb2c4e75020568a6fb57fd8505d839f5b/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L398

TCGC will generate a new model `UserAssignedIdentities` if it's defined `is Record`, which changes Java's generated `ManagedServiceIdentity`'s `userAssignedIdentities` property type from `Map<String, UserAssignedIdentity>` to now`UserAssignedIdentities`. This a breaking change. See https://github.com/Azure/autorest.java/pull/2698#discussion_r1596260260

I wonder why we decide to change the `UserAssignedIdenties` definition? 
BTW, isn't `model is Record` discouraged in ARM?
https://azure.github.io/typespec-azure/docs/libraries/azure-resource-manager/rules/no-record#-incorrect-1

### Reproduction

It happens for SDK generation. In Swagger, it refers to the common model.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by msyyc** [comment]
Python has similar issue, too.

**Comment by weidongxu-microsoft** [comment]
My guess is that the discourage is for generic additionalProperties.

I think the easiest fix would be as https://github.com/Azure/typespec-azure/issues/825 mentioned to revert it to `userAssignedIdentities?: Record<UserAssignedIdentity>`.

**Comment by XiaofeiCao** [comment]
discussion in https://github.com/Azure/typespec-azure/issues/825
