### ISSUE TITLE
[TCGC] design discussion, support options parameter in SDK

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#831]
### Clear and concise description of the problem

# Requirement

route can be
```ts
@resource("resource-collection")
model Resource {
  @key name: string;
  prop1: string;
}
model RequiredClientOptions {
  prop1: string;
}
model OptionalClientOptions {
  @header headerParam?: string;
  @query queryParam?: string;
  prop2?: string;
}
@trait
model RequestPropertiessTrait {
  @traitContext(TraitContext.Action)
  request: {
    @traitLocation(TraitLocation.Parameters)
    properties: {
      prop3: string
    };
  };
}
model Response {
}

op action is ResourceOperations.ResourceAction<
  Resource,
  {@header headerParam2?: string, ...RequiredClientOptions, ...OptionalClientOptions},
  Response,
  RequestPropertiessTrait>;
```

The source of request parameters could be from operation, from (shared) model (explicit or implicit body property), from (shared) template, from (shared) trait. This is one of the difficulties, that dev is likely not able to write an operation with a single model that contains all request parameters and body properties, as they uses Azure.Core template and trait.

A typical situation in SDK is that the parameters of the API is too long/complex, and SDK would like to group them into an [options parameter pattern](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-params-complex), e.g.
```java
public Response action(ActionOptions actionOptions);

public class ActionOptions {
  String name; // path
  String prop1; // body
  String prop2; // body
  String prop3; // body
  String queryParam; // query
  String headerParam; // header
  String headerParam2; // header
}
```
(some properties in `ActionOptions` is required)

A slightly different API could be
```java
public Response action(String name, ActionOptions actionOptions);
```

# Alternatives on Design

One major difficulty is to have the mapping of the properties in (if we define this options parameter model in client.tsp)
```ts
model ActionOptions {
  name: Resource.name;
  prop1: RequiredClientOptions.prop1;
  prop2?: OptionalClientOptions.prop2;
  prop3: string; // not able to ref, need named model
  queryParam?: OptionalClientOptions.queryParam;
  headerParam?: OptionalClientOptions.headerParam;
  headerParam2?: string; // not able to ref, even via Service.action::parameters.headerParam2, need named model
}
```
to the parameters of the operation
```ts
op action is ResourceOperations.ResourceAction<
  Resource,
  {@header headerParam2?: string, ...RequiredClientOptions, ...OptionalClientOptions},
  Response,
  RequestPropertiessTrait>;
```

## Candidate design: provide a model name for "options parameter"

Provide a decorator that only provide the name for "options parameter".
```ts
@@optionsParameter(Service.action, "ActionOptions");
```

Emitter would put all the path/header/query/property of the API into this options parameter.
This solution could avoid the difficulty of mapping the properties.

For a POST action already have a model as request body, we can ask dev to use an alias/spread to avoid the model be visible in SDK.

This may also solve the problem that Python want the alias/spread (i.e., all parameters and body properties on method signature), and other language want the options parameter -- via the scope of `@optionsParameter`.

This design is not able to support API with finer structure like `public Response action(String name, ActionOptions actionOptions)`.

## Candidate design: TOM pattern

```ts
namespace Client;

model ActionOptions {
  prop1: Service.RequiredClientOptions.prop1;
  prop2?: Service.OptionalClientOptions.prop2;
  prop3: string; // not able to ref, need named model
  queryParam?: Service.OptionalClientOptions.queryParam;
  headerParam?: Service.OptionalClientOptions.headerParam;
  headerParam2?: string; // not able to ref, need named model
}

@serviceOperation(Service.action)
op action(name: Resource.name, actionOptions: ActionOptions);
```

This is a most flexible representation in client.tsp. However, it would involve the complexity of mapping the properties. It is hard to figure out that `ActionOptions.prop3` is from trait `RequestPropertiessTrait.reuqest.properties.prop3` (where some of the model is anonymous).
And it could be hard to maintain, if service evolve the API and add more (optional) parameters/properties.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
@weidongxu-microsoft is this covered now that we have support for `@override` as part of the spread discussion?

**Comment by weidongxu-microsoft** [comment]
@iscai-msft 

Yeah, we can close this, as `@override` should support this.
