### ISSUE TITLE
[Bug]: Inconsistent type of `OperationStatusResult.percentComplete`

### ISSUE THREAD

**Issue by Alancere** [Azure/typespec-azure#832]
### Describe the bug

go sdk two different results:
![image](https://github.com/Azure/typespec-azure/assets/46921893/a971694c-f882-4373-9418-179cb20c8516)

### Reproduction

tsp: https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/common-types/types.tsp#L220

spec common-type: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v3/types.json#L439

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
cc: @allenjzhang

**Comment by allenjzhang** [comment]
Per ARM RPC guide line, it would be float64 (double). https://github.com/Azure/azure-resource-manager-rpc/blob/8231d7df51aec87e6ccb5bcc04478136758b0a4c/v1.0/async-api-reference.md?plain=1#L164
