### ISSUE TITLE
tcgc: expose way to get default api-version on methods

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#843]
### Clear and concise description of the problem

While methods contain an array of available api-versions, there's no easy way to determine which one is the default api-version. At present, we can enumerate the params, looking for `isApiVersionParam` and `clientDefaultValue`. Maybe method types can have a method `getDefaultApiVersion()` or something that returns the default? Or the index into `apiVersions` that's the default version.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
`apiVersion` in method should be all api versions that contain that method and the default should be the last one in the array.
