### ISSUE TITLE
[Bug]: The `OperationListResult` is converted to `PageOperation` ARM consistency

### ISSUE THREAD

**Issue by Alancere** [Azure/typespec-azure#844]
### Describe the bug

`Azure.ResourceManager.Operations` response `OperationListResult` is converted to `PageOperation`

![image](https://github.com/Azure/typespec-azure/assets/46921893/57c79392-bcb3-44c5-8039-15ac29c676ac)

### Reproduction

tsp: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devopsinfrastructure/Microsoft.DevOpsInfrastructure/main.tsp#L396

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
cc: @allenjzhang

**Comment by allenjzhang** [comment]
fixed in pending PR #945
