### ISSUE TITLE
[Bug]: `principalId` and `tenantId` in `ManagedServiceIdentity` should be of type `uuid`  ARM consistency

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/typespec-azure#845]
#### BUG

TypeSpec definition:
https://github.com/Azure/typespec-azure/blob/ac594eb6e52b4f41d6aaba774bd7f8f94490a870/packages/typespec-azure-resource-manager/lib/common-types/managed-identity.tsp#L20-L27

Though in Swagger's [common-types v5](https://github.com/Azure/azure-rest-api-specs/blob/a3b67e1e3a9554951860b9f9d2e1723036a5e032/specification/common-types/resource-management/v5/managedidentity.json#L53-L72), it's defined as 
```json
"principalId": {
  "readOnly": true,
  "format": "uuid",
  "type": "string",
  "description": "The service principal ID of the system assigned identity. This property will only be provided for a system assigned identity."
},
"tenantId": {
  "readOnly": true,
  "format": "uuid",
  "type": "string",
  "description": "The tenant ID of the system assigned identity. This property will only be provided for a system assigned identity."
},
```
[v3](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v3/managedidentity.json#L20-L33), [v4](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/managedidentity.json#L20-L33) are uuids also.

Java mgmt SDK will generate type `UUID` for `"format": "uuid"`. Lacking this mark will break Java SDK.

#### Expected behavior
These two properties should ~~have `@format("uuid")`~~ be of type `uuid`:
```typescript
@doc("The Active Directory tenant id of the principal.")
@visibility("read")
//@format("uuid")
//tenantId?: string;
tenantId?: uuid;

@doc("The active directory identifier of this principal.")
@visibility("read")
//@format("uuid")
//principalId?: string;
principalId?: uuid;
```

### Reproduction

In the description

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Should change to have `uuid` type not `@format("uuid")`

**Comment by XiaofeiCao** [comment]
@timotheeguerin This will impact MPG for Java and Go(@tadelesh for confirmation). I can help with a PR.

**Comment by pshao25** [comment]
> @timotheeguerin This will impact MPG for Java and Go(@tadelesh for confirmation). I can help with a PR.

Could you do this together? https://github.com/Azure/typespec-azure/issues/863

**Comment by XiaofeiCao** [comment]
@timotheeguerin Another discrepancy for `ManagedServiceIdentity`: https://github.com/Azure/typespec-azure/issues/931

I'll put them together.

**Comment by allenjzhang** [comment]
fixed in pending PR. #945
