### ISSUE TITLE
`subscriptionIdParameter` discrepancy from tsp and swagger ARM Consistency

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#863]
For v5 common-types: https://github.com/Azure/azure-rest-api-specs/blob/7aacb10759f40121fc79c52080e0b0e840d6a329/specification/common-types/resource-management/v5/types.json#L637, `subscriptionIdParameter` has format uuid while in tsp it is just a string.

**Comment by ArthurMa1978** [comment]
Related to https://github.com/Azure/typespec-azure/issues/845, I suggest that `subscriptionId` should be string for the sake of backward compatibility,.

**Comment by allenjzhang** [comment]
fixed in pending PR #945
