### ISSUE TITLE
[Feature Request][TCGC] Improve anonymous model names insider operation templates

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#87]
**Is your feature request related to a problem? Please describe.**
When an anonymous model is defined in an operation template, like `union` test cases under `cadl-ranch`: https://github.com/Azure/cadl-ranch/blob/e9ec5ecc308a01675fb80f3724cd7db558c61aa1/packages/cadl-ranch-specs/http/type/union/main.tsp#L220-L222
```typescript
interface GetAndSend<Union, Payload extends valueof string, Cases = Union> {
  ...
  get(): { // anonymous model
    prop: Cases;
  };
...
```

They will be given names like `GetResponse1`, `GetRespons2`... for each operation instance. That's very fragile, because any change on the template instantiation will change the names totally.

**Describe the solution you'd like**
We should use the operation instance name as the context to generate the name of the anonymous model. In the given example, instead of having `GetResponse1`, we probably can give the name `StringExtensibleGetResponse`.

**Comment by haolingdong-msft** [comment]
Current anonymous model logic is [operation name][parameter location like body/query][non-anonymous model name][property name]. This is an anonymous model used for response. So the name is `GetResponse`, `Get` is because the operation name is `get`.
But as you know, anonymous model cannot cover every edge case, so in some edge  cases , we will name it using suffix `1`, `2`. 

 I don't quite understand this comment:
"
That's very fragile, because any change on the template instantiation will change the names totally.
"
Could you explain more details?

**Comment by archerzz** [comment]
> @archerzz Current anonymous model logic is [operation name][parameter location like body/query][non-anonymous model name][property name]. This is an anonymous model used for response. So the name is `GetResponse`, `Get` is because the operation name is `get`. But as you know, anonymous model cannot cover every edge case, so in some edge cases , we will name it using suffix `1`, `2`.
> 
> I don't quite understand this comment: " That's very fragile, because any change on the template instantiation will change the names totally. " Could you explain more details?

@haolingdong-msft `interface GetAndSend<Union, Payload extends valueof string, Cases = Union>` is a template. There are a few operation instances declared above. If later on, we insert a new operation instance in-between, then sequence of `GetResponse1/2/3/4/5` is changed. That will cause breaking change.

**Comment by haolingdong-msft** [comment]
> > @archerzz Current anonymous model logic is [operation name][parameter location like body/query][non-anonymous model name][property name]. This is an anonymous model used for response. So the name is `GetResponse`, `Get` is because the operation name is `get`. But as you know, anonymous model cannot cover every edge case, so in some edge cases , we will name it using suffix `1`, `2`.
> > I don't quite understand this comment: " That's very fragile, because any change on the template instantiation will change the names totally. " Could you explain more details?
> 
> @haolingdong-msft `interface GetAndSend<Union, Payload extends valueof string, Cases = Union>` is a template. There are a few operation instances declared above. If later on, we insert a new operation instance in-between, then sequence of `GetResponse1/2/3/4/5` is changed. That will cause breaking change.

But if you define th name as `StringExtensibleGetResponse`, if another `get()` operation in `StringExtensible` interface, you will still have `StringExtensibleGetResponse1/2/3/4`.. I mean is there would be cases that our naming logic can't handle and we need to use suffix, I will discuss with @tadelesh to see up to what level shall we cover.

**Comment by archerzz** [comment]
> But if you define the name as `StringExtensibleGetResponse`, if another `get()` operation in `StringExtensible` interface, you will still have `StringExtensibleGetResponse1/2/3/4`.. I mean is there would be cases that our naming logic can't handle and we need to use suffix, I will discuss with @tadelesh to see up to what level shall we cover.

Here, `get` is the operation name, not the HTTP method. It's unique.

**Comment by haolingdong-msft** [comment]
> > But if you define the name as `StringExtensibleGetResponse`, if another `get()` operation in `StringExtensible` interface, you will still have `StringExtensibleGetResponse1/2/3/4`.. I mean is there would be cases that our naming logic can't handle and we need to use suffix, I will discuss with @tadelesh to see up to what level shall we cover.
> 
> Here, `get` is the operation name, not the HTTP method. It's unique.

We are currently using operation name, not HTTP method. It is called `GetResponse` because the operation name is `get`, not because the HTTP method. 
I mean even if we include interface name into the anonymous model name, user can define another operation named `get()` in the interface. It's still duplicate.

**Comment by tadelesh** [comment]
Current logic names anonymous model with the operation name, not take namespace/interface name into account. The sequence for the template usage will indeed cause naming change, which we are not aware of before.

**Comment by haolingdong-msft** [comment]
Yes. Let's solve it by adding interface and namespace into the usage path.

**Comment by iscai-msft** [comment]
@tadelesh has incorporated this in naming
