### ISSUE TITLE
[TCGC]: make sure discriminator is the 1st property

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#871]
### Clear and concise description of the problem

Moving discriminator to the beginning of properties array could bring benefits in performance and code simplicity for backend services. See the discussion in this issue: https://github.com/Azure/autorest.csharp/issues/4439

Sequence of properties defined in TCGC will impact the JSON payload sent by SDKs. For backend services, the JSON frameworks they use might require discriminator is always the 1st property. Otherwise, a custom deserializer is required.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
.net confirmed with customer that they will not do that explicitly. so also close for tcgc.
