### ISSUE TITLE
We have `any` in `SdkBuiltinKinds` for the built-in type `unknown` in typespec, why not `unknown`?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#874]
It is not a good practice that we change a name for a builtin type. Is it because the kind `unknown` is ambiguous from the type with a name of `unknown` and the case where there is an invalid kind which we do not know?

**Comment by iscai-msft** [comment]
Yeah that was the original thinking, and because it aligned more closely with what we got from m4. Happy to change this though, it will just be a breaking change that will have to be driven across languages

**Comment by tadelesh** [comment]
proposal: change `any` to `unknown`
