### ISSUE TITLE
Could we specify the value type of `SdkEnumType` more precisely 

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#876]
Now the type of `valueType` property in `SdkEnumType` is `SdkBuiltInType`, but this type is kind of too generic for enum because the value type of an enum could never be something other than string and number.

**Comment by iscai-msft** [comment]
We currently just have `SdkBuiltInType`, which has a bunch of different kinds. If you'd like to @ArcturusZhang, you can add a PR splitting this up. I'm not sure it's worth the trouble, but it would still be nice to more strongly type than just `SdkBuiltInType`. Would this be something you're interested in taking on? Thanks!

**Comment by ArcturusZhang** [comment]
> We currently just have `SdkBuiltInType`, which has a bunch of different kinds. If you'd like to @ArcturusZhang, you can add a PR splitting this up. I'm not sure it's worth the trouble, but it would still be nice to more strongly type than just `SdkBuiltInType`. Would this be something you're interested in taking on? Thanks!

since we are moving out those azure stuffs, this have relatively less concern now.
