### ISSUE TITLE
`UsageFlags` in TCGC collides with the enum defined in `typespec/compiler`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#878]
We have the enum of `UsageFlags` in both TCGC and `typespec/compiler`, which is very inconvenient and very easy to be misused, we might consider to change the name of our `UsageFlags` in TCGC

**Comment by iscai-msft** [comment]
This mgiht be too breaking for each language emitter, since they're probably all using `UsageFlags` rn, what are your thoughts. I might have to assign this to you if you think it's worth it, we have a few too many issues right now

**Comment by tadelesh** [comment]
since the value in core and tcgc is same for none/input/output, i think it's ok to have the same name.
