### ISSUE TITLE
SdkClient lacks of client parameter information

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#887]
We call `listClients` to get the client list. Take [this](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHVzZUF1dGgoCiAgQXBpS2V5xA48xgtMb2NhdGlvbi5oZWFkZXIsICJhcGkta2V5Ij4gfCBPxCoyxS9bCiAgICB7xQYgIOQA3DrHH0Zsb3fkAKUuaW1wbGljaXQsxyVhdXRob3JpesVhVXJsOiAi5AFoczovL2xvZ2luLmNvbnRvc28uY29tL2NvbW1vbi9vxDUyL3YyLjAvyEBlIshSc2NvcGVzOiBbyUl3aWRnZXTNSi5kZWZhdWx0Il3GN30KICBdPgopCkBzZXJ2aWNlKOQAxnRpdGxlOiAiQ8Y6IFfFSSBNYW5hZ2VyIiwKfccxZXLkATkie2VuZHBvaW50fS9jbGllbnQvc3RydWN0dXJlL3vGEn3lAKgixQbEYyAgQGRvYygiTmVlZCB0byBiZSBzZXQgYXMgJ%2BQAv%2BUBB2NhbGhvc3Q6MzAwMCcgaW4gxksuIinFQch1OiB1cmwsCt5V5wD4JywgJ211bHRpLcZMxBByZW5hbWVkLW9wZXLlAY%2FEFXR3b8oRLWdyb3Vw8wCDxg46IHN0cmluZ%2BQA3H3kAUznAwBlZCjnAUIu5gFC5wFB6AKucykKxHpzcGFjZSDVKjsKCi8qKiBUaMkg7wGMIOcBtyDHcy4gKi8KZW51bSDIZOUBbsRFxxEgMjAyMi0wOC0zMcQsICDkAwNEZXBlbmRlbmN5KOsDJshDLnYxXzBfUHJldmlld18y5AD7YMlGMGAsCn0KCkByb3V0ZSgiYmF6L3vkANZ9IuwA3kJheuUAiWludGVyZsQSRm9vxRIgICNzdXBwcmVzc%2B8EJGNhZGwtcmFuY2gtZXhwZWN0L21pc%2BQDyi1zY2VuYXJpbyIgIlRoaXMgaXMgYnkgZGVzaWduIHRob3NlIOkBvHMg5AEvZGVmaW5lZOQCC8g9c%2BQBz3RoZecBxSLmAkDnAMcvc2V2ZW7nAeZAcG9zdMUKxRYoQHBhdGgg5ADd6AH6KTogdm9pZDvlAgF9&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%5D%7D%7D) as example,
1. `client` is a client parameter for `ServiceClient`, `Baz`, and `BazFoo`.
2. `name` is a client parameter for `Baz`, and `BazFoo`, **not** for `ServiceClient`.

So when I call `listClients`, I should somehow know the client parameters of specific clients, or I should somehow know a specific parameter belongs to which client.

**Comment by tadelesh** [comment]
this is handled in `SdkClientType`, not in `listClients`. after you adopt `getAllOperations`, you will get that info.
