### ISSUE TITLE
TCGC: Add Support for Json Usage Flag for a Given Model

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/typespec-azure#896]
The .net generator requires knowing when a model is used in an operation that had content type to `application/json` to aid with generating the serialization code for a model. The existing usage flags should be extended to support an additional `json` usage flag to indicate when a model is used in an operation who's content type includes `application/json`.

**Comment by iscai-msft** [comment]
Do you need to know that it's used in `application/json` or just `JsonMergePatch`? If it's `application/json`, can you explain the use case? The default is they're used with `application/json` (and not multipart form data). If they're used with multipart form data, you would specify that with `UsageFlags.MultipartFormData`

**Comment by jorgerangel-msft** [comment]
hey @iscai-msft, we need to know when the model is used in `application/json`. Right now, if the default is assuming that it's application/json, we just need a way to know that explicitly from the generator as we don't have a way of knowing if the model was used for json. The use case from the generator is that if we encounter a model who is used in an operation that had content type to application/json, then we need to generate some additional json serialization methods for it.

**Comment by iscai-msft** [comment]
talked offline with @m-nash and I understand now. I'm wondering, would it be better to have a list of the content types it's used for, instead of adding more entries to `UsageFlags`? We are going to have merge patch json, application/json, and xml as well. Something like this

```ts
model.contentTypes === ["application/json", "application/merge-patch+json"]
```

cc @tadelesh

**Comment by jorgerangel-msft** [comment]
@iscai-msft - I don't have any concerns with that approach. @m-nash - any thoughts on this?

**Comment by iscai-msft** [comment]
@jorgerangel-msft I've opened PR #1129 to add this feature. It will be released as part of the TypeSpec release going out next Tuesday, so you should be good to go by then. Thanks for your patience!
