### ISSUE TITLE
[TCGC]: provide `SdkNamespace`

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#899]
### Clear and concise description of the problem

In original typespec definition, there are quite many decorators attached to a `namespace`, like:
```typescript
@versioned(Versions)
@service({title: "Anomaly Detector"})
@useAuth(ApiKeyAuth<ApiKeyLocation.header, "Ocp-Apim-Subscription-Key">)
@server(
  "{Endpoint}/anomalydetector/{ApiVersion}",
  "xxx.",
  {
    @doc("""
Supported Cognitive Services endpoints (protocol and hostname, for example:
https://westus2.api.cognitive.microsoft.com).
""")
    Endpoint: string,
    @doc("Api Version")
    @path
    ApiVersion: APIVersion
  }
)
@doc("CADL project to test api versions.")
namespace ApiVersionInTsp;
```

Some of them could be accessed in other places. But how about `@doc`? Right now, `SdkPackage.rootNamespace` is just a string.

From what I can see, there are 2 approaches:
1. Make sure all decorator values can be defined in other places in TCGC.
2. Or we can provide a `SdkNamespace` which include the values which cannot be define somewhere else.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
The doc info is in `description` on `SdkClientType`. I doubt if there is other case.

**Comment by archerzz** [comment]
Double checked with team. We do not generate comments for namespace. So this request is invalid.
