### ISSUE TITLE
TCGC: Flatten Response Decorator

### ISSUE THREAD

**Issue by l0lawrence** [Azure/typespec-azure#913]
Is there a good way to flatten an operation response into its individual pieces? (similar to alias/spread maybe?)

i.e I have an operation that returns ReceiveResult(List[ReceiveDetails]) and I want to just return List[ReceiveDetails] 

seen here:

https://github.com/Azure/azure-rest-api-specs/blob/9df71d5a717e4ed5e6728e7e6ba2fead60f62243/specification/eventgrid/Azure.Messaging.EventGrid/main.tsp#L296

**Comment by tadelesh** [comment]
a post paging operation? my idea is to provide a general way to map client method to service operation (project tom?).

**Comment by iscai-msft** [comment]
@tadelesh do you have a vague outline yet? i agree with what you're proposing that it should be more generic

**Comment by iscai-msft** [comment]
Closing in favor of https://github.com/Azure/typespec-azure/issues/1167
