### ISSUE TITLE
[TCGC] Support 'Exception' usage on `SdkModelType`/`SdkEnumType`

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#917]
Java needs to know if the model's usage is exception or not, e.g. not generate exception model. Currently we did special handling in emitter to see if a model is exception or not. But we should not track usage by ourselves after migrating to use TCGC usage. So it's better that TCGC can provide an `Exception` usage.

Our handling in emitter: https://github.com/Azure/autorest.java/blob/main/typespec-extension/src/code-model-builder.ts#L1643-L1650

**Comment by iscai-msft** [comment]
Unless I'm missing something, there is already this usage in the `.usage` section: There's an `isError` usage, so you can check it against `UsageFlags.IsError`

**Comment by tadelesh** [comment]
@iscai-msft we do not have `IsError` usage in tcgc now, do you mean we need to add support for that?

**Comment by iscai-msft** [comment]
oh you're right, I'm remembering now that I was originally going to add it into `UsageFlags`, but then @weidongxu-microsoft mentioned that Java actually shouldn't need to know this information? I can't find the conversation and I don't fully remember it

**Comment by weidongxu-microsoft** [comment]
> oh you're right, I'm remembering now that I was originally going to add it into `UsageFlags`, but then @weidongxu-microsoft mentioned that Java actually shouldn't need to know this information? I can't find the conversation and I don't fully remember it

@iscai-msft I don't think it was me.
We use m4 SchemaUsages and m4 has it, there is no incentive for me to break from that :-)
