### ISSUE TITLE
[Bug][TCGC]: alias model name is empty

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#918]
### Describe the bug

The following definition will generate 2 anonymous models, which is expected because alias model is like expression. However, their names are empty.
```typescript
@resource("tow")
model Test {
  @key
  name: string;
};

alias Request = {
  @doc("age.")
  age: int32;
};

model Request2 {
  @doc("age.")
  age: int32;
};

interface Test1 {

@route("/one")
@put
op create is Foundations.ResourceOperation<Test, Request, TypeSpec.Http.OkResponse>;

}


@route("/two")
@put
op create is Foundations.ResourceOperation<Test, Request, TypeSpec.Http.OkResponse>;
```
Playground is [here](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQrJGmF6dXJlLXRvb2xzL8gmLcYVY29yZc0syUZodHRw1hp2ZXJzaW9uaW5n32ZlYy1jbGllbnQtZ2VuZXJhdG9yyXENCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwyRZBxGIuQ8VTR8hSLkNvcmXSOVbpAKXQP8YvDQpA5wDIZWQoxy1zKQ0KQHNlcnZpY2Uoe3RpdGxlOiAiQW5vbWFseSBEZXRlY3RvciJ9xCd1c2VBdXRoKEFwaUtlecQLPMYLTG9jYXRpb24uaGVhZGVyLCAiT2NwLUFwaW0tU3Vic2NyaXDEHy1LZXkiPshxZXIoDQogICJ7RW5kcG9pbnR9L2HGd2TIdizFIVRoZSDwAJEgQVBJIMYocyDGN2llcyBhdXRvbWF0aWNhbGx5IGluIHRpbWUgc2VyxB1kYXRhLiBJdCBzdXDkAcBzIHR3byBraW5kcyBvZiBtb2RlLCBvbmUgaXMgZm9yIHN0YXRlbGVzcyDlAUwsxGh0aGVyzSBmdWzGHy4gSW7LM8ZOxC9lIGFyZSB0aHJlZSBmdW5j5AEKYWxpdGllcy4gRW50aXJl5wDXyFnmANjkAb90aGUgd2hvbOkAxHdpdGjFXGwgdHJhaW5lZCBiecUn6wDqLCBMYXN0y1XKUWzEGeUBbtdLxRxzIGJlZm9yZS4gQ2hhbmdlUMUx%2BQClcmVuZCBjxSpz7wF16gEW5AEpxG4sIHVzZXIgY2HEGG%2FkARrKLuUBMcYXZMwYIHdpbGwgYmXEO2TMfm9u6gH9LiBVbmRlciB0aGnoAX%2FLasRBdXPkAYhlIGFib3b3AZLkAQNvbmx5IGdpduQA3GHmAIdy5ADc5QEyb3V0IHByZXBhcsQf7ACkaW4g5gP6IHNpZGUuIEJlxAhz33JzLO4BH2wgYWxzbyBwcm92aWRlIGdyb3VwIGJh5AD47AD0ZCBsYWJlbOQAhOcDvS4gQnkgbGV2ZXJhZ8QX0CDqAQ3IXMUi5gHNZWFjaMtgcmVzdWx05QGOc8ko8QGEcmV0deQEbSDFDOcE78QQyknlANLlAgVjb25zaXN0ZW5jecsgaXMgYeUDguQDgfUA7OQAheoCwm9u5gCHZsQzac1Vb27mAYRhIHNldMRP7QKGQnnmA6bnAi%2FoAITkA8bmAR8sIGLEIeQDu2N1c3RvbWVyc%2BUBLmRpc2NvduQD9m5jaWRl5AMd5AF%2FZXN0YWJsaXNoIGEgbG9naWMgZmxvd%2BYBGG9vdCBjYeQCbmFuYWx5c2lzLuYEy3vEBSAgQGRvYygiIiINClPmBIplZCBDb2duaXRpdmUgU%2BYAkXMgZecFGHMgKHByb3RvY29sxXtob3N0bmFtZSzFbmV4YW1wbGU6DQrkBr5zOi8vd2VzdHVzMi5hcGkuY8hXLm1pY3Jvc29mdC5jb20pLg0KIiIiKeYAkOgFgTogc3TkAtfEFn0NCuQFqeUAqkNBREzkAjZq5AP%2FdG8gdGVzdCBhcGkg5wZOcy7ESuQAk3NwYWNlIEFwaecGXkluVHPkBswNCmVudW0gxxZz5gEJ5AZQRGVwZW5k5AHBKOoGq%2BgGyXMudjFfMF9QcmV2aWV3XzLlAK92MV8xOiAidjEuMeYBVXYxXzLGETIiDQp9xG1AcmVzb3VyY2UoInRvd%2BQAneYDW1TkALnGfGtlecQI5AC16AD3Ow0KfeUArGFsaWFzIFJlcXXEMD3HMuUBC2FnZeUA7SAgYWdlOiBpbnQzMsk4xmXHODLfN8o3aW50ZXJm5AE55ACgMcQ45ADDb3V0ZSgiL29uZcQ6QHB1dA0Kb3AgY3JlYXTlBqRGb3VuZOUHeHPkCErlAPFPcOUDhW9uPMRMLOgAjSzuCF4uT2tSZXNwb25zZT7lAIPlATbLdXR3b99133XfdTs%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D). If you switch to use `Request2` which is a model, then you'll get one model with name `Request2`.

---

In normal cases, alias models can have auto-assigned names, see below:
```typescript
alias Test = {
  name: string;
};

op createTemplate<T>(@body body: T): NoContentResponse;

namespace ApiVersionInTsp.Test1 {
  alias Test = {
    name: string;
  };

  @route("/one")
  @put
  op create is createTemplate<Test>;
}

@route("/two")
@put
op create is createTemplate<Test>;
```
That will generate 2 models `CreateRequest` and `CreateRequest1`. Playground is [here](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQrJGmF6dXJlLXRvb2xzL8gmLcYVY29yZc0syUZodHRw1hp2ZXJzaW9uaW5n32ZlYy1jbGllbnQtZ2VuZXJhdG9yyXENCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwyRZBxGIuQ8VTR8hSLkNvcmXSOVbpAKXQP8YvDQpA5wDIZWQoxy1zKQ0KQHNlcnZpY2Uoe3RpdGxlOiAiQW5vbWFseSBEZXRlY3RvciJ9xCd1c2VBdXRoKEFwaUtlecQLPMYLTG9jYXRpb24uaGVhZGVyLCAiT2NwLUFwaW0tU3Vic2NyaXDEHy1LZXkiPshxZXIoDQogICJ7RW5kcG9pbnR9L2HGd2TIdizFIVRoZSDwAJEgQVBJIMYocyDGN2llcyBhdXRvbWF0aWNhbGx5IGluIHRpbWUgc2VyxB1kYXRhLiBJdCBzdXDkAcBzIHR3byBraW5kcyBvZiBtb2RlLCBvbmUgaXMgZm9yIHN0YXRlbGVzcyDlAUwsxGh0aGVyzSBmdWzGHy4gSW7LM8ZOxC9lIGFyZSB0aHJlZSBmdW5j5AEKYWxpdGllcy4gRW50aXJl5wDXyFnmANjkAb90aGUgd2hvbOkAxHdpdGjFXGwgdHJhaW5lZCBiecUn6wDqLCBMYXN0y1XKUWzEGeUBbtdLxRxzIGJlZm9yZS4gQ2hhbmdlUMUx%2BQClcmVuZCBjxSpz7wF16gEW5AEpxG4sIHVzZXIgY2HEGG%2FkARrKLuUBMcYXZMwYIHdpbGwgYmXEO2TMfm9u6gH9LiBVbmRlciB0aGnoAX%2FLasRBdXPkAYhlIGFib3b3AZLkAQNvbmx5IGdpduQA3GHmAIdy5ADc5QEyb3V0IHByZXBhcsQf7ACkaW4g5gP6IHNpZGUuIEJlxAhz33JzLO4BH2wgYWxzbyBwcm92aWRlIGdyb3VwIGJh5AD47AD0ZCBsYWJlbOQAhOcDvS4gQnkgbGV2ZXJhZ8QX0CDqAQ3IXMUi5gHNZWFjaMtgcmVzdWx05QGOc8ko8QGEcmV0deQEbSDFDOcE78QQyknlANLlAgVjb25zaXN0ZW5jecsgaXMgYeUDguQDgfUA7OQAheoCwm9u5gCHZsQzac1Vb27mAYRhIHNldMRP7QKGQnnmA6bnAi%2FoAITkA8bmAR8sIGLEIeQDu2N1c3RvbWVyc%2BUBLmRpc2NvduQD9m5jaWRl5AMd5AF%2FZXN0YWJsaXNoIGEgbG9naWMgZmxvd%2BYBGG9vdCBjYeQCbmFuYWx5c2lzLuYEy3vEBSAgQGRvYygiIiINClPmBIplZCBDb2duaXRpdmUgU%2BYAkXMgZecFGHMgKHByb3RvY29sxXtob3N0bmFtZSzFbmV4YW1wbGU6DQrkBr5zOi8vd2VzdHVzMi5hcGkuY8hXLm1pY3Jvc29mdC5jb20pLg0KIiIiKeYAkOgFgTogc3TkAtfEFn0NCuQFqeUAqkNBREzkAjZq5AP%2FdG8gdGVzdCBhcGkg5wZOcy7ESuQAk3NwYWNlIEFwaecGXkluVHPkBswNCmVudW0gxxZz5gEJ5AZQRGVwZW5k5AHBKOoGq%2BgGyXMudjFfMF9QcmV2aWV3XzLlAK92MV8xOiAidjEuMeYBVXYxXzLGETIiDQp9xG1hbGlhcyBU5ACnPcZs5ACd6ADfOw0KfeUAlG9wIGNyZWF0ZVRlbXBsYXRlPFQ%2BKEBib2R5IMQFOiBUKTogTm9Db250ZW50UmVzcG9uc%2BYHSfkA7S7EdjHGdfIAh%2FEAiSAg5gCLICBAcm91dGUoIi9vbmXmAZlAcHV0xAjpAKfkAy%2FwALFlc3Q%2B5ADRxEXJQ3R3b8RDxkHfP3Q%2BOw%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D).

---

This is derived from Face spec update: https://github.com/Azure/azure-rest-api-specs/pull/29178
They have multiple create operations like [this](https://github.com/Azure/azure-rest-api-specs/blob/be45b922eca7b7753e74e2074127f395223fa13e/specification/ai/Face/client.tsp#L95) which finally invokes `Foundations.ResourceOperation<>`: https://github.com/Azure/azure-rest-api-specs/blob/be45b922eca7b7753e74e2074127f395223fa13e/specification/ai/Face/routes.common.tsp#L38

They send `CreateCollectionOptions` as the `Parameters` of [Foundations.ResourceOperation](https://github.com/Azure/typespec-azure/blob/8374fda595e5b19cdbc39565598e5a235a6f1d25/packages/typespec-azure-core/lib/foundations.tsp#L348-L354) which will do the `Foundations.ItemKeysOf<Resource> & Parameters` calculation.

And `CreateCollectionOptions` is an alias model: https://github.com/Azure/azure-rest-api-specs/blob/be45b922eca7b7753e74e2074127f395223fa13e/specification/ai/Face/models.common.tsp#L97

### Reproduction

Just try to parse the spec above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iscai-msft** [comment]
There's no way for use to retrieve an alias name, it's not something that TypeSpec keeps since an alias isn't a model, it's basically an anonymous grouping. With "spread is spread", we are moving away from this. Since this isn't possible, I'm going to go ahead and close this issue
