### ISSUE TITLE
Add linter rule to restrain tcgc decorators from being used within the scope of main.tsp scope.

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#924]
### Clear and concise description of the problem

[In batch's case](https://github.com/Azure/azure-rest-api-specs/pull/29018/files#r1613178851), if we define the `@client` decorator in main.tsp and all its refered scope, we will not be able to get any operations from service.type we get with listOperationsInOperationGroups api. see more details [here](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1716545372946?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1716491100753&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion&createdTime=1716545372946)

As tcgc is for customization, while main.tsp is not in the scope of customization, i don't think we should allow any tcgc decorators being used in main.tsp and all its referred files.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
I am not sure we want this at all.  We should try to avoid conditional and double compilation, and right now decorators like clientName are the only mechanism for changing the names of parameters and other entities that impact generated swagger and client generation, but not api shape.

**Comment by markcowl** [comment]
@joheredi please resolve or augment based on the outcome with javascript RLC API

**Comment by qiaozha** [comment]
@joheredi you may take a look at this [investigation](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1716545372946?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1716491100753&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion&createdTime=1716545372946) about the root cause. 

FYI, there's an issue that suggest RLC fully adopt to tcgc https://github.com/Azure/autorest.typescript/issues/2408 by @iscai-msft, which I don't think we should. and if anything, I more incline to think that we should completely get rid of tcgc. that's why I brought up to you earlier we probably should consider split the RLC emitter and Modular emitter, when we try to migrate to the public typespec repo.

**Comment by qiaozha** [comment]
@markcowl for this issue specific, I am more curious about the rationality of putting the tcgc related decorators into the main.tsp scope.

**Comment by joheredi** [comment]
Yes, RLC should not be impacted by anything on TCGC. We currently take a partial dependency on TCGC to get the operations but manually build the SdkClient and use __raw for accessing the TypeSpec types. This midground is causing this sort of issues.

I agree with @qiaozha that we need to decouple the RLC emitter from TCGC completly. Filed this issue to track https://github.com/Azure/autorest.typescript/issues/2553

Closing this issue since we agree we don't need this linter rule and the service team was able to work around the issue. Will continue tracking this work with the issue linked above
