### ISSUE TITLE
[Bug]: visibility discrepancy between Swagger and TypeSpec defined `UserAssignedIdentity` 

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/typespec-azure#931]
### Describe the bug

TypeSpec:
https://github.com/Azure/typespec-azure/blob/a633ee158fe4da70ebe8f1e0a5a27230701244af/packages/typespec-azure-resource-manager/lib/common-types/managed-identity.tsp#L95-L101

Swagger: 
```json
"UserAssignedIdentity": {
  "type": "object",
  "description": "User assigned identity properties",
  "properties": {
    "principalId": {
      "description": "The principal ID of the assigned identity.",
      "format": "uuid",
      "type": "string",
      "readOnly": true
    },
    "clientId": {
      "description": "The client ID of the assigned identity.",
      "format": "uuid",
      "type": "string",
      "readOnly": true
    }
  }
}
```

The model is used in both input and output. 
For input, user sends something like:
```json
{
  "userAssignedIdentities": {
    "00000000-0000-0000-0000-000000000000": {}
  }
}
```
For output, service will reply:
```json
{
  "userAssignedIdentities": {
    "00000000-0000-0000-0000-000000000000": {
      "principalId": <some-principal-id>,
      "tenantId": <some-tenant-id>
    }
  }
}

```

If not defined with  `@visibility("read")`, unnecessary setter methods will be generated for Java. 

### Reproduction

See above

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by allenjzhang** [comment]
fixed in pending PR #945
