### ISSUE TITLE
[Bug]: `1.0` is returned as `int32` type in enum values

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#932]
### Describe the bug

When we have this typespec:
```typespec
enum FloatFixedEnumWithIntValue {
	One: 1.0,
	Two: 2.0
}
```
The underlying value type of this enum is returned as `int32`:
![image](https://github.com/Azure/typespec-azure/assets/10554446/e5bab14b-06ed-4c9e-b07d-53f1d0c510a9)
This potentially causes breaking change in downstream SDKs, for instance they might add a new value `3.3` and the value type will change to `float32`.

### Reproduction

Use the above typespec and see the output

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment]
after tsp compile, we could only get enum value `1` and `2` with number type. we can only distinguish int or float by `.`.
