### ISSUE TITLE
`values` makes no sense in `SdkUnionType`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#933]
We have the following definition for union type in TCGC:

```typescript
export interface SdkUnionType extends SdkTypeBase {
	name: string;
	isGeneratedName: string;
	kind: "union";
	values: SdkType[];
}
```

it would make more sense if we change `values` to `valueTypes` or `itemTypes` or `variantTypes` (I prefer `variantTypes`), because the siblings of an union type are types, not values.

**Comment by tadelesh** [comment]
proposal: change `values` to `variants`

**Comment by ArcturusZhang** [comment]
> proposal: change `values` to `variants`

I prefer `variantTypes` to emphasize that these are types instead of the values of the union
