### ISSUE TITLE
[Bug]: Getting two responses within the same 202 response code

### ISSUE THREAD

**Issue by qiaozha** [Azure/typespec-azure#938]
### Describe the bug

[playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtxhVjb3JlIjsNCsksyCAvcmVzdM0a20ZyZXNvdXJjZS1tYW5hZ2Vy1lJvcGVuYXBp1h12ZXJzaW9uaW5nxCANCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwyRZB5ACLxCnlAItN5gCKyR5PcGVuQVBJzy5Db3Jl0xMuVHJhaXRz0nFW6QCm5QClQGFybVByb3ZpZGVyTmFtZXNwYWNlDQpAc2VydmljZSh7DQogIHRpdGxlOiAiQXBwIENvbXBsaWFuY2UgQXV0b21hdGlvbiBUb29sIGZvciBNaWNyb3NvZnQgMzY1IiwNCn0pDQpA5wEbZWQox39zxBZhcm1Db21tb27kAJ1zxxoo9QEFLssp6ADDcy52MykNCm7oALbKfC5BcHDqAKjqAKflAPIvKioNCiAqIFRoZSBhdmFpbGFibGUgQVBJIOcApnMuxCAvDQplbnVtIMhtIOUBCsY9IMc%2FMjAyNC0wNi0yN8xAxD8gxUEgIEB1c2VEZXBlbmRlbmN59wDcyGMudjFfMF9QcmV2aWV3XzEp2UHlAeHcNnbkAJpfMDZfMjc6ICLqAKflAZHkAQVhbGlhcyBQbGFjZWhvbGRlcugAlCA99gKGLkZvdW5k5QFGcy5Qcm94ecghO8hOQeoCSkFjxClBc3luYzzkAJBSZXF1ZXN0IGV4dGVuZHMge30gfCB2b2lkLMYec3BvbnNl1x9QYXJhbWV0ZXJzzCE9IHt9xR9Mcm9IZWFkzB%2FrA3RmbGXlAIwuTW9kZWzkAN5ybUxyb0xvY%2BUAzMY6ICbESSDsAz%2FsAO9SZXRyeUFmdGVyxi8NCj75ASdBcm3IE%2FABBfMBbucA%2F%2BUBHe4BC3zkAKlBY2NlcHRlZExyb8gZPCLIFSIs6wD7PsU%2BQmFzZesBLj0gQXBp5wInyRfwAVM9yw3wAVD2AS486wEnU3RhdHVzTW9uaXRvclBvbGxpbmdPcMQsczxBcm1PcGVyxTrGKD4%2BDQo%2B5gR3ZG9jKCLKeuUEPG9uYm9hcmQgb8g2IikNCm3lAbhPxhvoAkjvA4xMaXN0IG9mIHN1YnNjcmnlAIAgaWRzIHRvIGJlyFhlZOsDmcwrSWRzOiBzdHJpbmdbXTvnAyLGXirIes0xcyBy5wGP6AQr5gDQU3VjY2Vzcy7lBB3IIyBpbmRpY2F0ZXMgZ2l2ZW7PSmhhcyBiZWVu6gCmLvMA98dL%2FwD46gD4aGF0IGFy%2FwD75gD7P%2FIA%2FG9wIHVwbG9hZCBp%2BQPX7gGSLPAAqz47&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D) 

In this tsp example, I found we have get two response within the same 202 response code,  see the below screenshot.
![image](https://github.com/Azure/typespec-azure/assets/55688292/5568500f-a76e-4958-9a76-3dfd5f3114f4)
I wonder if it's a valid scenario to have multiple response for the same response code, or is it a bug in the compiler or maybe we write the operation template wrong ? 

Another question is how to handle this properly? typespec-autorest emitter is just merged the headers for different response, 
https://github.com/Azure/typespec-azure/blob/281250d7cf49f0d3b8bd0df877837582fb4b5a6a/packages/typespec-autorest/src/openapi.ts#L856  Is it a recommend way to handle the headers that belongs to different responses of the same status code ? 

### Reproduction

we have to dig into the compiler types to see the duplication here 

[playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtxhVjb3JlIjsNCsksyCAvcmVzdM0a20ZyZXNvdXJjZS1tYW5hZ2Vy1lJvcGVuYXBp1h12ZXJzaW9uaW5nxCANCnVzaW5nIFR5cGVTcGVjLlJlc3Q70RZIdHRwyRZB5ACLxCnlAItN5gCKyR5PcGVuQVBJzy5Db3Jl0xMuVHJhaXRz0nFW6QCm5QClQGFybVByb3ZpZGVyTmFtZXNwYWNlDQpAc2VydmljZSh7DQogIHRpdGxlOiAiQXBwIENvbXBsaWFuY2UgQXV0b21hdGlvbiBUb29sIGZvciBNaWNyb3NvZnQgMzY1IiwNCn0pDQpA5wEbZWQox39zxBZhcm1Db21tb27kAJ1zxxoo9QEFLssp6ADDcy52MykNCm7oALbKfC5BcHDqAKjqAKflAPIvKioNCiAqIFRoZSBhdmFpbGFibGUgQVBJIOcApnMuxCAvDQplbnVtIMhtIOUBCsY9IMc%2FMjAyNC0wNi0yN8xAxD8gxUEgIEB1c2VEZXBlbmRlbmN59wDcyGMudjFfMF9QcmV2aWV3XzEp2UHlAeHcNnbkAJpfMDZfMjc6ICLqAKflAZHkAQVhbGlhcyBQbGFjZWhvbGRlcugAlCA99gKGLkZvdW5k5QFGcy5Qcm94ecghO8hOQeoCSkFjxClBc3luYzzkAJBSZXF1ZXN0IGV4dGVuZHMge30gfCB2b2lkLMYec3BvbnNl1x9QYXJhbWV0ZXJzzCE9IHt9xR9Mcm9IZWFkzB%2FrA3RmbGXlAIwuTW9kZWzkAN5ybUxyb0xvY%2BUAzMY6ICbESSDsAz%2FsAO9SZXRyeUFmdGVyxi8NCj75ASdBcm3IE%2FABBfMBbucA%2F%2BUBHe4BC3zkAKlBY2NlcHRlZExyb8gZPCLIFSIs6wD7PsU%2BQmFzZesBLj0gQXBp5wInyRfwAVM9yw3wAVD2AS486wEnU3RhdHVzTW9uaXRvclBvbGxpbmdPcMQsczxBcm1PcGVyxTrGKD4%2BDQo%2B5gR3ZG9jKCLKeuUEPG9uYm9hcmQgb8g2IikNCm3lAbhPxhvoAkjvA4xMaXN0IG9mIHN1YnNjcmnlAIAgaWRzIHRvIGJlyFhlZOsDmcwrSWRzOiBzdHJpbmdbXTvnAyLGXirIes0xcyBy5wGP6AQr5gDQU3VjY2Vzcy7lBB3IIyBpbmRpY2F0ZXMgZ2l2ZW7PSmhhcyBiZWVu6gCmLvMA98dL%2FwD46gD4aGF0IGFy%2FwD75gD7P%2FIA%2FG9wIHVwbG9hZCBp%2BQPX7gGSLPAAqz47&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment]
So, you are seeing a 202 StatusCode and a non-specified StatusCode, which is a 200 for a non-error response.  The `StatusCodes` field is a different type, which is why there are two fields.

What would you expect to see as a result of this template?

**Comment by qiaozha** [comment]
No, they are both 202 statusCode. You can see in the screenshot, responses and statusCode are  in the same level.

**Comment by qiaozha** [comment]
To my understanding, we can only have one response per each status code. but if there're any cases that show otherwise, I would like to know the scenarios and the design intention.

**Comment by markcowl** [comment]
Oh, I see, you have multiple HttpResponseContent under the single response.

This is an unfortunate consequence of the fact that any parameter that extends model as a constraint will accept a union of models.  The purpose of this template is to represent resource actions, in which the non-202 response may be non-existent or void in addition to containing a model.  The template already provides a 202 response, so adding another 202 response creates this strange muleiple response body.

I think there is an issue in that multiple response bodies should only occur in the case of differing content-types or a multipart response, so that this should have produced a diagnostic at the http level.  However I think this is too complex a repro for that bug, which is really in the http library.

In this case, for this templte, you should either have the template supply a single success response, or if you need granular control over the 202 response, you should use the ArmResourceActionAsyncBase template instead: https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/operations.tsp#L527

**Comment by qiaozha** [comment]
Thanks @markcowl for providing the context, it does make more sense to me now. 

I tried to change the operation template as the following, it works
```
      alias ArmProviderActionAsync<
        Request extends {} | void,
        Response extends {} | void,
        Parameters extends {} = {},
        LroHeaders extends TypeSpec.Reflection.Model = ArmLroLocationHeader &
          Azure.Core.Foundations.RetryAfterHeader
      > = Azure.ResourceManager.ArmResourceActionAsync<
        PlaceholderResource,
        Request,
        Response,
        BaseParameters = ApiVersionParameter,
        Parameters = Parameters,
        LroHeaders = ArmLroLocationHeader & Azure.Core.Foundations.RetryAfterHeader
      >;
```
