### ISSUE TITLE
[Bug]: Inconsistent OperationStatusResult model in tsp

### ISSUE THREAD

**Issue by harshjangid** [Azure/typespec-azure#939]
### Describe the bug

The current **OperationStatusResult** model in typespec has mandatory `opeartions` parameter, but according to [this](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#azure-asyncoperation-resource-format). It must be optional.

![image](https://github.com/Azure/typespec-azure/assets/40545792/a510f0e4-ba7d-4d23-803c-c21764370994)

### Reproduction

Inspect OperationStatusResult model from `Azure.ResourceManager.Foundations.OperationStatusResult`

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pshao25** [comment]
Additional information: in swagger, it is optional as well.
https://github.com/Azure/azure-rest-api-specs/blob/b5512186602fbe490d273aab7ebddc21f8e7f855/specification/common-types/resource-management/v5/types.json#L463-L468

**Comment by allenjzhang** [comment]
Fixed in pending PR. https://github.com/Azure/typespec-azure/pull/945
