### ISSUE TITLE
Add template for data-plane  HEAD operations

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/typespec-azure#941]
### Clear and concise description of the problem

Some data-plane services define HEAD operations for their services. We currently have a template for ARM specs, but it would be great to also provide one for data-plane specs. 

Examples of brownfield data-plane specs that include HEAD operations:
- App Config: [head op](https://github.com/Azure/azure-rest-api-specs/blob/9582151c5dddde96f2b2c4e3a533c278115140ce/specification/appconfiguration/data-plane/Microsoft.AppConfiguration/stable/1.0/appconfiguration.json#L80)
- File Storage: [head op](https://github.com/Azure/azure-rest-api-specs/blob/9582151c5dddde96f2b2c4e3a533c278115140ce/specification/storage/data-plane/Microsoft.FileStorage/stable/2024-05-04/file.json#L3613)
- Web PubSub: [head op](https://github.com/Azure/azure-rest-api-specs/blob/9582151c5dddde96f2b2c4e3a533c278115140ce/specification/webpubsub/data-plane/WebPubSub/stable/2021-10-01/webpubsub.json#L9)
- Data Lake Storage: [head op](https://github.com/Azure/azure-rest-api-specs/blob/9582151c5dddde96f2b2c4e3a533c278115140ce/specification/storage/data-plane/Microsoft.StorageDataLake/stable/2018-11-09/DataLakeStorage.json#L490)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
est: 5

**Comment by allenjzhang** [comment]
We have recently added ability to override verb. https://github.com/microsoft/typespec/pull/3717

So with this, you can freely override any GET operation template with @head. It will be cleaner to create whole new set of operation templates.

**Comment by catalinaperalta** [comment]
I'm curious how this will impact the generated swagger? For head operations I would only expect the headers to be generated. I'll also give this a try to see what happens
