### ISSUE TITLE
refactor(tcgc): how we can better represent authentication

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#951]
### Clear and concise description of the problem

Our authentication is represented by `SdkCredentialParameter` as follows: https://github.com/Azure/typespec-azure/blob/414e3b201bf2fc0aeadcbc37c15549bfbc379547/packages/typespec-client-generator-core/src/interfaces.ts#L348-L352

There are a few issues:
- We'd better not to use `SdkUnionType` to represent multiple authentication types. We can change to `type: []SdkCredentialType`
- Maybe we should use `[]SdkCredentialParameter` to represent multiple authentication types.
- Or we should use key/value pair in `SdkInitializationType`: https://github.com/Azure/typespec-azure/blob/414e3b201bf2fc0aeadcbc37c15549bfbc379547/packages/typespec-client-generator-core/src/interfaces.ts#L53-L55

change it to
```typescript
export interface SdkInitializationType extends SdkModelType {
  endpoint: SdkEndpointParameter;
  credentials: []SdkCredentialParameter; 
  otherClientParameters: SdkParameter[];
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
I think it's consistent with `SdkUnionType`, because it is a union of credential types. @archerzz can you start a discussion around this issue and see what people's thoughts are?

**Comment by iscai-msft** [comment]
@archerzz I think this issue is the path forward for representing union types of `SdkCredentialTypes`

https://github.com/Azure/typespec-azure/issues/1274

Closing in favor of this, please reopen if you disagree
