### ISSUE TITLE
[TCGC] Provide an information to identify `initialization` is a customized constructor or not

### ISSUE THREAD

**Issue by chunyu3** [Azure/typespec-azure#957]
In SdkClientType, there is an `initialization` property to define how to initialization the client instance( client constructors). 
In .NET, we will generate two set of client constructors, one is the one with required parameters, the other is with all parameters. So we need the parameter list of the client.

And in future, we will need to support `constructor customization` that is user add `@initialize(<parameter-list>)` to define an customized constructor which will be in the `initialization` property.

We need a way to identify if the `initialization` is customized constructor or not. If it is, we will generate additional constructor, if not, we need to follow our .NET constructor rule to generate two set of client constructuors.  

```
export interface SdkClientType<TServiceOperation extends SdkServiceOperation> {
  name: string;
  kind: "client";
  description?: string;
  details?: string;
  initialization: SdkInitializationType;
  apiVersions: string[];
  // fully qualified. Compare to sdkPackage.rootNamespace to figure out where to generate
  nameSpace: string;
  methods: SdkMethod<TServiceOperation>[];
}
```

expected:
- add a property in `SdkInitializationType` to indicate it is customized or not

**Comment by iscai-msft** [comment]
@haolingdong-msft does java need this? If not, I think once we add the `@clientInitialization` decorator, csharp could look into the `.decorators` list that tcgc provides. We could even add a helper function, but long story short, if Java doesn't need this property, I don't think we should add it onto the `initialization` property, and instead should rely on helper methods / `.decorators`

**Comment by haolingdong-msft** [comment]
I don't think we need to know client is using customized constructor or not. Alaos add @weidongxu-microsoft in case I miss anything.

**Comment by iscai-msft** [comment]
@chunyu3 is this still an issue? I'm going to go ahead and close because once we have the `@clientInitialization` decorator, you can tell if it's customized by looking in `.decorators`. Please reopen if there's something I've missed. Thanks!
