### ISSUE TITLE
[tcgc] provide an API to list all supported api-versions for a SDK

### ISSUE THREAD

**Issue by chunyu3** [Azure/typespec-azure#965]
Now when we support versioning, .NET and Java need to generate [ServiceVersion in client](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning-select-api-version). It may not be same as the list of api-versions in main.tsp, in released SDK, the ServiceVersion only contains stable api-versions.

The supported api-versions should follow below rules:

- The api-versions not later than the SDK target api-version, by default the SDK target api-version is the latest one.
- Comply with [Azure API guideline](https://azure.github.io/azure-sdk/general_design.html#service-api-versions): so

1. A stable version of client library(SDK) will target the latest GA api-version by default, and only contains GA api-versions in `ServiceVersion` enum
2. A public beta version(preview version) of client library will target the latest public preview API version by default. It contains all api-versions in `ServiceVersion` enum.

Those rules are for all languages, so it is better for TCGC to provide an API to list out all the supported Api-version for a SDK.

**Comment by iscai-msft** [comment]
We could start with a helper function that is called `isStable` in tcgc, that initially only checks azure sdks based off of naming conventions. Once the typespec versioning library adds additional metadata about the stability of a defined api version, we can add those checks to the `isStable` function as well

**Comment by iscai-msft** [comment]
@johanste for a stable release of an SDK, do we want to include preview api versions in documentation for clients?

**Comment by srnagar** [comment]
## Versions in main.tsp
```
2020-01-01-Preview
2021-01-01
2022-01-01-Preview
2023-01-01
2024-01-01-Preview
```

Introduce a new API in TCGC `listFilteredVersions()`.

## Case 1
tspconfig.yaml
```
api-version: 2022-01-01-Preview
```

`listFilteredVersions` -> returns 
```
2020-01-01-Preview
2021-01-01
2022-01-01-Preview
```

## Case 2
tspconfig.yaml
```
api-version: 2023-01-01
```

`listFilteredVersions` -> returns 
```
2021-01-01
2023-01-01
```

## Case 3
No API version in tspconfig

`listFilteredVersions` -> returns 
```
2020-01-01-Preview
2021-01-01
2022-01-01-Preview
2023-01-01
2024-01-01-Preview
```

**Comment by chunyu3** [comment]
This PR https://github.com/Azure/typespec-azure/pull/1045 only filter the `SdkVersionEnum`, but it not filter apiVersions in sdkClient.

**Comment by iscai-msft** [comment]
@chunyu3 The thinking here is that we don't want to completely remove previous api version information from clients, we just don't want to document them as much. Languages like Python etc can still function with a client from an older api version. Can you explain how you're using `client.apiVersions`?

**Comment by tadelesh** [comment]
@chunyu3 synced with izzy, you could use usage (api version) to filter the enum list to get the api version enum to unblock your work. for multi-service concern, we could continue the discussion in this issue.

**Comment by haolingdong-msft** [comment]
Try to write an adoption guide for the case where we do not want the TCGC filtering logic and want `sdkpackage` to include both preview version and stable version, we can use below workaround when `createSdkContext`
```ts
this.sdkContext = await createSdkContext(this.emitterContext, "@azure-tools/typespec-java", {versioning:  {previewStringRegex: /$/}}); // this means TCGC will not match any version as perview version, so TCGC will include all versions
```
/cc @tadelesh  @weidongxu-microsoft

**Comment by iscai-msft** [comment]
Closing because I think the issue has been addressed, thanks!

**Comment by chunyu3** [comment]
> Try to write an adoption guide for the case where we do not want the TCGC filtering logic and want `sdkpackage` to include both preview version and stable version, we can use below workaround when `createSdkContext`
> 
> ```ts
> this.sdkContext = await createSdkContext(this.emitterContext, "@azure-tools/typespec-java", {versioning:  {previewStringRegex: /$/}}); // this means TCGC will not match any version as perview version, so TCGC will include all versions
> ```
> 
> /cc @tadelesh @weidongxu-microsoft

It is a workaround . but I think it is good to provide an way to ignore preview/stable api-version filtering. because in non-branding SDKs, they will not filter out preview api-versions. I think it is better that `previewStringRegex` is null (not set) by default, and azure sdk emitter will set this if they want to filter.
