### ISSUE TITLE
[Bug]: location not required for TrackedResource by typespec-autorest

### ISSUE THREAD

**Issue by cataggar** [Azure/typespec-azure#970]
### Describe the bug

In `TrackedResource`, the `location` is not optional. It does not have a `?`.

https://github.com/Azure/typespec-azure/blob/85171a8b2f284c4c07c6a8237dfe55562fc5cf51/packages/typespec-azure-resource-manager/lib/common-types/types.tsp#L58-L64

Our 2023-03-01 [spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/vmware/resource-manager/Microsoft.AVS/stable/2023-03-01/vmware.json#L5799-L5805) prior to TypeSpec has:

``` json
    "PrivateCloud": {
      "type": "object",
      "description": "A private cloud resource",
      "required": [
        "location",
        "sku"
      ],
```

For our 2023-09-01 [spec](https://github.com/Azure/azure-rest-api-specs/blob/b22c642b361e6d6e7d72a2347a09b0bcf6075d70/specification/vmware/Microsoft.AVS/models.tsp#L624) it is using TypeSpec with:

``` tsp
model PrivateCloud is TrackedResource<PrivateCloudProperties> {
```

and typespec-autorest [generates](https://github.com/Azure/azure-rest-api-specs/blob/b22c642b361e6d6e7d72a2347a09b0bcf6075d70/specification/vmware/resource-manager/Microsoft.AVS/stable/2023-09-01/vmware.json#L8710-L8712):

``` json
"required": [
        "sku"
      ],
```

### Reproduction

The basic RM examples does it:
https://azure.github.io/typespec-azure/playground?options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D&sample=Azure+Resource+Manager+framework

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
Hey @cataggar I don't really see how the example reproduce this, the `TrackedResource` you linked is also different from the one you use to build yours(linked one is in the foundations namespace and is replaced by the $ref to the common types library). The tracked resource you use is this one https://github.com/Azure/typespec-azure/blob/a8f03375864cc0ca3394e99e5af18047209e4d9f/packages/typespec-azure-resource-manager/lib/models.tsp#L42

**Comment by abatishchev** [comment]
I don't see this to be an issue. Your spec references Common Types v5 which define TrackedResource as:

https://github.com/Azure/azure-rest-api-specs/blob/0d5a4226bcd5966d15e2335a976c239431b0d414/specification/common-types/resource-management/v5/types.json#L56-84

**Comment by markcowl** [comment]
Yes, in both the typespec and the generated swagger, your Resource type has 'location' as required.  In the case of Swagger, the common schema your resource is 'allOf'  has required location (your resource inherits the validations from that schema, by definition).  In the case of TypeSpec, you extend a type that has required location.  The API in this case is equivalent.
