### ISSUE TITLE
[Linter rule] Add warning if service spec uses internal .Private namespace

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#977]
Having access to .Private namespace is strongly discouraged. TypeSpec team needs to review any specs with usage to .Private namespace. This is to avoid future breaking changes AND incorporate any deficiencies that forces Specs to use it for only temporary purposes.

Should apply to both:
- Azure.Core
- Azure.ResourceManager.

**Comment by markcowl** [comment]
est: 3
