### ISSUE TITLE
feat(tcgc): `SdkMethodParameter` should have a way to know `location`

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#981]
### Clear and concise description of the problem

A parameter of `SdkServiceMethod` (https://github.com/Azure/typespec-azure/blob/f63d6d741ef07158f3348df0198bf8f013cd178b/packages/typespec-client-generator-core/src/interfaces.ts#L483) could be:
- query parameter
- header parameter
- path parameter
- body parameter (spread or not spread)

There is no easy way to find the `location` of the `SdkMethodParameter`.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment]
@archerzz can you explain why you need `SdkMethodParameter` to know location?

**Comment by archerzz** [comment]
> @archerzz can you explain why you need `SdkMethodParameter` to know location?

Hi @iscai-msft The reason behind is that we need to know how to covert `SdkMethodParameter` into HTTP request. For example, when a model is spread, its properties will be the parameters in `SdkServiceMethod`. So, when the generator parses the definition, it needs to know the corresponding parameters should be composed into a model. The `location` is to identify the mapping.

For now, .net actually uses the underlying `SdkHttpOperation`, parses its parameters to get all the information. That works fine. 

And to be honest, for code generation, maybe `SdkHttpOperation` is more important. For example, people can define a constant HTTP parameter which will not show up in the `SdkServiceMethod`, but generators need to know it so that correct codes can be generated. From that perspective, this issue is not high priority, since we have to parse `SdkHttpOperation` anyway.

**Comment by tadelesh** [comment]
we want to sperate the user interface with the protocol. so sdkmethodparameter will not contain any protocol info. so, like you mentioned, you need to use correspondingMethodParams from sdkserviceopertion's parameters.
