### ISSUE TITLE
Directory Structure Expected by the xamples-directory Emitter Option and What OAV Outputs are Different

### ISSUE THREAD

**Issue by bhaden94** [Azure/typespec-azure#983]
I am a little confused on how the [generated examples from OAV](https://azure.github.io/typespec-azure/docs/howtos/migrate-swagger/x-ms-examples#generate-the-examples) and the [x-ms-examples `examples-directory` option](https://azure.github.io/typespec-azure/docs/howtos/migrate-swagger/x-ms-examples) for the `typespec-autorest` emitter works together in a multiple API version scenario.

The `examples-directory` option is expecting the folder structure to be `examples/<api-verison>/<example-name>.json`.
However, OAV is generating examples for the passed in OpenAPI spec, which outputs in the structure `<api-version>/examples/<examlpe-name>.json`.

Something that I tried is to define the `examples-directory` similar to the `
output-file` emitter option. It looked like this: `examples-directory: {azure-resource-provider-folder}/{service-name}/{version-status}/{version}/examples`.
This did not work since the service-name, version-status, and version variables are not provided like the `output-file` option does.

This is sort of an easy issue to handle with a short script, but it seems like these should work together and expect/output the same structure.

**Comment by timotheeguerin** [comment]
There is supposed to be a copy of examples. The typespec examples then get copied to the swagger output dir. See this doc https://azure.github.io/typespec-azure/docs/howtos/migrate-swagger/x-ms-examples

**Comment by bhaden94** [comment]
@timotheeguerin Yes, I am using that documentation. My order of operations looks like this:

1. Run the autorest emitter, which outputs my OpenAPI specifications. Let's assume I don't already have examples.
    * We have multiple API versions, so the output looks like this: `resource-manager/{service-name}/{version-status}/{version}/openapi.json`
1. Run `oav generate-examples` against each generated OpenAPI specifications. **oav does not have a way to specify the output directory.**
    * The generated examples will be put right next to the OpenApi specification, which looks like this: `resource-manager/{service-name}/{version-status}/{version}/examples/{example-name}.json`
1. Create an examples folder alongside my TSP files. Create a folder inside for each API version.
1. Copy the examples from the oav output to their correct API version folder.
1. Re-run the autorest emitter with the correct examples-directory option.
1. See the `x-ms-examples` property added in my new OpenApi specifications.

I understand it is difficult to handle the Generate OpenApi specs -> generate examples -> generate OpenApi specs again, order of operations, but it would be nice if I didn't have to perform steps 3 and 4 from above.

Am I doing things in a wrong order or have folder structures incorrect that is making this harder than it needs to be?

**Comment by timotheeguerin** [comment]
no that is the expected order today, and yeah it is not ideal but this is the way we have it now to keep working with the swagger flow. It might be more helpful and easier for now that oav support an output dir you can use to do step 2-4 in one

**Comment by bhaden94** [comment]
Okay, thanks for the quick responses! At least I know this is the current expected order.
