### ISSUE TITLE
Add filterAPIVersion helper than filter GA/preview

### ISSUE THREAD

**Issue by lmazuel** [Azure/typespec-azure#984]
Add an helper function `filterGaApiVersion` (name TBD), that will filter the api-version enum according to the targeted api-version for Azure:
- If api-version is YYYY-MM-DD, keep only API-versions of that shape (remove everything that ends with `-preview`)
- Else, return all api-versions

If flavor is not Azure, don't do filtering yet (see https://github.com/microsoft/typespec/issues/3482)

**Comment by iscai-msft** [comment]
closing in favor of duplicate issue #965
