### ISSUE TITLE
[Breaking Change Review] Removal of autorest dependency from typespec-azure-resource-manager

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#986]
**Describe the breaking change**
Remove dependency on autorest emitter from arm library to allow tcgc to depend on this library and remove any openapi specific handling

Autorest import is not something any azure specs should be using so it shouldn't be breaking anyone that did things correctly.
**Back-compat design to avoid immediate breaking**
```
import "@azure-tools/typespec-autorest";
```

**Impact**
This change affecting:

- [x] ARM
- [ ] Data-plane
- [ ] Existing specs: approx. 1
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: June 2024

**Additional information**
Add any other information about the change including fixes for here.

**Comment by markcowl** [comment]
I already added this to the original issue
