### ISSUE TITLE
[Bug] TCGC ignores core models, missing template params

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#99]
For reference https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/payload/pageable

Generating this results in an empty `sdkPackage.models` array.

**Comment by iscai-msft** [comment]
@jhendrixMSFT this is because by default we filter out core models. If you pass `filter-out-core-models: false` to the command line, then these won't be filtered out. Closing in favor of another issue that is related https://github.com/Azure/typespec-azure/issues/204
