### ISSUE TITLE
[Bug]: `SdkHttpResponse.contentTypes?` can be empty array

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#992]
### Describe the bug

**minor**

`SdkHttpResponse.contentTypes` is an optional array: https://github.com/Azure/typespec-azure/blob/d30db5bd8bf78c5eb237ea8cdbc0e98755a86be1/packages/typespec-client-generator-core/src/interfaces.ts#L435-L440

So it would be better to either a non-empty array or `undefined`, but not an empty array.

### Reproduction

Try to parse a spec like https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/authentication/http/custom/main.tsp

You'll find the `contentTypes` is an empty array.
![image](https://github.com/Azure/typespec-azure/assets/4516/20e95059-3f4c-4676-8eb8-d482f0df2f3e)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iscai-msft** [comment]
good point, let me fix this
